/*2023-10-04T11:03:56-01:00*/

/********************************************************************
 * product_killer.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__PRODUCT_KILLER_H
#define _MOTION_CONTROL__PRODUCT_KILLER_H


/********************** Variable declarations ***********************/

extern CB_Index product_killer__num;
extern CB_Mem_Int *product_killer_status_act_prod;
extern CB_Mem_Float *product_killer_m11;
extern CB_Mem_Float *product_killer_m12;
extern CB_Mem_Float *product_killer_m13;
extern CB_Mem_Float *product_killer_m14;
extern CB_Mem_Float *product_killer_m21;
extern CB_Mem_Float *product_killer_m22;
extern CB_Mem_Float *product_killer_m23;
extern CB_Mem_Float *product_killer_m24;
extern CB_Mem_Float *product_killer_m31;
extern CB_Mem_Float *product_killer_m32;
extern CB_Mem_Float *product_killer_m33;
extern CB_Mem_Float *product_killer_m34;
extern CB_Mem_Float *product_killer_m41;
extern CB_Mem_Float *product_killer_m42;
extern CB_Mem_Float *product_killer_m43;
extern CB_Mem_Float *product_killer_m44;
extern CB_Mem_Bool *product_killer_isActive;

/********************** Function declarations ***********************/

extern int _motion_control__product_killer_init(void);
extern int motion_control__product_killer(void);

/************************** Access macros ***************************/

#define mx_acces_motion_control__product_killer__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_control__product_killer__m11 Float[0].CB_current_value
#define mx_acces_motion_control__product_killer__m12 Float[1].CB_current_value
#define mx_acces_motion_control__product_killer__m13 Float[2].CB_current_value
#define mx_acces_motion_control__product_killer__m14 Float[3].CB_current_value
#define mx_acces_motion_control__product_killer__m21 Float[4].CB_current_value
#define mx_acces_motion_control__product_killer__m22 Float[5].CB_current_value
#define mx_acces_motion_control__product_killer__m23 Float[6].CB_current_value
#define mx_acces_motion_control__product_killer__m24 Float[7].CB_current_value
#define mx_acces_motion_control__product_killer__m31 Float[8].CB_current_value
#define mx_acces_motion_control__product_killer__m32 Float[9].CB_current_value
#define mx_acces_motion_control__product_killer__m33 Float[10].CB_current_value
#define mx_acces_motion_control__product_killer__m34 Float[11].CB_current_value
#define mx_acces_motion_control__product_killer__m41 Float[12].CB_current_value
#define mx_acces_motion_control__product_killer__m42 Float[13].CB_current_value
#define mx_acces_motion_control__product_killer__m43 Float[14].CB_current_value
#define mx_acces_motion_control__product_killer__m44 Float[15].CB_current_value
#define mx_acces_motion_control__product_killer__isActive Bool[0].CB_current_value

#endif /*_MOTION_CONTROL__PRODUCT_KILLER_H*/
