/*2023-10-04T11:03:50-01:00*/

/********************************************************************
 * cam_profile.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__CAM_PROFILE_H
#define _MOTION_LIB__CAM_PROFILE_H


/********************** Variable declarations ***********************/

extern CB_Index cam_profile__num;
extern CB_Mem_Char *cam_profile_name;
extern CB_Mem_Int *cam_profile_nbPoints;
extern CB_Mem_Float *cam_profile_MasterPoints;
extern CB_Mem_Float *cam_profile_SlavePoints;
extern CB_Mem_Int *cam_profile_pointer;
extern CB_Mem_Bool *cam_profile_initialized;
extern CB_Mem_Int *cam_profile_pFile;
extern CB_Mem_Bool *cam_profile_fault_reading;
extern CB_Mem_Bool *cam_profile_fault_openning;
extern CB_Mem_Char *cam_profile_complete_path;

/********************** Function declarations ***********************/

extern int _motion_lib__cam_profile_init(void);
extern int motion_lib__cam_profile(void);

#endif /*_MOTION_LIB__CAM_PROFILE_H*/
