/*2023-10-04T11:03:50-01:00*/

/********************************************************************
 * cam_profile.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "cam_profile.h"

#include <stdint.h>
#include <sys/time.h>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <psapi.h>
#include <shlwapi.h>


char projPath[MAX_PATH];
int iPath;

char* ptrToPathProjet;
char completPathToFile[MAX_PATH];

void trim(char * s) {
    char * p = s;
    int l = strlen(p);

    while(isspace(p[l - 1])) p[--l] = 0;
    while(* p && isspace(* p)) ++p, --l;

    memmove(s, p, l + 1);
}


typedef struct camTableStruct
{  
	float master[7000];
	float slave[7000];
} camTableStruct;

camTableStruct *camTable;

/**************************** Variables *****************************/

CB_Index cam_profile__num = 0;
CB_Mem_Char *cam_profile_name;
CB_Mem_Int *cam_profile_nbPoints;
CB_Mem_Float *cam_profile_MasterPoints;
CB_Mem_Float *cam_profile_SlavePoints;
CB_Mem_Int *cam_profile_pointer;
CB_Mem_Bool *cam_profile_initialized;
CB_Mem_Int *cam_profile_pFile;
CB_Mem_Bool *cam_profile_fault_reading;
CB_Mem_Bool *cam_profile_fault_openning;
CB_Mem_Char *cam_profile_complete_path;

/**************************** Variables *****************************/

#define name(i) (cam_profile_name[i+2].CB_current_value)
#define nbPoints (*((short *)&(cam_profile_nbPoints->CB_current_value) + ALIGN_OFFSET_SHORT))
#define MasterPoints(i) (cam_profile_MasterPoints[i+1].CB_current_value)
#define SlavePoints(i) (cam_profile_SlavePoints[i+1].CB_current_value)
#define pointer (cam_profile_pointer->CB_current_value)
#define initialized (cam_profile_initialized->CB_current_value)
#define pFile (cam_profile_pFile->CB_current_value)
#define fault_reading (cam_profile_fault_reading->CB_current_value)
#define fault_openning (cam_profile_fault_openning->CB_current_value)
#define complete_path(i) (cam_profile_complete_path[i+2].CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_lib__cam_profile_init(void)
{
	(cam_profile_name+0)->CB_current_value = 0; /*name size1*/
	(cam_profile_name+1)->CB_current_value = 50; /*name size2*/
	(cam_profile_name+3)->CB_current_value = 'd'; /*name[1]*/
	(cam_profile_name+4)->CB_current_value = 'e'; /*name[2]*/
	(cam_profile_name+5)->CB_current_value = 'f'; /*name[3]*/
	(cam_profile_name+6)->CB_current_value = 'a'; /*name[4]*/
	(cam_profile_name+7)->CB_current_value = 'u'; /*name[5]*/
	(cam_profile_name+8)->CB_current_value = 'l'; /*name[6]*/
	(cam_profile_name+9)->CB_current_value = 't'; /*name[7]*/
	(cam_profile_name+10)->CB_current_value = '.'; /*name[8]*/
	(cam_profile_name+11)->CB_current_value = 't'; /*name[9]*/
	(cam_profile_name+12)->CB_current_value = 'x'; /*name[10]*/
	(cam_profile_name+13)->CB_current_value = 't'; /*name[11]*/
	(self.Char+0+0)->CB_current_value = 0; /*complete_path size1*/
	(self.Char+0+1)->CB_current_value = 254; /*complete_path size2*/
	self.Bool+=3;
	self.Int+=1;
	self.Char+=257;


	return 0;
}


/************************ Behavior function *************************/

int motion_lib__cam_profile(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		cam_profile_initialized = self.Bool+0;
		cam_profile_pFile = self.Int+0;
		cam_profile_fault_reading = self.Bool+1;
		cam_profile_fault_openning = self.Bool+2;
		cam_profile_complete_path = self.Char+0;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category : motion_control						*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2021							*/
			/* ----------------------------------------------------------------	*/
			/* This module prepares one cam profile tables for the module		*/
			/* cam_computation								*/
			/* It reads a file made of pair of values :				*/
			/* 	<master coord><tab><slave coord>					*/
			/* The input file need to be located in the folder 			*/
			/* 	/Configuration/camProfiles/						*/
			/* of the ControlBuild project						*/
			/* ----------------------------------------------------------------	*/

			if(!initialized)
			{
				initialized = 1;
				fault_openning = 0;
				fault_reading = 0;
				//récupération du chemin complet d'exécution
				GetModuleFileNameA(GetModuleHandle(NULL), projPath, sizeof(projPath));
				for (iPath=0;iPath<6;iPath++) {
					if ((ptrToPathProjet=strrchr(projPath, '\\')) || (ptrToPathProjet=strrchr(projPath, '/')))
						*(ptrToPathProjet) = 0;
				}
				strncpy (completPathToFile, projPath, MAX_PATH);
				strcat(completPathToFile, "/Configuration/camProfiles/");
				completPathToFile[strlen(completPathToFile)] = '\0';

				int inc;
				for(inc=1;inc<=50;inc++){	
					completPathToFile[strlen(completPathToFile)] = name(inc);
				}
				for(inc=1;inc<=254;inc++){	
					complete_path(inc) = completPathToFile[inc-1];
				}

				pFile = fopen(completPathToFile, "r");
				pointer = (camTableStruct*)malloc(sizeof(camTableStruct));
				camTable = pointer;

				if (pFile == 0) {
					fault_openning = 1;
				} else {
					int fin = 0;
					nbPoints = 0;
					while(fin==0) {
						static char str[BUFSIZ];
						char *masterPosC, *slavePosC;
						float masterPos, slavePos;
						if(fgets(str, BUFSIZ, pFile) <= 0) {
							fin = 1;
						} else {
							nbPoints++;
							trim(str);
							if (strlen(str)>1) {
								if (str[strlen(str)-1]=='\n')
									str[strlen(str)-1] = '\0';
								masterPosC = strtok( str, "\t" );
								slavePosC = strtok( NULL, "\t");
								if (slavePosC==NULL || masterPosC==NULL) {
									fault_reading = 1;
								} else {
									sscanf(masterPosC, "%f", &masterPos);
									sscanf(slavePosC, "%f", &slavePos);
									if (nbPoints < 100) {
										MasterPoints(nbPoints) = masterPos;
										SlavePoints(nbPoints) = slavePos;
									}
									camTable->master[nbPoints-1] = masterPos;
									camTable->slave[nbPoints-1] = slavePos;
								}
							}
						}
					}
				}
				initialized = 1;
			}











		}

		CB_post_int(cam_profile_nbPoints);
		{int _k; for (_k = 2; _k < 102; _k++) { CB_post_float(cam_profile_MasterPoints+_k); }}
		{int _k; for (_k = 2; _k < 102; _k++) { CB_post_float(cam_profile_SlavePoints+_k); }}
		CB_post_int(cam_profile_pointer);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 3;
	self.Int += 1;
	self.Char += 257;

	return 0;
}

