/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * conveyor.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"
#include "cb_products_iec.h"

#include "conveyor.h"



/**************************** Variables *****************************/

CB_Index conveyor__num = 0;
CB_Mem_Float *conveyor_incPositionX;
CB_Mem_Float *conveyor_incPositionY;
CB_Mem_Float *conveyor_incPositionZ;
CB_Mem_Float *conveyor_coordCenterX;
CB_Mem_Float *conveyor_coordCenterY;
CB_Mem_Float *conveyor_coordCenterZ;
CB_Mem_Float *conveyor_incRotationX;
CB_Mem_Float *conveyor_incRotationY;
CB_Mem_Float *conveyor_incRotationZ;
CB_Mem_Float *conveyor_linearSpeed;
CB_Mem_Int *conveyor_status_act_prod;
CB_Mem_Float *conveyor_m11;
CB_Mem_Float *conveyor_m12;
CB_Mem_Float *conveyor_m13;
CB_Mem_Float *conveyor_m14;
CB_Mem_Float *conveyor_m21;
CB_Mem_Float *conveyor_m22;
CB_Mem_Float *conveyor_m23;
CB_Mem_Float *conveyor_m24;
CB_Mem_Float *conveyor_m31;
CB_Mem_Float *conveyor_m32;
CB_Mem_Float *conveyor_m33;
CB_Mem_Float *conveyor_m34;
CB_Mem_Float *conveyor_m41;
CB_Mem_Float *conveyor_m42;
CB_Mem_Float *conveyor_m43;
CB_Mem_Float *conveyor_m44;
CB_Mem_Float *conveyor_incrementPositionX;
CB_Mem_Float *conveyor_incrementPositionY;
CB_Mem_Float *conveyor_incrementPositionZ;
CB_Mem_Float *conveyor_incShiftProduct;
CB_Mem_Float *conveyor_centerRotX;
CB_Mem_Float *conveyor_centerRotY;
CB_Mem_Float *conveyor_centerRotZ;
CB_Mem_Float *conveyor_incRotY;
CB_Mem_Float *conveyor_incRotZ;
CB_Mem_Float *conveyor_incRotX;
CB_Mem_Bool *conveyor_d_locking;
CB_Mem_Bool *conveyor_v_d_locking;

/**************************** Variables *****************************/

#define incPositionX (conveyor_incPositionX->CB_current_value)
#define incPositionY (conveyor_incPositionY->CB_current_value)
#define incPositionZ (conveyor_incPositionZ->CB_current_value)
#define coordCenterX (conveyor_coordCenterX->CB_current_value)
#define coordCenterY (conveyor_coordCenterY->CB_current_value)
#define coordCenterZ (conveyor_coordCenterZ->CB_current_value)
#define incRotationX (conveyor_incRotationX->CB_current_value)
#define incRotationY (conveyor_incRotationY->CB_current_value)
#define incRotationZ (conveyor_incRotationZ->CB_current_value)
#define linearSpeed (conveyor_linearSpeed->CB_current_value)
#define status_act_prod (conveyor_status_act_prod->CB_current_value)
#define m11 (conveyor_m11->CB_current_value)
#define m12 (conveyor_m12->CB_current_value)
#define m13 (conveyor_m13->CB_current_value)
#define m14 (conveyor_m14->CB_current_value)
#define m21 (conveyor_m21->CB_current_value)
#define m22 (conveyor_m22->CB_current_value)
#define m23 (conveyor_m23->CB_current_value)
#define m24 (conveyor_m24->CB_current_value)
#define m31 (conveyor_m31->CB_current_value)
#define m32 (conveyor_m32->CB_current_value)
#define m33 (conveyor_m33->CB_current_value)
#define m34 (conveyor_m34->CB_current_value)
#define m41 (conveyor_m41->CB_current_value)
#define m42 (conveyor_m42->CB_current_value)
#define m43 (conveyor_m43->CB_current_value)
#define m44 (conveyor_m44->CB_current_value)
#define incrementPositionX (conveyor_incrementPositionX->CB_current_value)
#define incrementPositionY (conveyor_incrementPositionY->CB_current_value)
#define incrementPositionZ (conveyor_incrementPositionZ->CB_current_value)
#define incShiftProduct (conveyor_incShiftProduct->CB_current_value)
#define centerRotX (conveyor_centerRotX->CB_current_value)
#define centerRotY (conveyor_centerRotY->CB_current_value)
#define centerRotZ (conveyor_centerRotZ->CB_current_value)
#define incRotY (conveyor_incRotY->CB_current_value)
#define incRotZ (conveyor_incRotZ->CB_current_value)
#define incRotX (conveyor_incRotX->CB_current_value)
#define d_locking (conveyor_d_locking->CB_current_value)
#define v_d_locking (conveyor_v_d_locking->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_lib__conveyor_init(void)
{
	(self.Float+0)->CB_current_value = 1.0; /*m11*/
	(self.Float+5)->CB_current_value = 1.0; /*m22*/
	(self.Float+10)->CB_current_value = 1.0; /*m33*/
	(self.Float+15)->CB_current_value = 1.0; /*m44*/
	self.Bool+=2;
	self.Int+=1;
	self.Float+=26;


	return 0;
}


/************************ Behavior function *************************/

int motion_lib__conveyor(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		conveyor_status_act_prod = self.Int+0;
		conveyor_m11 = self.Float+0;
		conveyor_m12 = self.Float+1;
		conveyor_m13 = self.Float+2;
		conveyor_m14 = self.Float+3;
		conveyor_m21 = self.Float+4;
		conveyor_m22 = self.Float+5;
		conveyor_m23 = self.Float+6;
		conveyor_m24 = self.Float+7;
		conveyor_m31 = self.Float+8;
		conveyor_m32 = self.Float+9;
		conveyor_m33 = self.Float+10;
		conveyor_m34 = self.Float+11;
		conveyor_m41 = self.Float+12;
		conveyor_m42 = self.Float+13;
		conveyor_m43 = self.Float+14;
		conveyor_m44 = self.Float+15;
		conveyor_incrementPositionX = self.Float+16;
		conveyor_incrementPositionY = self.Float+17;
		conveyor_incrementPositionZ = self.Float+18;
		conveyor_incShiftProduct = self.Float+19;
		conveyor_centerRotX = self.Float+20;
		conveyor_centerRotY = self.Float+21;
		conveyor_centerRotZ = self.Float+22;
		conveyor_incRotY = self.Float+23;
		conveyor_incRotZ = self.Float+24;
		conveyor_incRotX = self.Float+25;
		conveyor_d_locking = self.Bool+0;
		conveyor_v_d_locking = self.Bool+1;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Actor Myself init *************************/

		setMyselfFor(self_num);

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Actors and Products						*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates the behaviour of a roller table.		*/
			/* It takes a linear speed coming from a gear motor as input.		*/
			/* It can  be associated with equipements such as rotary plate ring,	*/
			/* traverser, ...								*/
			/* It can be used to shift the products that are in interaction with	*/
			/* it.										*/
			/* ----------------------------------------------------------------	*/


			/* ----------------------------------------------------------------	*/
			/* Compute the product traverse speed					*/
			/* ----------------------------------------------------------------	*/
			if (!d_locking)
				incShiftProduct=(linearSpeed*CLOCK_PERIOD/1000000.0);
			else
				incShiftProduct=0;

			/* ----------------------------------------------------------------	*/
			/* Association with an traverser : take account of the traverse 	*/
			/* speed of the traverser							*/
			/* ----------------------------------------------------------------	*/
			if (incPositionX != 0.0) moveXBy(myself, incPositionX);
			if (incPositionY != 0.0) moveYBy(myself, incPositionY);
			if (incPositionZ != 0.0) moveZBy(myself, incPositionZ);

			/* ----------------------------------------------------------------	*/
			/* Association with a rotary plate ring : take account of the 	*/
			/* rotation speed of the plate						*/
			/* ----------------------------------------------------------------	*/
			if ((incRotationY != 0.0) || (incRotationZ != 0.0))
				rotateBy(myself, incRotationX, incRotationY, incRotationZ, coordCenterX, coordCenterY, coordCenterZ);


			/* ----------------------------------------------------------------	*/
			/*  Exchange of informations with products				*/
			/* ----------------------------------------------------------------	*/

			/* => informations coming from rotary plate ring, ...			*/
			centerRotX=coordCenterX;
			centerRotY=coordCenterY;
			centerRotZ=coordCenterZ;
			incRotX=incRotationX;
			incRotY=incRotationY;
			incRotZ=incRotationZ;

			/* => informations coming from traverser, ...				*/
			incrementPositionX=incPositionX;
			incrementPositionY=incPositionY;
			incrementPositionZ=incPositionZ;



		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 2;
	self.Int += 1;
	self.Float += 26;

	return 0;
}

