/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * conveyor.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__CONVEYOR_H
#define _MOTION_LIB__CONVEYOR_H


/********************** Variable declarations ***********************/

extern CB_Index conveyor__num;
extern CB_Mem_Float *conveyor_incPositionX;
extern CB_Mem_Float *conveyor_incPositionY;
extern CB_Mem_Float *conveyor_incPositionZ;
extern CB_Mem_Float *conveyor_coordCenterX;
extern CB_Mem_Float *conveyor_coordCenterY;
extern CB_Mem_Float *conveyor_coordCenterZ;
extern CB_Mem_Float *conveyor_incRotationX;
extern CB_Mem_Float *conveyor_incRotationY;
extern CB_Mem_Float *conveyor_incRotationZ;
extern CB_Mem_Float *conveyor_linearSpeed;
extern CB_Mem_Int *conveyor_status_act_prod;
extern CB_Mem_Float *conveyor_m11;
extern CB_Mem_Float *conveyor_m12;
extern CB_Mem_Float *conveyor_m13;
extern CB_Mem_Float *conveyor_m14;
extern CB_Mem_Float *conveyor_m21;
extern CB_Mem_Float *conveyor_m22;
extern CB_Mem_Float *conveyor_m23;
extern CB_Mem_Float *conveyor_m24;
extern CB_Mem_Float *conveyor_m31;
extern CB_Mem_Float *conveyor_m32;
extern CB_Mem_Float *conveyor_m33;
extern CB_Mem_Float *conveyor_m34;
extern CB_Mem_Float *conveyor_m41;
extern CB_Mem_Float *conveyor_m42;
extern CB_Mem_Float *conveyor_m43;
extern CB_Mem_Float *conveyor_m44;
extern CB_Mem_Float *conveyor_incrementPositionX;
extern CB_Mem_Float *conveyor_incrementPositionY;
extern CB_Mem_Float *conveyor_incrementPositionZ;
extern CB_Mem_Float *conveyor_incShiftProduct;
extern CB_Mem_Float *conveyor_centerRotX;
extern CB_Mem_Float *conveyor_centerRotY;
extern CB_Mem_Float *conveyor_centerRotZ;
extern CB_Mem_Float *conveyor_incRotY;
extern CB_Mem_Float *conveyor_incRotZ;
extern CB_Mem_Float *conveyor_incRotX;
extern CB_Mem_Bool *conveyor_d_locking;
extern CB_Mem_Bool *conveyor_v_d_locking;

/********************** Function declarations ***********************/

extern int _motion_lib__conveyor_init(void);
extern int motion_lib__conveyor(void);

/************************** Access macros ***************************/

#define mx_acces_motion_lib__conveyor__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_lib__conveyor__m11 Float[0].CB_current_value
#define mx_acces_motion_lib__conveyor__m12 Float[1].CB_current_value
#define mx_acces_motion_lib__conveyor__m13 Float[2].CB_current_value
#define mx_acces_motion_lib__conveyor__m14 Float[3].CB_current_value
#define mx_acces_motion_lib__conveyor__m21 Float[4].CB_current_value
#define mx_acces_motion_lib__conveyor__m22 Float[5].CB_current_value
#define mx_acces_motion_lib__conveyor__m23 Float[6].CB_current_value
#define mx_acces_motion_lib__conveyor__m24 Float[7].CB_current_value
#define mx_acces_motion_lib__conveyor__m31 Float[8].CB_current_value
#define mx_acces_motion_lib__conveyor__m32 Float[9].CB_current_value
#define mx_acces_motion_lib__conveyor__m33 Float[10].CB_current_value
#define mx_acces_motion_lib__conveyor__m34 Float[11].CB_current_value
#define mx_acces_motion_lib__conveyor__m41 Float[12].CB_current_value
#define mx_acces_motion_lib__conveyor__m42 Float[13].CB_current_value
#define mx_acces_motion_lib__conveyor__m43 Float[14].CB_current_value
#define mx_acces_motion_lib__conveyor__m44 Float[15].CB_current_value
#define mx_acces_motion_lib__conveyor__incrementPositionX Float[16].CB_current_value
#define mx_acces_motion_lib__conveyor__incrementPositionY Float[17].CB_current_value
#define mx_acces_motion_lib__conveyor__incrementPositionZ Float[18].CB_current_value
#define mx_acces_motion_lib__conveyor__incShiftProduct Float[19].CB_current_value
#define mx_acces_motion_lib__conveyor__centerRotX Float[20].CB_current_value
#define mx_acces_motion_lib__conveyor__centerRotY Float[21].CB_current_value
#define mx_acces_motion_lib__conveyor__centerRotZ Float[22].CB_current_value
#define mx_acces_motion_lib__conveyor__incRotY Float[23].CB_current_value
#define mx_acces_motion_lib__conveyor__incRotZ Float[24].CB_current_value
#define mx_acces_motion_lib__conveyor__incRotX Float[25].CB_current_value
#define mx_acces_motion_lib__conveyor__d_locking Bool[0].CB_current_value
#define mx_acces_motion_lib__conveyor__v_d_locking Bool[1].CB_current_value

#endif /*_MOTION_LIB__CONVEYOR_H*/
