/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * conveyors.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _FLASK_MOTION_APP__CONVEYORS_H
#define _FLASK_MOTION_APP__CONVEYORS_H


/********************** Variable declarations ***********************/

extern CB_Index conveyors__num;
extern CB_Mem_Bool *conveyors_forwardUp;
extern CB_Mem_Bool *conveyors_backwardUp;
extern CB_Mem_Bool *conveyors_forwardDw;
extern CB_Mem_Bool *conveyors_backwardDw;
extern CB_Mem_Bool *conveyors_ejectBadProd;
extern CB_Mem_Bool *conveyors_presConvUp;
extern CB_Mem_Bool *conveyors_presConvDw;
extern CB_Mem_Int *conveyors_idRead;
extern CB_Mem_Int *conveyors_mesuredWeight;
extern CB_Mem_Bool *conveyors_bpStart;
extern CB_Mem_Bool *conveyors_bpAuto;
extern CB_Mem_Bool *conveyors_bpManu;
extern CB_Mem_Bool *conveyors_bpEmergencyStop;
extern CB_Mem_Bool *conveyors_bpStop;

/********************** Function declarations ***********************/

extern int _flask_motion_app__conveyors_init(void);
extern int flask_motion_app__conveyors(void);

#endif /*_FLASK_MOTION_APP__CONVEYORS_H*/
