/*2023-10-04T11:04:01-01:00*/

/********************************************************************
 * robot6axis_ctrled.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _ROBOT6AXIS_CTRLED__ROBOT6AXIS_CTRLED_H
#define _ROBOT6AXIS_CTRLED__ROBOT6AXIS_CTRLED_H


/********************** Variable declarations ***********************/

extern CB_Index robot6axis_ctrled__num;
extern CB_Mem_Float *robot6axis_ctrled_armOrigin;
extern CB_Mem_Int *robot6axis_ctrled_profileNr;
extern CB_Mem_Bool *robot6axis_ctrled_HomeCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveVelCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveAbsCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveVel1ManualCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveVel2ManualCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveAbs1ManualCmd;
extern CB_Mem_Bool *robot6axis_ctrled_MoveAbs2ManualCmd;
extern CB_Mem_Bool *robot6axis_ctrled_StopCmd;
extern CB_Mem_Float *robot6axis_ctrled_MovePosition;
extern CB_Mem_Float *robot6axis_ctrled_MoveSpeed;
extern CB_Mem_Float *robot6axis_ctrled_MoveAcceleration;
extern CB_Mem_Float *robot6axis_ctrled_MoveDeceleration;
extern CB_Mem_Float *robot6axis_ctrled_offsetAxToMa;
extern CB_Mem_Bool *robot6axis_ctrled_gripSyringes;
extern CB_Mem_Bool *robot6axis_ctrled_Auto;
extern CB_Mem_Bool *robot6axis_ctrled_Manu;
extern CB_Mem_Bool *robot6axis_ctrled_run;
extern CB_Mem_Float *robot6axis_ctrled_armExtrem;
extern CB_Mem_Float *robot6axis_ctrled_velX;
extern CB_Mem_Float *robot6axis_ctrled_velY;
extern CB_Mem_Float *robot6axis_ctrled_velZ;
extern CB_Mem_Bool *robot6axis_ctrled_armInStop;
extern CB_Mem_Float *robot6axis_ctrled_masterPosition;
extern CB_Mem_Float *robot6axis_ctrled_ActualPositionAx;

/********************** Function declarations ***********************/

extern int _robot6axis_ctrled__robot6axis_ctrled_init(void);
extern int robot6axis_ctrled__robot6axis_ctrled(void);

#endif /*_ROBOT6AXIS_CTRLED__ROBOT6AXIS_CTRLED_H*/
