/*2023-10-04T11:04:01-01:00*/

/********************************************************************
 * robot6axis_ctrled.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "robot6axis_ctrled.h"
#include "robot6axis_ctrled/functional/robot6axis_cams/robot6axis_cams.h"
#include "motion_lib/functional/robot6axis/robot6axis.h"


/**************************** Variables *****************************/

CB_Index robot6axis_ctrled__num = 0;
CB_Mem_Float *robot6axis_ctrled_armOrigin;
CB_Mem_Int *robot6axis_ctrled_profileNr;
CB_Mem_Bool *robot6axis_ctrled_HomeCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveVelCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveAbsCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveVel1ManualCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveVel2ManualCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveAbs1ManualCmd;
CB_Mem_Bool *robot6axis_ctrled_MoveAbs2ManualCmd;
CB_Mem_Bool *robot6axis_ctrled_StopCmd;
CB_Mem_Float *robot6axis_ctrled_MovePosition;
CB_Mem_Float *robot6axis_ctrled_MoveSpeed;
CB_Mem_Float *robot6axis_ctrled_MoveAcceleration;
CB_Mem_Float *robot6axis_ctrled_MoveDeceleration;
CB_Mem_Float *robot6axis_ctrled_offsetAxToMa;
CB_Mem_Bool *robot6axis_ctrled_gripSyringes;
CB_Mem_Bool *robot6axis_ctrled_Auto;
CB_Mem_Bool *robot6axis_ctrled_Manu;
CB_Mem_Bool *robot6axis_ctrled_run;
CB_Mem_Float *robot6axis_ctrled_armExtrem;
CB_Mem_Float *robot6axis_ctrled_velX;
CB_Mem_Float *robot6axis_ctrled_velY;
CB_Mem_Float *robot6axis_ctrled_velZ;
CB_Mem_Bool *robot6axis_ctrled_armInStop;
CB_Mem_Float *robot6axis_ctrled_masterPosition;
CB_Mem_Float *robot6axis_ctrled_ActualPositionAx;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams;
static CB_Offset robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis;
static CB_Offset robot6axis_ctrled__robot6axis_ctrled_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _robot6axis_ctrled__robot6axis_ctrled_init(void)
{
	CB_Object __start = self;
	(robot6axis_ctrled_armOrigin+2)->CB_current_value = 800.0; /*armOrigin[1]*/
	(robot6axis_ctrled_armOrigin+3)->CB_current_value = 400.0; /*armOrigin[2]*/
	(robot6axis_ctrled_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(robot6axis_ctrled_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(robot6axis_ctrled_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	(self.Char+0+0)->CB_current_value = 0; /*_cn_18 size1*/
	(self.Char+0+1)->CB_current_value = 50; /*_cn_18 size2*/
	(self.Char+53+0)->CB_current_value = 0; /*_cn_17 size1*/
	(self.Char+53+1)->CB_current_value = 50; /*_cn_17 size2*/
	(self.Char+106+0)->CB_current_value = 0; /*_cn_16 size1*/
	(self.Char+106+1)->CB_current_value = 50; /*_cn_16 size2*/
	(self.Char+159+0)->CB_current_value = 0; /*_cn_15 size1*/
	(self.Char+159+1)->CB_current_value = 50; /*_cn_15 size2*/
	(self.Char+212+0)->CB_current_value = 0; /*_cn_14 size1*/
	(self.Char+212+1)->CB_current_value = 50; /*_cn_14 size2*/
	(self.Char+265+0)->CB_current_value = 0; /*_cn_13 size1*/
	(self.Char+265+1)->CB_current_value = 50; /*_cn_13 size2*/
	(self.Char+318+0)->CB_current_value = 0; /*_cn_12 size1*/
	(self.Char+318+1)->CB_current_value = 50; /*_cn_12 size2*/
	(self.Char+371+0)->CB_current_value = 0; /*_cn_11 size1*/
	(self.Char+371+1)->CB_current_value = 50; /*_cn_11 size2*/
	(self.Char+424+0)->CB_current_value = 0; /*_cn_10 size1*/
	(self.Char+424+1)->CB_current_value = 50; /*_cn_10 size2*/
	(self.Char+477+0)->CB_current_value = 0; /*_cn_9 size1*/
	(self.Char+477+1)->CB_current_value = 50; /*_cn_9 size2*/
	(self.Char+530+0)->CB_current_value = 0; /*_cn_8 size1*/
	(self.Char+530+1)->CB_current_value = 50; /*_cn_8 size2*/
	(self.Char+583+0)->CB_current_value = 0; /*_cn_7 size1*/
	(self.Char+583+1)->CB_current_value = 50; /*_cn_7 size2*/
	self.Bool+=60;
	self.Float+=127;
	self.Char+=636;

	/*initialize child robot6axis_cams (robot6axis_ctrled.robot6axis_cams):*/
	self_num++;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Char = self.Char - __start.Char;
	robot6axis_cams_profileNr = robot6axis_ctrled_profileNr;
	robot6axis_cams_HomeCmd = robot6axis_ctrled_HomeCmd;
	robot6axis_cams_MoveVelCmd = robot6axis_ctrled_MoveVelCmd;
	robot6axis_cams_MoveAbsCmd = robot6axis_ctrled_MoveAbsCmd;
	robot6axis_cams_MoveVel1ManualCmd = robot6axis_ctrled_MoveVel1ManualCmd;
	robot6axis_cams_MoveVel2ManualCmd = robot6axis_ctrled_MoveVel2ManualCmd;
	robot6axis_cams_MoveAbs1ManualCmd = robot6axis_ctrled_MoveAbs1ManualCmd;
	robot6axis_cams_MoveAbs2ManualCmd = robot6axis_ctrled_MoveAbs2ManualCmd;
	robot6axis_cams_StopCmd = robot6axis_ctrled_StopCmd;
	robot6axis_cams_MovePosition = robot6axis_ctrled_MovePosition;
	robot6axis_cams_MoveSpeed = robot6axis_ctrled_MoveSpeed;
	robot6axis_cams_MoveAcceleration = robot6axis_ctrled_MoveAcceleration;
	robot6axis_cams_MoveDeceleration = robot6axis_ctrled_MoveDeceleration;
	robot6axis_cams_offsetAxToMa = robot6axis_ctrled_offsetAxToMa;
	robot6axis_cams_name1 = __start.Char+583; /*robot6axis_ctrled__cn_7*/
	robot6axis_cams_name2 = __start.Char+530; /*robot6axis_ctrled__cn_8*/
	robot6axis_cams_name3 = __start.Char+477; /*robot6axis_ctrled__cn_9*/
	robot6axis_cams_name4 = __start.Char+424; /*robot6axis_ctrled__cn_10*/
	robot6axis_cams_name5 = __start.Char+371; /*robot6axis_ctrled__cn_11*/
	robot6axis_cams_name6 = __start.Char+318; /*robot6axis_ctrled__cn_12*/
	robot6axis_cams_name1_rej = __start.Char+265; /*robot6axis_ctrled__cn_13*/
	robot6axis_cams_name2_rej = __start.Char+212; /*robot6axis_ctrled__cn_14*/
	robot6axis_cams_name3_rej = __start.Char+159; /*robot6axis_ctrled__cn_15*/
	robot6axis_cams_name4_rej = __start.Char+106; /*robot6axis_ctrled__cn_16*/
	robot6axis_cams_name5_rej = __start.Char+53; /*robot6axis_ctrled__cn_17*/
	robot6axis_cams_name6_rej = __start.Char+0; /*robot6axis_ctrled__cn_18*/
	robot6axis_cams_slavePosition1 = __start.Float+121; /*robot6axis_ctrled__cn_6*/
	robot6axis_cams_slavePosition2 = __start.Float+122; /*robot6axis_ctrled__cn_5*/
	robot6axis_cams_slavePosition3 = __start.Float+123; /*robot6axis_ctrled__cn_4*/
	robot6axis_cams_slavePosition4 = __start.Float+124; /*robot6axis_ctrled__cn_3*/
	robot6axis_cams_slavePosition5 = __start.Float+125; /*robot6axis_ctrled__cn_2*/
	robot6axis_cams_slavePosition6 = __start.Float+126; /*robot6axis_ctrled__cn_1*/
	robot6axis_cams_ActualPositionAx = robot6axis_ctrled_ActualPositionAx;
	robot6axis_cams_masterPosition = robot6axis_ctrled_masterPosition;
	_robot6axis_ctrled__robot6axis_cams_init();

	/*initialize child robot6axis (motion_lib.robot6axis):*/
	self_num++;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis.Char = self.Char - __start.Char;
	robot6axis_armOrigin = robot6axis_ctrled_armOrigin;
	robot6axis_structRotVectorFOOT = __start.Float+116; /*robot6axis_ctrled__cn_19*/
	robot6axis_structRotDegFOOT = __start.Float+115; /*robot6axis_ctrled__cn_20*/
	robot6axis_ownRotDegFOOT = __start.Float+114; /*robot6axis_ctrled__cn_21*/
	robot6axis_structRotVectorFOOT2 = __start.Float+109; /*robot6axis_ctrled__cn_22*/
	robot6axis_structRotDegFOOT2 = __start.Float+108; /*robot6axis_ctrled__cn_23*/
	robot6axis_structRotVectorArm2 = __start.Float+103; /*robot6axis_ctrled__cn_24*/
	robot6axis_structRotDegArm2 = __start.Float+102; /*robot6axis_ctrled__cn_25*/
	robot6axis_driveRotVector1 = __start.Float+97; /*robot6axis_ctrled__cn_26*/
	robot6axis_driveRotVector2 = __start.Float+92; /*robot6axis_ctrled__cn_27*/
	robot6axis_driveRotVector3 = __start.Float+87; /*robot6axis_ctrled__cn_28*/
	robot6axis_driveRotVector4 = __start.Float+82; /*robot6axis_ctrled__cn_29*/
	robot6axis_driveRotVector5 = __start.Float+77; /*robot6axis_ctrled__cn_30*/
	robot6axis_driveRotVector6 = __start.Float+72; /*robot6axis_ctrled__cn_31*/
	robot6axis_structRotVector1RowA = __start.Float+67; /*robot6axis_ctrled__cn_32*/
	robot6axis_structRotDeg1RowA = __start.Float+66; /*robot6axis_ctrled__cn_33*/
	robot6axis_structRotVector1RowB = __start.Float+61; /*robot6axis_ctrled__cn_34*/
	robot6axis_structRotDeg1RowB = __start.Float+60; /*robot6axis_ctrled__cn_35*/
	robot6axis_structRotVectorMultiRowsA = __start.Float+55; /*robot6axis_ctrled__cn_36*/
	robot6axis_structRotDegMultiRowsA = __start.Float+54; /*robot6axis_ctrled__cn_37*/
	robot6axis_structRotVectorMultiRowsB = __start.Float+49; /*robot6axis_ctrled__cn_38*/
	robot6axis_structRotDegMultiRowsB = __start.Float+48; /*robot6axis_ctrled__cn_39*/
	robot6axis_HomeCmd = __start.Bool+59; /*robot6axis_ctrled__cn_40*/
	robot6axis_MoveVelCmd = __start.Bool+58; /*robot6axis_ctrled__cn_41*/
	robot6axis_MoveAbsCmd = __start.Bool+57; /*robot6axis_ctrled__cn_42*/
	robot6axis_MoveVel1ManualCmd = __start.Bool+56; /*robot6axis_ctrled__cn_43*/
	robot6axis_MoveVel2ManualCmd = __start.Bool+55; /*robot6axis_ctrled__cn_44*/
	robot6axis_MoveAbs1ManualCmd = __start.Bool+54; /*robot6axis_ctrled__cn_45*/
	robot6axis_MoveAbs2ManualCmd = __start.Bool+53; /*robot6axis_ctrled__cn_46*/
	robot6axis_StopCmd = robot6axis_ctrled_Auto;
	robot6axis_MovePosition = __start.Float+47; /*robot6axis_ctrled__cn_47*/
	robot6axis_MoveSpeed = __start.Float+46; /*robot6axis_ctrled__cn_48*/
	robot6axis_MoveAcceleration = __start.Float+45; /*robot6axis_ctrled__cn_49*/
	robot6axis_MoveDeceleration = __start.Float+44; /*robot6axis_ctrled__cn_50*/
	robot6axis_offsetAxToMa = __start.Float+43; /*robot6axis_ctrled__cn_51*/
	robot6axis_HomeCmd2 = __start.Bool+52; /*robot6axis_ctrled__cn_52*/
	robot6axis_MoveVelCmd2 = __start.Bool+51; /*robot6axis_ctrled__cn_53*/
	robot6axis_MoveAbsCmd2 = __start.Bool+50; /*robot6axis_ctrled__cn_54*/
	robot6axis_MoveVel1ManualCmd2 = __start.Bool+49; /*robot6axis_ctrled__cn_55*/
	robot6axis_MoveVel2ManualCmd2 = __start.Bool+48; /*robot6axis_ctrled__cn_56*/
	robot6axis_MoveAbs1ManualCmd2 = __start.Bool+47; /*robot6axis_ctrled__cn_57*/
	robot6axis_MoveAbs2ManualCmd2 = __start.Bool+46; /*robot6axis_ctrled__cn_58*/
	robot6axis_StopCmd2 = robot6axis_ctrled_Auto;
	robot6axis_MovePosition2 = __start.Float+42; /*robot6axis_ctrled__cn_59*/
	robot6axis_MoveSpeed2 = __start.Float+41; /*robot6axis_ctrled__cn_60*/
	robot6axis_MoveAcceleration2 = __start.Float+40; /*robot6axis_ctrled__cn_61*/
	robot6axis_MoveDeceleration2 = __start.Float+39; /*robot6axis_ctrled__cn_62*/
	robot6axis_offsetAxToMa2 = __start.Float+38; /*robot6axis_ctrled__cn_63*/
	robot6axis_HomeCmd3 = __start.Bool+45; /*robot6axis_ctrled__cn_64*/
	robot6axis_MoveVelCmd3 = __start.Bool+44; /*robot6axis_ctrled__cn_65*/
	robot6axis_MoveAbsCmd3 = __start.Bool+43; /*robot6axis_ctrled__cn_66*/
	robot6axis_MoveVel1ManualCmd3 = __start.Bool+42; /*robot6axis_ctrled__cn_67*/
	robot6axis_MoveVel2ManualCmd3 = __start.Bool+41; /*robot6axis_ctrled__cn_68*/
	robot6axis_MoveAbs1ManualCmd3 = __start.Bool+40; /*robot6axis_ctrled__cn_69*/
	robot6axis_MoveAbs2ManualCmd3 = __start.Bool+39; /*robot6axis_ctrled__cn_70*/
	robot6axis_StopCmd3 = robot6axis_ctrled_Auto;
	robot6axis_MovePosition3 = __start.Float+37; /*robot6axis_ctrled__cn_71*/
	robot6axis_MoveSpeed3 = __start.Float+36; /*robot6axis_ctrled__cn_72*/
	robot6axis_MoveAcceleration3 = __start.Float+35; /*robot6axis_ctrled__cn_73*/
	robot6axis_MoveDeceleration3 = __start.Float+34; /*robot6axis_ctrled__cn_74*/
	robot6axis_offsetAxToMa3 = __start.Float+33; /*robot6axis_ctrled__cn_75*/
	robot6axis_HomeCmd4 = __start.Bool+38; /*robot6axis_ctrled__cn_76*/
	robot6axis_MoveVelCmd4 = __start.Bool+37; /*robot6axis_ctrled__cn_77*/
	robot6axis_MoveAbsCmd4 = __start.Bool+36; /*robot6axis_ctrled__cn_78*/
	robot6axis_MoveVel1ManualCmd4 = __start.Bool+35; /*robot6axis_ctrled__cn_79*/
	robot6axis_MoveVel2ManualCmd4 = __start.Bool+34; /*robot6axis_ctrled__cn_80*/
	robot6axis_MoveAbs1ManualCmd4 = __start.Bool+33; /*robot6axis_ctrled__cn_81*/
	robot6axis_MoveAbs2ManualCmd4 = __start.Bool+32; /*robot6axis_ctrled__cn_82*/
	robot6axis_StopCmd4 = robot6axis_ctrled_Auto;
	robot6axis_MovePosition4 = __start.Float+32; /*robot6axis_ctrled__cn_83*/
	robot6axis_MoveSpeed4 = __start.Float+31; /*robot6axis_ctrled__cn_84*/
	robot6axis_MoveAcceleration4 = __start.Float+30; /*robot6axis_ctrled__cn_85*/
	robot6axis_MoveDeceleration4 = __start.Float+29; /*robot6axis_ctrled__cn_86*/
	robot6axis_offsetAxToMa4 = __start.Float+28; /*robot6axis_ctrled__cn_87*/
	robot6axis_HomeCmd5 = __start.Bool+31; /*robot6axis_ctrled__cn_88*/
	robot6axis_MoveVelCmd5 = __start.Bool+30; /*robot6axis_ctrled__cn_89*/
	robot6axis_MoveAbsCmd5 = __start.Bool+29; /*robot6axis_ctrled__cn_90*/
	robot6axis_MoveVel1ManualCmd5 = __start.Bool+28; /*robot6axis_ctrled__cn_91*/
	robot6axis_MoveVel2ManualCmd5 = __start.Bool+27; /*robot6axis_ctrled__cn_92*/
	robot6axis_MoveAbs1ManualCmd5 = __start.Bool+26; /*robot6axis_ctrled__cn_93*/
	robot6axis_MoveAbs2ManualCmd5 = __start.Bool+25; /*robot6axis_ctrled__cn_94*/
	robot6axis_StopCmd5 = robot6axis_ctrled_Auto;
	robot6axis_MovePosition5 = __start.Float+27; /*robot6axis_ctrled__cn_95*/
	robot6axis_MoveSpeed5 = __start.Float+26; /*robot6axis_ctrled__cn_96*/
	robot6axis_MoveAcceleration5 = __start.Float+25; /*robot6axis_ctrled__cn_97*/
	robot6axis_MoveDeceleration5 = __start.Float+24; /*robot6axis_ctrled__cn_98*/
	robot6axis_offsetAxToMa5 = __start.Float+23; /*robot6axis_ctrled__cn_99*/
	robot6axis_HomeCmd6 = __start.Bool+24; /*robot6axis_ctrled__cn_100*/
	robot6axis_MoveVelCmd6 = __start.Bool+23; /*robot6axis_ctrled__cn_101*/
	robot6axis_MoveAbsCmd6 = __start.Bool+22; /*robot6axis_ctrled__cn_102*/
	robot6axis_MoveVel1ManualCmd6 = __start.Bool+21; /*robot6axis_ctrled__cn_103*/
	robot6axis_MoveVel2ManualCmd6 = __start.Bool+20; /*robot6axis_ctrled__cn_104*/
	robot6axis_MoveAbs1ManualCmd6 = __start.Bool+19; /*robot6axis_ctrled__cn_105*/
	robot6axis_MoveAbs2ManualCmd6 = __start.Bool+18; /*robot6axis_ctrled__cn_106*/
	robot6axis_StopCmd6 = robot6axis_ctrled_Auto;
	robot6axis_MovePosition6 = __start.Float+22; /*robot6axis_ctrled__cn_107*/
	robot6axis_MoveSpeed6 = __start.Float+21; /*robot6axis_ctrled__cn_108*/
	robot6axis_MoveAcceleration6 = __start.Float+20; /*robot6axis_ctrled__cn_109*/
	robot6axis_MoveDeceleration6 = __start.Float+19; /*robot6axis_ctrled__cn_110*/
	robot6axis_offsetAxToMa6 = __start.Float+18; /*robot6axis_ctrled__cn_111*/
	robot6axis_PLC_StatusReady = __start.Bool+17; /*robot6axis_ctrled__cn_112*/
	robot6axis_PLC_StatusMoved = __start.Bool+16; /*robot6axis_ctrled__cn_113*/
	robot6axis_PLC_StatusStand = __start.Bool+15; /*robot6axis_ctrled__cn_114*/
	robot6axis_PLC_ActualPositionAx = __start.Float+121; /*robot6axis_ctrled__cn_6*/
	robot6axis_PLC_ActualPositionMa = __start.Float+17; /*robot6axis_ctrled__cn_115*/
	robot6axis_PLC_ActualVelocity = __start.Float+16; /*robot6axis_ctrled__cn_116*/
	robot6axis_PLC_StatusReady2 = __start.Bool+14; /*robot6axis_ctrled__cn_117*/
	robot6axis_PLC_StatusMoved2 = __start.Bool+13; /*robot6axis_ctrled__cn_118*/
	robot6axis_PLC_StatusStand2 = __start.Bool+12; /*robot6axis_ctrled__cn_119*/
	robot6axis_PLC_ActualPositionAx2 = __start.Float+122; /*robot6axis_ctrled__cn_5*/
	robot6axis_PLC_ActualPositionMa2 = __start.Float+15; /*robot6axis_ctrled__cn_120*/
	robot6axis_PLC_ActualVelocity2 = __start.Float+14; /*robot6axis_ctrled__cn_121*/
	robot6axis_PLC_StatusReady3 = __start.Bool+11; /*robot6axis_ctrled__cn_122*/
	robot6axis_PLC_StatusMoved3 = __start.Bool+10; /*robot6axis_ctrled__cn_123*/
	robot6axis_PLC_StatusStand3 = __start.Bool+9; /*robot6axis_ctrled__cn_124*/
	robot6axis_PLC_ActualPositionAx3 = __start.Float+123; /*robot6axis_ctrled__cn_4*/
	robot6axis_PLC_ActualPositionMa3 = __start.Float+13; /*robot6axis_ctrled__cn_125*/
	robot6axis_PLC_ActualVelocity3 = __start.Float+12; /*robot6axis_ctrled__cn_126*/
	robot6axis_PLC_StatusReady4 = __start.Bool+8; /*robot6axis_ctrled__cn_127*/
	robot6axis_PLC_StatusMoved4 = __start.Bool+7; /*robot6axis_ctrled__cn_128*/
	robot6axis_PLC_StatusStand4 = __start.Bool+6; /*robot6axis_ctrled__cn_129*/
	robot6axis_PLC_ActualPositionAx4 = __start.Float+124; /*robot6axis_ctrled__cn_3*/
	robot6axis_PLC_ActualPositionMa4 = __start.Float+11; /*robot6axis_ctrled__cn_130*/
	robot6axis_PLC_ActualVelocity4 = __start.Float+10; /*robot6axis_ctrled__cn_131*/
	robot6axis_PLC_StatusReady5 = __start.Bool+5; /*robot6axis_ctrled__cn_132*/
	robot6axis_PLC_StatusMoved5 = __start.Bool+4; /*robot6axis_ctrled__cn_133*/
	robot6axis_PLC_StatusStand5 = __start.Bool+3; /*robot6axis_ctrled__cn_134*/
	robot6axis_PLC_ActualPositionAx5 = __start.Float+125; /*robot6axis_ctrled__cn_2*/
	robot6axis_PLC_ActualPositionMa5 = __start.Float+9; /*robot6axis_ctrled__cn_135*/
	robot6axis_PLC_ActualVelocity5 = __start.Float+8; /*robot6axis_ctrled__cn_136*/
	robot6axis_PLC_StatusReady6 = __start.Bool+2; /*robot6axis_ctrled__cn_137*/
	robot6axis_PLC_StatusMoved6 = __start.Bool+1; /*robot6axis_ctrled__cn_138*/
	robot6axis_PLC_StatusStand6 = __start.Bool+0; /*robot6axis_ctrled__cn_139*/
	robot6axis_PLC_ActualPositionAx6 = __start.Float+126; /*robot6axis_ctrled__cn_1*/
	robot6axis_PLC_ActualPositionMa6 = __start.Float+7; /*robot6axis_ctrled__cn_140*/
	robot6axis_PLC_ActualVelocity6 = __start.Float+6; /*robot6axis_ctrled__cn_141*/
	robot6axis_gripSyringes = robot6axis_ctrled_gripSyringes;
	robot6axis_ActualVelocity1 = __start.Float+5; /*robot6axis_ctrled__cn_142*/
	robot6axis_ActualVelocity2 = __start.Float+4; /*robot6axis_ctrled__cn_143*/
	robot6axis_ActualVelocity3 = __start.Float+3; /*robot6axis_ctrled__cn_144*/
	robot6axis_ActualVelocity4 = __start.Float+2; /*robot6axis_ctrled__cn_145*/
	robot6axis_ActualVelocity5 = __start.Float+1; /*robot6axis_ctrled__cn_146*/
	robot6axis_ActualVelocity6 = __start.Float+0; /*robot6axis_ctrled__cn_147*/
	robot6axis_armExtrem = robot6axis_ctrled_armExtrem;
	robot6axis_velX = robot6axis_ctrled_velX;
	robot6axis_velY = robot6axis_ctrled_velY;
	robot6axis_velZ = robot6axis_ctrled_velZ;
	robot6axis_armInStop = robot6axis_ctrled_armInStop;
	_motion_lib__robot6axis_init();

	robot6axis_ctrled__robot6axis_ctrled_offset__end.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_ctrled_offset__end.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_ctrled_offset__end.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_ctrled_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int robot6axis_ctrled__robot6axis_ctrled(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																																																																																																																																																																																																																																																																																						
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Bool;
			self.Int = __start.Int + robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Int;
			self.Float = __start.Float + robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Float;
			self.Char = __start.Char + robot6axis_ctrled__robot6axis_ctrled_offset_robot6axis_cams.Char;

			/******************** robot6axis_cams execution *********************/

			self_num++;
			if (robot6axis_cams__num != self_num) {
				robot6axis_cams__num = self_num;
				robot6axis_cams_profileNr = robot6axis_ctrled_profileNr;
				robot6axis_cams_HomeCmd = robot6axis_ctrled_HomeCmd;
				robot6axis_cams_MoveVelCmd = robot6axis_ctrled_MoveVelCmd;
				robot6axis_cams_MoveAbsCmd = robot6axis_ctrled_MoveAbsCmd;
				robot6axis_cams_MoveVel1ManualCmd = robot6axis_ctrled_MoveVel1ManualCmd;
				robot6axis_cams_MoveVel2ManualCmd = robot6axis_ctrled_MoveVel2ManualCmd;
				robot6axis_cams_MoveAbs1ManualCmd = robot6axis_ctrled_MoveAbs1ManualCmd;
				robot6axis_cams_MoveAbs2ManualCmd = robot6axis_ctrled_MoveAbs2ManualCmd;
				robot6axis_cams_StopCmd = robot6axis_ctrled_StopCmd;
				robot6axis_cams_MovePosition = robot6axis_ctrled_MovePosition;
				robot6axis_cams_MoveSpeed = robot6axis_ctrled_MoveSpeed;
				robot6axis_cams_MoveAcceleration = robot6axis_ctrled_MoveAcceleration;
				robot6axis_cams_MoveDeceleration = robot6axis_ctrled_MoveDeceleration;
				robot6axis_cams_offsetAxToMa = robot6axis_ctrled_offsetAxToMa;
				robot6axis_cams_name1 = __start.Char+583; /*robot6axis_ctrled__cn_7*/
				robot6axis_cams_name2 = __start.Char+530; /*robot6axis_ctrled__cn_8*/
				robot6axis_cams_name3 = __start.Char+477; /*robot6axis_ctrled__cn_9*/
				robot6axis_cams_name4 = __start.Char+424; /*robot6axis_ctrled__cn_10*/
				robot6axis_cams_name5 = __start.Char+371; /*robot6axis_ctrled__cn_11*/
				robot6axis_cams_name6 = __start.Char+318; /*robot6axis_ctrled__cn_12*/
				robot6axis_cams_name1_rej = __start.Char+265; /*robot6axis_ctrled__cn_13*/
				robot6axis_cams_name2_rej = __start.Char+212; /*robot6axis_ctrled__cn_14*/
				robot6axis_cams_name3_rej = __start.Char+159; /*robot6axis_ctrled__cn_15*/
				robot6axis_cams_name4_rej = __start.Char+106; /*robot6axis_ctrled__cn_16*/
				robot6axis_cams_name5_rej = __start.Char+53; /*robot6axis_ctrled__cn_17*/
				robot6axis_cams_name6_rej = __start.Char+0; /*robot6axis_ctrled__cn_18*/
				robot6axis_cams_slavePosition1 = __start.Float+121; /*robot6axis_ctrled__cn_6*/
				robot6axis_cams_slavePosition2 = __start.Float+122; /*robot6axis_ctrled__cn_5*/
				robot6axis_cams_slavePosition3 = __start.Float+123; /*robot6axis_ctrled__cn_4*/
				robot6axis_cams_slavePosition4 = __start.Float+124; /*robot6axis_ctrled__cn_3*/
				robot6axis_cams_slavePosition5 = __start.Float+125; /*robot6axis_ctrled__cn_2*/
				robot6axis_cams_slavePosition6 = __start.Float+126; /*robot6axis_ctrled__cn_1*/
				robot6axis_cams_ActualPositionAx = robot6axis_ctrled_ActualPositionAx;
				robot6axis_cams_masterPosition = robot6axis_ctrled_masterPosition;
			}
			__ret = robot6axis_ctrled__robot6axis_cams();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** robot6axis execution ***********************/

			self_num++;
			if (robot6axis__num != self_num) {
				robot6axis__num = self_num;
				robot6axis_armOrigin = robot6axis_ctrled_armOrigin;
				robot6axis_structRotVectorFOOT = __start.Float+116; /*robot6axis_ctrled__cn_19*/
				robot6axis_structRotDegFOOT = __start.Float+115; /*robot6axis_ctrled__cn_20*/
				robot6axis_ownRotDegFOOT = __start.Float+114; /*robot6axis_ctrled__cn_21*/
				robot6axis_structRotVectorFOOT2 = __start.Float+109; /*robot6axis_ctrled__cn_22*/
				robot6axis_structRotDegFOOT2 = __start.Float+108; /*robot6axis_ctrled__cn_23*/
				robot6axis_structRotVectorArm2 = __start.Float+103; /*robot6axis_ctrled__cn_24*/
				robot6axis_structRotDegArm2 = __start.Float+102; /*robot6axis_ctrled__cn_25*/
				robot6axis_driveRotVector1 = __start.Float+97; /*robot6axis_ctrled__cn_26*/
				robot6axis_driveRotVector2 = __start.Float+92; /*robot6axis_ctrled__cn_27*/
				robot6axis_driveRotVector3 = __start.Float+87; /*robot6axis_ctrled__cn_28*/
				robot6axis_driveRotVector4 = __start.Float+82; /*robot6axis_ctrled__cn_29*/
				robot6axis_driveRotVector5 = __start.Float+77; /*robot6axis_ctrled__cn_30*/
				robot6axis_driveRotVector6 = __start.Float+72; /*robot6axis_ctrled__cn_31*/
				robot6axis_structRotVector1RowA = __start.Float+67; /*robot6axis_ctrled__cn_32*/
				robot6axis_structRotDeg1RowA = __start.Float+66; /*robot6axis_ctrled__cn_33*/
				robot6axis_structRotVector1RowB = __start.Float+61; /*robot6axis_ctrled__cn_34*/
				robot6axis_structRotDeg1RowB = __start.Float+60; /*robot6axis_ctrled__cn_35*/
				robot6axis_structRotVectorMultiRowsA = __start.Float+55; /*robot6axis_ctrled__cn_36*/
				robot6axis_structRotDegMultiRowsA = __start.Float+54; /*robot6axis_ctrled__cn_37*/
				robot6axis_structRotVectorMultiRowsB = __start.Float+49; /*robot6axis_ctrled__cn_38*/
				robot6axis_structRotDegMultiRowsB = __start.Float+48; /*robot6axis_ctrled__cn_39*/
				robot6axis_HomeCmd = __start.Bool+59; /*robot6axis_ctrled__cn_40*/
				robot6axis_MoveVelCmd = __start.Bool+58; /*robot6axis_ctrled__cn_41*/
				robot6axis_MoveAbsCmd = __start.Bool+57; /*robot6axis_ctrled__cn_42*/
				robot6axis_MoveVel1ManualCmd = __start.Bool+56; /*robot6axis_ctrled__cn_43*/
				robot6axis_MoveVel2ManualCmd = __start.Bool+55; /*robot6axis_ctrled__cn_44*/
				robot6axis_MoveAbs1ManualCmd = __start.Bool+54; /*robot6axis_ctrled__cn_45*/
				robot6axis_MoveAbs2ManualCmd = __start.Bool+53; /*robot6axis_ctrled__cn_46*/
				robot6axis_StopCmd = robot6axis_ctrled_Auto;
				robot6axis_MovePosition = __start.Float+47; /*robot6axis_ctrled__cn_47*/
				robot6axis_MoveSpeed = __start.Float+46; /*robot6axis_ctrled__cn_48*/
				robot6axis_MoveAcceleration = __start.Float+45; /*robot6axis_ctrled__cn_49*/
				robot6axis_MoveDeceleration = __start.Float+44; /*robot6axis_ctrled__cn_50*/
				robot6axis_offsetAxToMa = __start.Float+43; /*robot6axis_ctrled__cn_51*/
				robot6axis_HomeCmd2 = __start.Bool+52; /*robot6axis_ctrled__cn_52*/
				robot6axis_MoveVelCmd2 = __start.Bool+51; /*robot6axis_ctrled__cn_53*/
				robot6axis_MoveAbsCmd2 = __start.Bool+50; /*robot6axis_ctrled__cn_54*/
				robot6axis_MoveVel1ManualCmd2 = __start.Bool+49; /*robot6axis_ctrled__cn_55*/
				robot6axis_MoveVel2ManualCmd2 = __start.Bool+48; /*robot6axis_ctrled__cn_56*/
				robot6axis_MoveAbs1ManualCmd2 = __start.Bool+47; /*robot6axis_ctrled__cn_57*/
				robot6axis_MoveAbs2ManualCmd2 = __start.Bool+46; /*robot6axis_ctrled__cn_58*/
				robot6axis_StopCmd2 = robot6axis_ctrled_Auto;
				robot6axis_MovePosition2 = __start.Float+42; /*robot6axis_ctrled__cn_59*/
				robot6axis_MoveSpeed2 = __start.Float+41; /*robot6axis_ctrled__cn_60*/
				robot6axis_MoveAcceleration2 = __start.Float+40; /*robot6axis_ctrled__cn_61*/
				robot6axis_MoveDeceleration2 = __start.Float+39; /*robot6axis_ctrled__cn_62*/
				robot6axis_offsetAxToMa2 = __start.Float+38; /*robot6axis_ctrled__cn_63*/
				robot6axis_HomeCmd3 = __start.Bool+45; /*robot6axis_ctrled__cn_64*/
				robot6axis_MoveVelCmd3 = __start.Bool+44; /*robot6axis_ctrled__cn_65*/
				robot6axis_MoveAbsCmd3 = __start.Bool+43; /*robot6axis_ctrled__cn_66*/
				robot6axis_MoveVel1ManualCmd3 = __start.Bool+42; /*robot6axis_ctrled__cn_67*/
				robot6axis_MoveVel2ManualCmd3 = __start.Bool+41; /*robot6axis_ctrled__cn_68*/
				robot6axis_MoveAbs1ManualCmd3 = __start.Bool+40; /*robot6axis_ctrled__cn_69*/
				robot6axis_MoveAbs2ManualCmd3 = __start.Bool+39; /*robot6axis_ctrled__cn_70*/
				robot6axis_StopCmd3 = robot6axis_ctrled_Auto;
				robot6axis_MovePosition3 = __start.Float+37; /*robot6axis_ctrled__cn_71*/
				robot6axis_MoveSpeed3 = __start.Float+36; /*robot6axis_ctrled__cn_72*/
				robot6axis_MoveAcceleration3 = __start.Float+35; /*robot6axis_ctrled__cn_73*/
				robot6axis_MoveDeceleration3 = __start.Float+34; /*robot6axis_ctrled__cn_74*/
				robot6axis_offsetAxToMa3 = __start.Float+33; /*robot6axis_ctrled__cn_75*/
				robot6axis_HomeCmd4 = __start.Bool+38; /*robot6axis_ctrled__cn_76*/
				robot6axis_MoveVelCmd4 = __start.Bool+37; /*robot6axis_ctrled__cn_77*/
				robot6axis_MoveAbsCmd4 = __start.Bool+36; /*robot6axis_ctrled__cn_78*/
				robot6axis_MoveVel1ManualCmd4 = __start.Bool+35; /*robot6axis_ctrled__cn_79*/
				robot6axis_MoveVel2ManualCmd4 = __start.Bool+34; /*robot6axis_ctrled__cn_80*/
				robot6axis_MoveAbs1ManualCmd4 = __start.Bool+33; /*robot6axis_ctrled__cn_81*/
				robot6axis_MoveAbs2ManualCmd4 = __start.Bool+32; /*robot6axis_ctrled__cn_82*/
				robot6axis_StopCmd4 = robot6axis_ctrled_Auto;
				robot6axis_MovePosition4 = __start.Float+32; /*robot6axis_ctrled__cn_83*/
				robot6axis_MoveSpeed4 = __start.Float+31; /*robot6axis_ctrled__cn_84*/
				robot6axis_MoveAcceleration4 = __start.Float+30; /*robot6axis_ctrled__cn_85*/
				robot6axis_MoveDeceleration4 = __start.Float+29; /*robot6axis_ctrled__cn_86*/
				robot6axis_offsetAxToMa4 = __start.Float+28; /*robot6axis_ctrled__cn_87*/
				robot6axis_HomeCmd5 = __start.Bool+31; /*robot6axis_ctrled__cn_88*/
				robot6axis_MoveVelCmd5 = __start.Bool+30; /*robot6axis_ctrled__cn_89*/
				robot6axis_MoveAbsCmd5 = __start.Bool+29; /*robot6axis_ctrled__cn_90*/
				robot6axis_MoveVel1ManualCmd5 = __start.Bool+28; /*robot6axis_ctrled__cn_91*/
				robot6axis_MoveVel2ManualCmd5 = __start.Bool+27; /*robot6axis_ctrled__cn_92*/
				robot6axis_MoveAbs1ManualCmd5 = __start.Bool+26; /*robot6axis_ctrled__cn_93*/
				robot6axis_MoveAbs2ManualCmd5 = __start.Bool+25; /*robot6axis_ctrled__cn_94*/
				robot6axis_StopCmd5 = robot6axis_ctrled_Auto;
				robot6axis_MovePosition5 = __start.Float+27; /*robot6axis_ctrled__cn_95*/
				robot6axis_MoveSpeed5 = __start.Float+26; /*robot6axis_ctrled__cn_96*/
				robot6axis_MoveAcceleration5 = __start.Float+25; /*robot6axis_ctrled__cn_97*/
				robot6axis_MoveDeceleration5 = __start.Float+24; /*robot6axis_ctrled__cn_98*/
				robot6axis_offsetAxToMa5 = __start.Float+23; /*robot6axis_ctrled__cn_99*/
				robot6axis_HomeCmd6 = __start.Bool+24; /*robot6axis_ctrled__cn_100*/
				robot6axis_MoveVelCmd6 = __start.Bool+23; /*robot6axis_ctrled__cn_101*/
				robot6axis_MoveAbsCmd6 = __start.Bool+22; /*robot6axis_ctrled__cn_102*/
				robot6axis_MoveVel1ManualCmd6 = __start.Bool+21; /*robot6axis_ctrled__cn_103*/
				robot6axis_MoveVel2ManualCmd6 = __start.Bool+20; /*robot6axis_ctrled__cn_104*/
				robot6axis_MoveAbs1ManualCmd6 = __start.Bool+19; /*robot6axis_ctrled__cn_105*/
				robot6axis_MoveAbs2ManualCmd6 = __start.Bool+18; /*robot6axis_ctrled__cn_106*/
				robot6axis_StopCmd6 = robot6axis_ctrled_Auto;
				robot6axis_MovePosition6 = __start.Float+22; /*robot6axis_ctrled__cn_107*/
				robot6axis_MoveSpeed6 = __start.Float+21; /*robot6axis_ctrled__cn_108*/
				robot6axis_MoveAcceleration6 = __start.Float+20; /*robot6axis_ctrled__cn_109*/
				robot6axis_MoveDeceleration6 = __start.Float+19; /*robot6axis_ctrled__cn_110*/
				robot6axis_offsetAxToMa6 = __start.Float+18; /*robot6axis_ctrled__cn_111*/
				robot6axis_PLC_StatusReady = __start.Bool+17; /*robot6axis_ctrled__cn_112*/
				robot6axis_PLC_StatusMoved = __start.Bool+16; /*robot6axis_ctrled__cn_113*/
				robot6axis_PLC_StatusStand = __start.Bool+15; /*robot6axis_ctrled__cn_114*/
				robot6axis_PLC_ActualPositionAx = __start.Float+121; /*robot6axis_ctrled__cn_6*/
				robot6axis_PLC_ActualPositionMa = __start.Float+17; /*robot6axis_ctrled__cn_115*/
				robot6axis_PLC_ActualVelocity = __start.Float+16; /*robot6axis_ctrled__cn_116*/
				robot6axis_PLC_StatusReady2 = __start.Bool+14; /*robot6axis_ctrled__cn_117*/
				robot6axis_PLC_StatusMoved2 = __start.Bool+13; /*robot6axis_ctrled__cn_118*/
				robot6axis_PLC_StatusStand2 = __start.Bool+12; /*robot6axis_ctrled__cn_119*/
				robot6axis_PLC_ActualPositionAx2 = __start.Float+122; /*robot6axis_ctrled__cn_5*/
				robot6axis_PLC_ActualPositionMa2 = __start.Float+15; /*robot6axis_ctrled__cn_120*/
				robot6axis_PLC_ActualVelocity2 = __start.Float+14; /*robot6axis_ctrled__cn_121*/
				robot6axis_PLC_StatusReady3 = __start.Bool+11; /*robot6axis_ctrled__cn_122*/
				robot6axis_PLC_StatusMoved3 = __start.Bool+10; /*robot6axis_ctrled__cn_123*/
				robot6axis_PLC_StatusStand3 = __start.Bool+9; /*robot6axis_ctrled__cn_124*/
				robot6axis_PLC_ActualPositionAx3 = __start.Float+123; /*robot6axis_ctrled__cn_4*/
				robot6axis_PLC_ActualPositionMa3 = __start.Float+13; /*robot6axis_ctrled__cn_125*/
				robot6axis_PLC_ActualVelocity3 = __start.Float+12; /*robot6axis_ctrled__cn_126*/
				robot6axis_PLC_StatusReady4 = __start.Bool+8; /*robot6axis_ctrled__cn_127*/
				robot6axis_PLC_StatusMoved4 = __start.Bool+7; /*robot6axis_ctrled__cn_128*/
				robot6axis_PLC_StatusStand4 = __start.Bool+6; /*robot6axis_ctrled__cn_129*/
				robot6axis_PLC_ActualPositionAx4 = __start.Float+124; /*robot6axis_ctrled__cn_3*/
				robot6axis_PLC_ActualPositionMa4 = __start.Float+11; /*robot6axis_ctrled__cn_130*/
				robot6axis_PLC_ActualVelocity4 = __start.Float+10; /*robot6axis_ctrled__cn_131*/
				robot6axis_PLC_StatusReady5 = __start.Bool+5; /*robot6axis_ctrled__cn_132*/
				robot6axis_PLC_StatusMoved5 = __start.Bool+4; /*robot6axis_ctrled__cn_133*/
				robot6axis_PLC_StatusStand5 = __start.Bool+3; /*robot6axis_ctrled__cn_134*/
				robot6axis_PLC_ActualPositionAx5 = __start.Float+125; /*robot6axis_ctrled__cn_2*/
				robot6axis_PLC_ActualPositionMa5 = __start.Float+9; /*robot6axis_ctrled__cn_135*/
				robot6axis_PLC_ActualVelocity5 = __start.Float+8; /*robot6axis_ctrled__cn_136*/
				robot6axis_PLC_StatusReady6 = __start.Bool+2; /*robot6axis_ctrled__cn_137*/
				robot6axis_PLC_StatusMoved6 = __start.Bool+1; /*robot6axis_ctrled__cn_138*/
				robot6axis_PLC_StatusStand6 = __start.Bool+0; /*robot6axis_ctrled__cn_139*/
				robot6axis_PLC_ActualPositionAx6 = __start.Float+126; /*robot6axis_ctrled__cn_1*/
				robot6axis_PLC_ActualPositionMa6 = __start.Float+7; /*robot6axis_ctrled__cn_140*/
				robot6axis_PLC_ActualVelocity6 = __start.Float+6; /*robot6axis_ctrled__cn_141*/
				robot6axis_gripSyringes = robot6axis_ctrled_gripSyringes;
				robot6axis_ActualVelocity1 = __start.Float+5; /*robot6axis_ctrled__cn_142*/
				robot6axis_ActualVelocity2 = __start.Float+4; /*robot6axis_ctrled__cn_143*/
				robot6axis_ActualVelocity3 = __start.Float+3; /*robot6axis_ctrled__cn_144*/
				robot6axis_ActualVelocity4 = __start.Float+2; /*robot6axis_ctrled__cn_145*/
				robot6axis_ActualVelocity5 = __start.Float+1; /*robot6axis_ctrled__cn_146*/
				robot6axis_ActualVelocity6 = __start.Float+0; /*robot6axis_ctrled__cn_147*/
				robot6axis_armExtrem = robot6axis_ctrled_armExtrem;
				robot6axis_velX = robot6axis_ctrled_velX;
				robot6axis_velY = robot6axis_ctrled_velY;
				robot6axis_velZ = robot6axis_ctrled_velZ;
				robot6axis_armInStop = robot6axis_ctrled_armInStop;
			}
			__ret = motion_lib__robot6axis();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + robot6axis_ctrled__robot6axis_ctrled_offset__end.Bool;
	self.Int = __start.Int + robot6axis_ctrled__robot6axis_ctrled_offset__end.Int;
	self.Float = __start.Float + robot6axis_ctrled__robot6axis_ctrled_offset__end.Float;
	self.Char = __start.Char + robot6axis_ctrled__robot6axis_ctrled_offset__end.Char;

	return 0;
}

