/*2023-10-04T11:04:00-01:00*/

/********************************************************************
 * robot6axis_cams.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "robot6axis_cams.h"
#include "motion_control/functional/servo/servo.h"
#include "motion_lib/functional/cam_profile/cam_profile.h"
#include "motion_lib/functional/cam_computation/cam_computation.h"


/**************************** Variables *****************************/

CB_Index robot6axis_cams__num = 0;
CB_Mem_Int *robot6axis_cams_profileNr;
CB_Mem_Bool *robot6axis_cams_HomeCmd;
CB_Mem_Bool *robot6axis_cams_MoveVelCmd;
CB_Mem_Bool *robot6axis_cams_MoveAbsCmd;
CB_Mem_Bool *robot6axis_cams_MoveVel1ManualCmd;
CB_Mem_Bool *robot6axis_cams_MoveVel2ManualCmd;
CB_Mem_Bool *robot6axis_cams_MoveAbs1ManualCmd;
CB_Mem_Bool *robot6axis_cams_MoveAbs2ManualCmd;
CB_Mem_Bool *robot6axis_cams_StopCmd;
CB_Mem_Float *robot6axis_cams_MovePosition;
CB_Mem_Float *robot6axis_cams_MoveSpeed;
CB_Mem_Float *robot6axis_cams_MoveAcceleration;
CB_Mem_Float *robot6axis_cams_MoveDeceleration;
CB_Mem_Float *robot6axis_cams_offsetAxToMa;
CB_Mem_Char *robot6axis_cams_name1;
CB_Mem_Char *robot6axis_cams_name2;
CB_Mem_Char *robot6axis_cams_name3;
CB_Mem_Char *robot6axis_cams_name4;
CB_Mem_Char *robot6axis_cams_name5;
CB_Mem_Char *robot6axis_cams_name6;
CB_Mem_Char *robot6axis_cams_name1_rej;
CB_Mem_Char *robot6axis_cams_name2_rej;
CB_Mem_Char *robot6axis_cams_name3_rej;
CB_Mem_Char *robot6axis_cams_name4_rej;
CB_Mem_Char *robot6axis_cams_name5_rej;
CB_Mem_Char *robot6axis_cams_name6_rej;
CB_Mem_Float *robot6axis_cams_slavePosition1;
CB_Mem_Float *robot6axis_cams_slavePosition2;
CB_Mem_Float *robot6axis_cams_slavePosition3;
CB_Mem_Float *robot6axis_cams_slavePosition4;
CB_Mem_Float *robot6axis_cams_slavePosition5;
CB_Mem_Float *robot6axis_cams_slavePosition6;
CB_Mem_Float *robot6axis_cams_ActualPositionAx;
CB_Mem_Float *robot6axis_cams_masterPosition;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile1;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile7;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation1;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile2;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile8;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation2;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile3;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile9;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation3;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile4;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile10;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation4;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile5;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile11;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation5;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile6;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_profile12;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset_cam_computation6;
static CB_Offset robot6axis_ctrled__robot6axis_cams_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _robot6axis_ctrled__robot6axis_cams_init(void)
{
	CB_Object __start = self;
	(robot6axis_cams_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(robot6axis_cams_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(robot6axis_cams_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	(robot6axis_cams_name1+0)->CB_current_value = 0; /*name1 size1*/
	(robot6axis_cams_name1+1)->CB_current_value = 50; /*name1 size2*/
	(robot6axis_cams_name1+3)->CB_current_value = 'C'; /*name1[1]*/
	(robot6axis_cams_name1+4)->CB_current_value = 'a'; /*name1[2]*/
	(robot6axis_cams_name1+5)->CB_current_value = 'm'; /*name1[3]*/
	(robot6axis_cams_name1+6)->CB_current_value = 'A'; /*name1[4]*/
	(robot6axis_cams_name1+7)->CB_current_value = 'x'; /*name1[5]*/
	(robot6axis_cams_name1+8)->CB_current_value = 'i'; /*name1[6]*/
	(robot6axis_cams_name1+9)->CB_current_value = 's'; /*name1[7]*/
	(robot6axis_cams_name1+10)->CB_current_value = '1'; /*name1[8]*/
	(robot6axis_cams_name1+11)->CB_current_value = '_'; /*name1[9]*/
	(robot6axis_cams_name1+12)->CB_current_value = '1'; /*name1[10]*/
	(robot6axis_cams_name1+13)->CB_current_value = '0'; /*name1[11]*/
	(robot6axis_cams_name1+14)->CB_current_value = '0'; /*name1[12]*/
	(robot6axis_cams_name1+15)->CB_current_value = '.'; /*name1[13]*/
	(robot6axis_cams_name1+16)->CB_current_value = 't'; /*name1[14]*/
	(robot6axis_cams_name1+17)->CB_current_value = 'x'; /*name1[15]*/
	(robot6axis_cams_name1+18)->CB_current_value = 't'; /*name1[16]*/
	(robot6axis_cams_name2+0)->CB_current_value = 0; /*name2 size1*/
	(robot6axis_cams_name2+1)->CB_current_value = 50; /*name2 size2*/
	(robot6axis_cams_name2+3)->CB_current_value = 'C'; /*name2[1]*/
	(robot6axis_cams_name2+4)->CB_current_value = 'a'; /*name2[2]*/
	(robot6axis_cams_name2+5)->CB_current_value = 'm'; /*name2[3]*/
	(robot6axis_cams_name2+6)->CB_current_value = 'A'; /*name2[4]*/
	(robot6axis_cams_name2+7)->CB_current_value = 'x'; /*name2[5]*/
	(robot6axis_cams_name2+8)->CB_current_value = 'i'; /*name2[6]*/
	(robot6axis_cams_name2+9)->CB_current_value = 's'; /*name2[7]*/
	(robot6axis_cams_name2+10)->CB_current_value = '2'; /*name2[8]*/
	(robot6axis_cams_name2+11)->CB_current_value = '_'; /*name2[9]*/
	(robot6axis_cams_name2+12)->CB_current_value = '1'; /*name2[10]*/
	(robot6axis_cams_name2+13)->CB_current_value = '0'; /*name2[11]*/
	(robot6axis_cams_name2+14)->CB_current_value = '0'; /*name2[12]*/
	(robot6axis_cams_name2+15)->CB_current_value = '.'; /*name2[13]*/
	(robot6axis_cams_name2+16)->CB_current_value = 't'; /*name2[14]*/
	(robot6axis_cams_name2+17)->CB_current_value = 'x'; /*name2[15]*/
	(robot6axis_cams_name2+18)->CB_current_value = 't'; /*name2[16]*/
	(robot6axis_cams_name3+0)->CB_current_value = 0; /*name3 size1*/
	(robot6axis_cams_name3+1)->CB_current_value = 50; /*name3 size2*/
	(robot6axis_cams_name3+3)->CB_current_value = 'C'; /*name3[1]*/
	(robot6axis_cams_name3+4)->CB_current_value = 'a'; /*name3[2]*/
	(robot6axis_cams_name3+5)->CB_current_value = 'm'; /*name3[3]*/
	(robot6axis_cams_name3+6)->CB_current_value = 'A'; /*name3[4]*/
	(robot6axis_cams_name3+7)->CB_current_value = 'x'; /*name3[5]*/
	(robot6axis_cams_name3+8)->CB_current_value = 'i'; /*name3[6]*/
	(robot6axis_cams_name3+9)->CB_current_value = 's'; /*name3[7]*/
	(robot6axis_cams_name3+10)->CB_current_value = '3'; /*name3[8]*/
	(robot6axis_cams_name3+11)->CB_current_value = '_'; /*name3[9]*/
	(robot6axis_cams_name3+12)->CB_current_value = '1'; /*name3[10]*/
	(robot6axis_cams_name3+13)->CB_current_value = '0'; /*name3[11]*/
	(robot6axis_cams_name3+14)->CB_current_value = '0'; /*name3[12]*/
	(robot6axis_cams_name3+15)->CB_current_value = '.'; /*name3[13]*/
	(robot6axis_cams_name3+16)->CB_current_value = 't'; /*name3[14]*/
	(robot6axis_cams_name3+17)->CB_current_value = 'x'; /*name3[15]*/
	(robot6axis_cams_name3+18)->CB_current_value = 't'; /*name3[16]*/
	(robot6axis_cams_name4+0)->CB_current_value = 0; /*name4 size1*/
	(robot6axis_cams_name4+1)->CB_current_value = 50; /*name4 size2*/
	(robot6axis_cams_name4+3)->CB_current_value = 'C'; /*name4[1]*/
	(robot6axis_cams_name4+4)->CB_current_value = 'a'; /*name4[2]*/
	(robot6axis_cams_name4+5)->CB_current_value = 'm'; /*name4[3]*/
	(robot6axis_cams_name4+6)->CB_current_value = 'A'; /*name4[4]*/
	(robot6axis_cams_name4+7)->CB_current_value = 'x'; /*name4[5]*/
	(robot6axis_cams_name4+8)->CB_current_value = 'i'; /*name4[6]*/
	(robot6axis_cams_name4+9)->CB_current_value = 's'; /*name4[7]*/
	(robot6axis_cams_name4+10)->CB_current_value = '4'; /*name4[8]*/
	(robot6axis_cams_name4+11)->CB_current_value = '_'; /*name4[9]*/
	(robot6axis_cams_name4+12)->CB_current_value = '1'; /*name4[10]*/
	(robot6axis_cams_name4+13)->CB_current_value = '0'; /*name4[11]*/
	(robot6axis_cams_name4+14)->CB_current_value = '0'; /*name4[12]*/
	(robot6axis_cams_name4+15)->CB_current_value = '.'; /*name4[13]*/
	(robot6axis_cams_name4+16)->CB_current_value = 't'; /*name4[14]*/
	(robot6axis_cams_name4+17)->CB_current_value = 'x'; /*name4[15]*/
	(robot6axis_cams_name4+18)->CB_current_value = 't'; /*name4[16]*/
	(robot6axis_cams_name5+0)->CB_current_value = 0; /*name5 size1*/
	(robot6axis_cams_name5+1)->CB_current_value = 50; /*name5 size2*/
	(robot6axis_cams_name5+3)->CB_current_value = 'C'; /*name5[1]*/
	(robot6axis_cams_name5+4)->CB_current_value = 'a'; /*name5[2]*/
	(robot6axis_cams_name5+5)->CB_current_value = 'm'; /*name5[3]*/
	(robot6axis_cams_name5+6)->CB_current_value = 'A'; /*name5[4]*/
	(robot6axis_cams_name5+7)->CB_current_value = 'x'; /*name5[5]*/
	(robot6axis_cams_name5+8)->CB_current_value = 'i'; /*name5[6]*/
	(robot6axis_cams_name5+9)->CB_current_value = 's'; /*name5[7]*/
	(robot6axis_cams_name5+10)->CB_current_value = '5'; /*name5[8]*/
	(robot6axis_cams_name5+11)->CB_current_value = '_'; /*name5[9]*/
	(robot6axis_cams_name5+12)->CB_current_value = '1'; /*name5[10]*/
	(robot6axis_cams_name5+13)->CB_current_value = '0'; /*name5[11]*/
	(robot6axis_cams_name5+14)->CB_current_value = '0'; /*name5[12]*/
	(robot6axis_cams_name5+15)->CB_current_value = '.'; /*name5[13]*/
	(robot6axis_cams_name5+16)->CB_current_value = 't'; /*name5[14]*/
	(robot6axis_cams_name5+17)->CB_current_value = 'x'; /*name5[15]*/
	(robot6axis_cams_name5+18)->CB_current_value = 't'; /*name5[16]*/
	(robot6axis_cams_name6+0)->CB_current_value = 0; /*name6 size1*/
	(robot6axis_cams_name6+1)->CB_current_value = 50; /*name6 size2*/
	(robot6axis_cams_name6+3)->CB_current_value = 'C'; /*name6[1]*/
	(robot6axis_cams_name6+4)->CB_current_value = 'a'; /*name6[2]*/
	(robot6axis_cams_name6+5)->CB_current_value = 'm'; /*name6[3]*/
	(robot6axis_cams_name6+6)->CB_current_value = 'A'; /*name6[4]*/
	(robot6axis_cams_name6+7)->CB_current_value = 'x'; /*name6[5]*/
	(robot6axis_cams_name6+8)->CB_current_value = 'i'; /*name6[6]*/
	(robot6axis_cams_name6+9)->CB_current_value = 's'; /*name6[7]*/
	(robot6axis_cams_name6+10)->CB_current_value = '6'; /*name6[8]*/
	(robot6axis_cams_name6+11)->CB_current_value = '_'; /*name6[9]*/
	(robot6axis_cams_name6+12)->CB_current_value = '1'; /*name6[10]*/
	(robot6axis_cams_name6+13)->CB_current_value = '0'; /*name6[11]*/
	(robot6axis_cams_name6+14)->CB_current_value = '0'; /*name6[12]*/
	(robot6axis_cams_name6+15)->CB_current_value = '.'; /*name6[13]*/
	(robot6axis_cams_name6+16)->CB_current_value = 't'; /*name6[14]*/
	(robot6axis_cams_name6+17)->CB_current_value = 'x'; /*name6[15]*/
	(robot6axis_cams_name6+18)->CB_current_value = 't'; /*name6[16]*/
	(robot6axis_cams_name1_rej+0)->CB_current_value = 0; /*name1_rej size1*/
	(robot6axis_cams_name1_rej+1)->CB_current_value = 50; /*name1_rej size2*/
	(robot6axis_cams_name1_rej+3)->CB_current_value = 'C'; /*name1_rej[1]*/
	(robot6axis_cams_name1_rej+4)->CB_current_value = 'a'; /*name1_rej[2]*/
	(robot6axis_cams_name1_rej+5)->CB_current_value = 'm'; /*name1_rej[3]*/
	(robot6axis_cams_name1_rej+6)->CB_current_value = 'A'; /*name1_rej[4]*/
	(robot6axis_cams_name1_rej+7)->CB_current_value = 'x'; /*name1_rej[5]*/
	(robot6axis_cams_name1_rej+8)->CB_current_value = 'i'; /*name1_rej[6]*/
	(robot6axis_cams_name1_rej+9)->CB_current_value = 's'; /*name1_rej[7]*/
	(robot6axis_cams_name1_rej+10)->CB_current_value = '1'; /*name1_rej[8]*/
	(robot6axis_cams_name1_rej+11)->CB_current_value = '_'; /*name1_rej[9]*/
	(robot6axis_cams_name1_rej+12)->CB_current_value = 'r'; /*name1_rej[10]*/
	(robot6axis_cams_name1_rej+13)->CB_current_value = 'e'; /*name1_rej[11]*/
	(robot6axis_cams_name1_rej+14)->CB_current_value = 'j'; /*name1_rej[12]*/
	(robot6axis_cams_name1_rej+15)->CB_current_value = '.'; /*name1_rej[13]*/
	(robot6axis_cams_name1_rej+16)->CB_current_value = 't'; /*name1_rej[14]*/
	(robot6axis_cams_name1_rej+17)->CB_current_value = 'x'; /*name1_rej[15]*/
	(robot6axis_cams_name1_rej+18)->CB_current_value = 't'; /*name1_rej[16]*/
	(robot6axis_cams_name2_rej+0)->CB_current_value = 0; /*name2_rej size1*/
	(robot6axis_cams_name2_rej+1)->CB_current_value = 50; /*name2_rej size2*/
	(robot6axis_cams_name2_rej+3)->CB_current_value = 'C'; /*name2_rej[1]*/
	(robot6axis_cams_name2_rej+4)->CB_current_value = 'a'; /*name2_rej[2]*/
	(robot6axis_cams_name2_rej+5)->CB_current_value = 'm'; /*name2_rej[3]*/
	(robot6axis_cams_name2_rej+6)->CB_current_value = 'A'; /*name2_rej[4]*/
	(robot6axis_cams_name2_rej+7)->CB_current_value = 'x'; /*name2_rej[5]*/
	(robot6axis_cams_name2_rej+8)->CB_current_value = 'i'; /*name2_rej[6]*/
	(robot6axis_cams_name2_rej+9)->CB_current_value = 's'; /*name2_rej[7]*/
	(robot6axis_cams_name2_rej+10)->CB_current_value = '2'; /*name2_rej[8]*/
	(robot6axis_cams_name2_rej+11)->CB_current_value = '_'; /*name2_rej[9]*/
	(robot6axis_cams_name2_rej+12)->CB_current_value = 'r'; /*name2_rej[10]*/
	(robot6axis_cams_name2_rej+13)->CB_current_value = 'e'; /*name2_rej[11]*/
	(robot6axis_cams_name2_rej+14)->CB_current_value = 'j'; /*name2_rej[12]*/
	(robot6axis_cams_name2_rej+15)->CB_current_value = '.'; /*name2_rej[13]*/
	(robot6axis_cams_name2_rej+16)->CB_current_value = 't'; /*name2_rej[14]*/
	(robot6axis_cams_name2_rej+17)->CB_current_value = 'x'; /*name2_rej[15]*/
	(robot6axis_cams_name2_rej+18)->CB_current_value = 't'; /*name2_rej[16]*/
	(robot6axis_cams_name3_rej+0)->CB_current_value = 0; /*name3_rej size1*/
	(robot6axis_cams_name3_rej+1)->CB_current_value = 50; /*name3_rej size2*/
	(robot6axis_cams_name3_rej+3)->CB_current_value = 'C'; /*name3_rej[1]*/
	(robot6axis_cams_name3_rej+4)->CB_current_value = 'a'; /*name3_rej[2]*/
	(robot6axis_cams_name3_rej+5)->CB_current_value = 'm'; /*name3_rej[3]*/
	(robot6axis_cams_name3_rej+6)->CB_current_value = 'A'; /*name3_rej[4]*/
	(robot6axis_cams_name3_rej+7)->CB_current_value = 'x'; /*name3_rej[5]*/
	(robot6axis_cams_name3_rej+8)->CB_current_value = 'i'; /*name3_rej[6]*/
	(robot6axis_cams_name3_rej+9)->CB_current_value = 's'; /*name3_rej[7]*/
	(robot6axis_cams_name3_rej+10)->CB_current_value = '3'; /*name3_rej[8]*/
	(robot6axis_cams_name3_rej+11)->CB_current_value = '_'; /*name3_rej[9]*/
	(robot6axis_cams_name3_rej+12)->CB_current_value = 'r'; /*name3_rej[10]*/
	(robot6axis_cams_name3_rej+13)->CB_current_value = 'e'; /*name3_rej[11]*/
	(robot6axis_cams_name3_rej+14)->CB_current_value = 'j'; /*name3_rej[12]*/
	(robot6axis_cams_name3_rej+15)->CB_current_value = '.'; /*name3_rej[13]*/
	(robot6axis_cams_name3_rej+16)->CB_current_value = 't'; /*name3_rej[14]*/
	(robot6axis_cams_name3_rej+17)->CB_current_value = 'x'; /*name3_rej[15]*/
	(robot6axis_cams_name3_rej+18)->CB_current_value = 't'; /*name3_rej[16]*/
	(robot6axis_cams_name4_rej+0)->CB_current_value = 0; /*name4_rej size1*/
	(robot6axis_cams_name4_rej+1)->CB_current_value = 50; /*name4_rej size2*/
	(robot6axis_cams_name4_rej+3)->CB_current_value = 'C'; /*name4_rej[1]*/
	(robot6axis_cams_name4_rej+4)->CB_current_value = 'a'; /*name4_rej[2]*/
	(robot6axis_cams_name4_rej+5)->CB_current_value = 'm'; /*name4_rej[3]*/
	(robot6axis_cams_name4_rej+6)->CB_current_value = 'A'; /*name4_rej[4]*/
	(robot6axis_cams_name4_rej+7)->CB_current_value = 'x'; /*name4_rej[5]*/
	(robot6axis_cams_name4_rej+8)->CB_current_value = 'i'; /*name4_rej[6]*/
	(robot6axis_cams_name4_rej+9)->CB_current_value = 's'; /*name4_rej[7]*/
	(robot6axis_cams_name4_rej+10)->CB_current_value = '4'; /*name4_rej[8]*/
	(robot6axis_cams_name4_rej+11)->CB_current_value = '_'; /*name4_rej[9]*/
	(robot6axis_cams_name4_rej+12)->CB_current_value = 'r'; /*name4_rej[10]*/
	(robot6axis_cams_name4_rej+13)->CB_current_value = 'e'; /*name4_rej[11]*/
	(robot6axis_cams_name4_rej+14)->CB_current_value = 'j'; /*name4_rej[12]*/
	(robot6axis_cams_name4_rej+15)->CB_current_value = '.'; /*name4_rej[13]*/
	(robot6axis_cams_name4_rej+16)->CB_current_value = 't'; /*name4_rej[14]*/
	(robot6axis_cams_name4_rej+17)->CB_current_value = 'x'; /*name4_rej[15]*/
	(robot6axis_cams_name4_rej+18)->CB_current_value = 't'; /*name4_rej[16]*/
	(robot6axis_cams_name5_rej+0)->CB_current_value = 0; /*name5_rej size1*/
	(robot6axis_cams_name5_rej+1)->CB_current_value = 50; /*name5_rej size2*/
	(robot6axis_cams_name5_rej+3)->CB_current_value = 'C'; /*name5_rej[1]*/
	(robot6axis_cams_name5_rej+4)->CB_current_value = 'a'; /*name5_rej[2]*/
	(robot6axis_cams_name5_rej+5)->CB_current_value = 'm'; /*name5_rej[3]*/
	(robot6axis_cams_name5_rej+6)->CB_current_value = 'A'; /*name5_rej[4]*/
	(robot6axis_cams_name5_rej+7)->CB_current_value = 'x'; /*name5_rej[5]*/
	(robot6axis_cams_name5_rej+8)->CB_current_value = 'i'; /*name5_rej[6]*/
	(robot6axis_cams_name5_rej+9)->CB_current_value = 's'; /*name5_rej[7]*/
	(robot6axis_cams_name5_rej+10)->CB_current_value = '5'; /*name5_rej[8]*/
	(robot6axis_cams_name5_rej+11)->CB_current_value = '_'; /*name5_rej[9]*/
	(robot6axis_cams_name5_rej+12)->CB_current_value = 'r'; /*name5_rej[10]*/
	(robot6axis_cams_name5_rej+13)->CB_current_value = 'e'; /*name5_rej[11]*/
	(robot6axis_cams_name5_rej+14)->CB_current_value = 'j'; /*name5_rej[12]*/
	(robot6axis_cams_name5_rej+15)->CB_current_value = '.'; /*name5_rej[13]*/
	(robot6axis_cams_name5_rej+16)->CB_current_value = 't'; /*name5_rej[14]*/
	(robot6axis_cams_name5_rej+17)->CB_current_value = 'x'; /*name5_rej[15]*/
	(robot6axis_cams_name5_rej+18)->CB_current_value = 't'; /*name5_rej[16]*/
	(robot6axis_cams_name6_rej+0)->CB_current_value = 0; /*name6_rej size1*/
	(robot6axis_cams_name6_rej+1)->CB_current_value = 50; /*name6_rej size2*/
	(robot6axis_cams_name6_rej+3)->CB_current_value = 'C'; /*name6_rej[1]*/
	(robot6axis_cams_name6_rej+4)->CB_current_value = 'a'; /*name6_rej[2]*/
	(robot6axis_cams_name6_rej+5)->CB_current_value = 'm'; /*name6_rej[3]*/
	(robot6axis_cams_name6_rej+6)->CB_current_value = 'A'; /*name6_rej[4]*/
	(robot6axis_cams_name6_rej+7)->CB_current_value = 'x'; /*name6_rej[5]*/
	(robot6axis_cams_name6_rej+8)->CB_current_value = 'i'; /*name6_rej[6]*/
	(robot6axis_cams_name6_rej+9)->CB_current_value = 's'; /*name6_rej[7]*/
	(robot6axis_cams_name6_rej+10)->CB_current_value = '6'; /*name6_rej[8]*/
	(robot6axis_cams_name6_rej+11)->CB_current_value = '_'; /*name6_rej[9]*/
	(robot6axis_cams_name6_rej+12)->CB_current_value = 'r'; /*name6_rej[10]*/
	(robot6axis_cams_name6_rej+13)->CB_current_value = 'e'; /*name6_rej[11]*/
	(robot6axis_cams_name6_rej+14)->CB_current_value = 'j'; /*name6_rej[12]*/
	(robot6axis_cams_name6_rej+15)->CB_current_value = '.'; /*name6_rej[13]*/
	(robot6axis_cams_name6_rej+16)->CB_current_value = 't'; /*name6_rej[14]*/
	(robot6axis_cams_name6_rej+17)->CB_current_value = 'x'; /*name6_rej[15]*/
	(robot6axis_cams_name6_rej+18)->CB_current_value = 't'; /*name6_rej[16]*/
	self.Bool+=10;
	self.Int+=50;
	self.Float+=4915;

	/*initialize child servo_kinetix2 (motion_control.servo):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Char = self.Char - __start.Char;
	servo_status = __start.Int+25; /*robot6axis_cams__cn_49*/
	servo_errorFlag = __start.Int+24; /*robot6axis_cams__cn_50*/
	servo_ActualPositionAx1 = __start.Float+2466; /*robot6axis_cams__cn_51*/
	servo_MoveVelDone1 = __start.Bool+9; /*robot6axis_cams__cn_52*/
	servo_ActualVelocity1 = __start.Float+2465; /*robot6axis_cams__cn_53*/
	servo_MoveAbsDone1 = __start.Bool+8; /*robot6axis_cams__cn_54*/
	servo_HomeCmd = robot6axis_cams_HomeCmd;
	servo_MoveVelCmd = robot6axis_cams_MoveVelCmd;
	servo_MoveAbsCmd = robot6axis_cams_MoveAbsCmd;
	servo_MoveVel1ManualCmd = robot6axis_cams_MoveVel1ManualCmd;
	servo_MoveVel2ManualCmd = robot6axis_cams_MoveVel2ManualCmd;
	servo_MoveAbs1ManualCmd = robot6axis_cams_MoveAbs1ManualCmd;
	servo_MoveAbs2ManualCmd = robot6axis_cams_MoveAbs2ManualCmd;
	servo_StopCmd = robot6axis_cams_StopCmd;
	servo_MovePosition = robot6axis_cams_MovePosition;
	servo_MoveSpeed = robot6axis_cams_MoveSpeed;
	servo_MoveAcceleration = robot6axis_cams_MoveAcceleration;
	servo_MoveDeceleration = robot6axis_cams_MoveDeceleration;
	servo_offsetAxToMa = robot6axis_cams_offsetAxToMa;
	servo_PLC_StatusReady = __start.Bool+7; /*robot6axis_cams__cn_55*/
	servo_PLC_StatusMoved = __start.Bool+6; /*robot6axis_cams__cn_56*/
	servo_PLC_StatusStand = __start.Bool+5; /*robot6axis_cams__cn_57*/
	servo_PLC_ActualPositionAx = __start.Float+2464; /*robot6axis_cams__cn_58*/
	servo_PLC_ActualPositionMa = __start.Float+2463; /*robot6axis_cams__cn_59*/
	servo_PLC_ActualVelocity = __start.Float+2462; /*robot6axis_cams__cn_60*/
	servo_physicalPosInit = __start.Float+2461; /*robot6axis_cams__cn_61*/
	servo_MAX_SPEED = __start.Float+2460; /*robot6axis_cams__cn_62*/
	servo_MAX_ACCEL = __start.Float+2459; /*robot6axis_cams__cn_63*/
	servo_MAX_DECEL = __start.Float+2458; /*robot6axis_cams__cn_64*/
	servo_MODULO_LENGTH = __start.Float+2457; /*robot6axis_cams__cn_65*/
	servo_StatusReady = __start.Bool+4; /*robot6axis_cams__cn_66*/
	servo_StatusMoved = __start.Bool+3; /*robot6axis_cams__cn_67*/
	servo_StatusStand = __start.Bool+2; /*robot6axis_cams__cn_68*/
	servo_ActualPositionAx = robot6axis_cams_ActualPositionAx;
	servo_ActualPositionMa = __start.Float+2456; /*robot6axis_cams__cn_69*/
	servo_ActualVelocity = __start.Float+2455; /*robot6axis_cams__cn_70*/
	servo_MaximumVelocity = __start.Float+2454; /*robot6axis_cams__cn_71*/
	servo_StatusPosIncrease = __start.Bool+1; /*robot6axis_cams__cn_72*/
	servo_StatusPosDecrease = __start.Bool+0; /*robot6axis_cams__cn_73*/
	servo_displayJauge = __start.Float+2453; /*robot6axis_cams__cn_74*/
	_motion_control__servo_init();

	/*initialize child cam_profile1 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile1.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile1.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile1.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile1.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name1;
	cam_profile_nbPoints = __start.Int+26; /*robot6axis_cams__cn_48*/
	cam_profile_MasterPoints = __start.Float+2467; /*robot6axis_cams__cn_47*/
	cam_profile_SlavePoints = __start.Float+2569; /*robot6axis_cams__cn_46*/
	cam_profile_pointer = __start.Int+27; /*robot6axis_cams__cn_45*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile7 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile7.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile7.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile7.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile7.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name1_rej;
	cam_profile_nbPoints = __start.Int+28; /*robot6axis_cams__cn_44*/
	cam_profile_MasterPoints = __start.Float+2671; /*robot6axis_cams__cn_43*/
	cam_profile_SlavePoints = __start.Float+2773; /*robot6axis_cams__cn_42*/
	cam_profile_pointer = __start.Int+29; /*robot6axis_cams__cn_41*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation1 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation1.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation1.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation1.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation1.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+26; /*robot6axis_cams__cn_48*/
	cam_computation_MasterPoints0 = __start.Float+2467; /*robot6axis_cams__cn_47*/
	cam_computation_SlavePoints0 = __start.Float+2569; /*robot6axis_cams__cn_46*/
	cam_computation_pointer0 = __start.Int+27; /*robot6axis_cams__cn_45*/
	cam_computation_nbPoints1 = __start.Int+28; /*robot6axis_cams__cn_44*/
	cam_computation_MasterPoints1 = __start.Float+2671; /*robot6axis_cams__cn_43*/
	cam_computation_SlavePoints1 = __start.Float+2773; /*robot6axis_cams__cn_42*/
	cam_computation_pointer1 = __start.Int+29; /*robot6axis_cams__cn_41*/
	cam_computation_nbPoints2 = __start.Int+23; /*robot6axis_cams__cn_75*/
	cam_computation_MasterPoints2 = __start.Float+2351; /*robot6axis_cams__cn_76*/
	cam_computation_SlavePoints2 = __start.Float+2249; /*robot6axis_cams__cn_77*/
	cam_computation_pointer2 = __start.Int+22; /*robot6axis_cams__cn_78*/
	cam_computation_nbPoints3 = __start.Int+21; /*robot6axis_cams__cn_79*/
	cam_computation_MasterPoints3 = __start.Float+2147; /*robot6axis_cams__cn_80*/
	cam_computation_SlavePoints3 = __start.Float+2045; /*robot6axis_cams__cn_81*/
	cam_computation_pointer3 = __start.Int+20; /*robot6axis_cams__cn_82*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition1;
	cam_computation_masterPosition = robot6axis_cams_masterPosition;
	_motion_lib__cam_computation_init();

	/*initialize child cam_profile2 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile2.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile2.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile2.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile2.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name2;
	cam_profile_nbPoints = __start.Int+30; /*robot6axis_cams__cn_40*/
	cam_profile_MasterPoints = __start.Float+2875; /*robot6axis_cams__cn_39*/
	cam_profile_SlavePoints = __start.Float+2977; /*robot6axis_cams__cn_38*/
	cam_profile_pointer = __start.Int+31; /*robot6axis_cams__cn_37*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile8 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile8.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile8.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile8.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile8.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name2_rej;
	cam_profile_nbPoints = __start.Int+32; /*robot6axis_cams__cn_36*/
	cam_profile_MasterPoints = __start.Float+3079; /*robot6axis_cams__cn_35*/
	cam_profile_SlavePoints = __start.Float+3181; /*robot6axis_cams__cn_34*/
	cam_profile_pointer = __start.Int+33; /*robot6axis_cams__cn_33*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation2 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation2.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation2.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation2.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation2.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+30; /*robot6axis_cams__cn_40*/
	cam_computation_MasterPoints0 = __start.Float+2875; /*robot6axis_cams__cn_39*/
	cam_computation_SlavePoints0 = __start.Float+2977; /*robot6axis_cams__cn_38*/
	cam_computation_pointer0 = __start.Int+31; /*robot6axis_cams__cn_37*/
	cam_computation_nbPoints1 = __start.Int+32; /*robot6axis_cams__cn_36*/
	cam_computation_MasterPoints1 = __start.Float+3079; /*robot6axis_cams__cn_35*/
	cam_computation_SlavePoints1 = __start.Float+3181; /*robot6axis_cams__cn_34*/
	cam_computation_pointer1 = __start.Int+33; /*robot6axis_cams__cn_33*/
	cam_computation_nbPoints2 = __start.Int+19; /*robot6axis_cams__cn_83*/
	cam_computation_MasterPoints2 = __start.Float+1943; /*robot6axis_cams__cn_84*/
	cam_computation_SlavePoints2 = __start.Float+1841; /*robot6axis_cams__cn_85*/
	cam_computation_pointer2 = __start.Int+18; /*robot6axis_cams__cn_86*/
	cam_computation_nbPoints3 = __start.Int+17; /*robot6axis_cams__cn_87*/
	cam_computation_MasterPoints3 = __start.Float+1739; /*robot6axis_cams__cn_88*/
	cam_computation_SlavePoints3 = __start.Float+1637; /*robot6axis_cams__cn_89*/
	cam_computation_pointer3 = __start.Int+16; /*robot6axis_cams__cn_90*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition2;
	cam_computation_masterPosition = __start.Float+1636; /*robot6axis_cams__cn_91*/
	_motion_lib__cam_computation_init();

	/*initialize child cam_profile3 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile3.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile3.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile3.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile3.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name3;
	cam_profile_nbPoints = __start.Int+34; /*robot6axis_cams__cn_32*/
	cam_profile_MasterPoints = __start.Float+3283; /*robot6axis_cams__cn_31*/
	cam_profile_SlavePoints = __start.Float+3385; /*robot6axis_cams__cn_30*/
	cam_profile_pointer = __start.Int+35; /*robot6axis_cams__cn_29*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile9 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile9.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile9.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile9.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile9.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name3_rej;
	cam_profile_nbPoints = __start.Int+36; /*robot6axis_cams__cn_28*/
	cam_profile_MasterPoints = __start.Float+3487; /*robot6axis_cams__cn_27*/
	cam_profile_SlavePoints = __start.Float+3589; /*robot6axis_cams__cn_26*/
	cam_profile_pointer = __start.Int+37; /*robot6axis_cams__cn_25*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation3 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation3.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation3.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation3.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation3.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+34; /*robot6axis_cams__cn_32*/
	cam_computation_MasterPoints0 = __start.Float+3283; /*robot6axis_cams__cn_31*/
	cam_computation_SlavePoints0 = __start.Float+3385; /*robot6axis_cams__cn_30*/
	cam_computation_pointer0 = __start.Int+35; /*robot6axis_cams__cn_29*/
	cam_computation_nbPoints1 = __start.Int+36; /*robot6axis_cams__cn_28*/
	cam_computation_MasterPoints1 = __start.Float+3487; /*robot6axis_cams__cn_27*/
	cam_computation_SlavePoints1 = __start.Float+3589; /*robot6axis_cams__cn_26*/
	cam_computation_pointer1 = __start.Int+37; /*robot6axis_cams__cn_25*/
	cam_computation_nbPoints2 = __start.Int+15; /*robot6axis_cams__cn_92*/
	cam_computation_MasterPoints2 = __start.Float+1534; /*robot6axis_cams__cn_93*/
	cam_computation_SlavePoints2 = __start.Float+1432; /*robot6axis_cams__cn_94*/
	cam_computation_pointer2 = __start.Int+14; /*robot6axis_cams__cn_95*/
	cam_computation_nbPoints3 = __start.Int+13; /*robot6axis_cams__cn_96*/
	cam_computation_MasterPoints3 = __start.Float+1330; /*robot6axis_cams__cn_97*/
	cam_computation_SlavePoints3 = __start.Float+1228; /*robot6axis_cams__cn_98*/
	cam_computation_pointer3 = __start.Int+12; /*robot6axis_cams__cn_99*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition3;
	cam_computation_masterPosition = __start.Float+1227; /*robot6axis_cams__cn_100*/
	_motion_lib__cam_computation_init();

	/*initialize child cam_profile4 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile4.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile4.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile4.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile4.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name4;
	cam_profile_nbPoints = __start.Int+38; /*robot6axis_cams__cn_24*/
	cam_profile_MasterPoints = __start.Float+3691; /*robot6axis_cams__cn_23*/
	cam_profile_SlavePoints = __start.Float+3793; /*robot6axis_cams__cn_22*/
	cam_profile_pointer = __start.Int+39; /*robot6axis_cams__cn_21*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile10 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile10.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile10.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile10.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile10.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name4_rej;
	cam_profile_nbPoints = __start.Int+40; /*robot6axis_cams__cn_20*/
	cam_profile_MasterPoints = __start.Float+3895; /*robot6axis_cams__cn_19*/
	cam_profile_SlavePoints = __start.Float+3997; /*robot6axis_cams__cn_18*/
	cam_profile_pointer = __start.Int+41; /*robot6axis_cams__cn_17*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation4 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation4.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation4.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation4.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation4.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+38; /*robot6axis_cams__cn_24*/
	cam_computation_MasterPoints0 = __start.Float+3691; /*robot6axis_cams__cn_23*/
	cam_computation_SlavePoints0 = __start.Float+3793; /*robot6axis_cams__cn_22*/
	cam_computation_pointer0 = __start.Int+39; /*robot6axis_cams__cn_21*/
	cam_computation_nbPoints1 = __start.Int+40; /*robot6axis_cams__cn_20*/
	cam_computation_MasterPoints1 = __start.Float+3895; /*robot6axis_cams__cn_19*/
	cam_computation_SlavePoints1 = __start.Float+3997; /*robot6axis_cams__cn_18*/
	cam_computation_pointer1 = __start.Int+41; /*robot6axis_cams__cn_17*/
	cam_computation_nbPoints2 = __start.Int+11; /*robot6axis_cams__cn_101*/
	cam_computation_MasterPoints2 = __start.Float+1125; /*robot6axis_cams__cn_102*/
	cam_computation_SlavePoints2 = __start.Float+1023; /*robot6axis_cams__cn_103*/
	cam_computation_pointer2 = __start.Int+10; /*robot6axis_cams__cn_104*/
	cam_computation_nbPoints3 = __start.Int+9; /*robot6axis_cams__cn_105*/
	cam_computation_MasterPoints3 = __start.Float+921; /*robot6axis_cams__cn_106*/
	cam_computation_SlavePoints3 = __start.Float+819; /*robot6axis_cams__cn_107*/
	cam_computation_pointer3 = __start.Int+8; /*robot6axis_cams__cn_108*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition4;
	cam_computation_masterPosition = __start.Float+818; /*robot6axis_cams__cn_109*/
	_motion_lib__cam_computation_init();

	/*initialize child cam_profile5 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile5.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile5.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile5.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile5.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name5;
	cam_profile_nbPoints = __start.Int+42; /*robot6axis_cams__cn_16*/
	cam_profile_MasterPoints = __start.Float+4099; /*robot6axis_cams__cn_15*/
	cam_profile_SlavePoints = __start.Float+4201; /*robot6axis_cams__cn_14*/
	cam_profile_pointer = __start.Int+43; /*robot6axis_cams__cn_13*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile11 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile11.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile11.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile11.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile11.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name5_rej;
	cam_profile_nbPoints = __start.Int+44; /*robot6axis_cams__cn_12*/
	cam_profile_MasterPoints = __start.Float+4303; /*robot6axis_cams__cn_11*/
	cam_profile_SlavePoints = __start.Float+4405; /*robot6axis_cams__cn_10*/
	cam_profile_pointer = __start.Int+45; /*robot6axis_cams__cn_9*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation5 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation5.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation5.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation5.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation5.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+42; /*robot6axis_cams__cn_16*/
	cam_computation_MasterPoints0 = __start.Float+4099; /*robot6axis_cams__cn_15*/
	cam_computation_SlavePoints0 = __start.Float+4201; /*robot6axis_cams__cn_14*/
	cam_computation_pointer0 = __start.Int+43; /*robot6axis_cams__cn_13*/
	cam_computation_nbPoints1 = __start.Int+44; /*robot6axis_cams__cn_12*/
	cam_computation_MasterPoints1 = __start.Float+4303; /*robot6axis_cams__cn_11*/
	cam_computation_SlavePoints1 = __start.Float+4405; /*robot6axis_cams__cn_10*/
	cam_computation_pointer1 = __start.Int+45; /*robot6axis_cams__cn_9*/
	cam_computation_nbPoints2 = __start.Int+7; /*robot6axis_cams__cn_110*/
	cam_computation_MasterPoints2 = __start.Float+716; /*robot6axis_cams__cn_111*/
	cam_computation_SlavePoints2 = __start.Float+614; /*robot6axis_cams__cn_112*/
	cam_computation_pointer2 = __start.Int+6; /*robot6axis_cams__cn_113*/
	cam_computation_nbPoints3 = __start.Int+5; /*robot6axis_cams__cn_114*/
	cam_computation_MasterPoints3 = __start.Float+512; /*robot6axis_cams__cn_115*/
	cam_computation_SlavePoints3 = __start.Float+410; /*robot6axis_cams__cn_116*/
	cam_computation_pointer3 = __start.Int+4; /*robot6axis_cams__cn_117*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition5;
	cam_computation_masterPosition = __start.Float+409; /*robot6axis_cams__cn_118*/
	_motion_lib__cam_computation_init();

	/*initialize child cam_profile6 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile6.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile6.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile6.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile6.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name6;
	cam_profile_nbPoints = __start.Int+46; /*robot6axis_cams__cn_8*/
	cam_profile_MasterPoints = __start.Float+4507; /*robot6axis_cams__cn_7*/
	cam_profile_SlavePoints = __start.Float+4609; /*robot6axis_cams__cn_6*/
	cam_profile_pointer = __start.Int+47; /*robot6axis_cams__cn_5*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_profile12 (motion_lib.cam_profile):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile12.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile12.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile12.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_profile12.Char = self.Char - __start.Char;
	cam_profile_name = robot6axis_cams_name6_rej;
	cam_profile_nbPoints = __start.Int+48; /*robot6axis_cams__cn_4*/
	cam_profile_MasterPoints = __start.Float+4711; /*robot6axis_cams__cn_3*/
	cam_profile_SlavePoints = __start.Float+4813; /*robot6axis_cams__cn_2*/
	cam_profile_pointer = __start.Int+49; /*robot6axis_cams__cn_1*/
	_motion_lib__cam_profile_init();

	/*initialize child cam_computation6 (motion_lib.cam_computation):*/
	self_num++;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation6.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation6.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation6.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset_cam_computation6.Char = self.Char - __start.Char;
	cam_computation_profileNr = robot6axis_cams_profileNr;
	cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
	cam_computation_nbPoints0 = __start.Int+46; /*robot6axis_cams__cn_8*/
	cam_computation_MasterPoints0 = __start.Float+4507; /*robot6axis_cams__cn_7*/
	cam_computation_SlavePoints0 = __start.Float+4609; /*robot6axis_cams__cn_6*/
	cam_computation_pointer0 = __start.Int+47; /*robot6axis_cams__cn_5*/
	cam_computation_nbPoints1 = __start.Int+48; /*robot6axis_cams__cn_4*/
	cam_computation_MasterPoints1 = __start.Float+4711; /*robot6axis_cams__cn_3*/
	cam_computation_SlavePoints1 = __start.Float+4813; /*robot6axis_cams__cn_2*/
	cam_computation_pointer1 = __start.Int+49; /*robot6axis_cams__cn_1*/
	cam_computation_nbPoints2 = __start.Int+3; /*robot6axis_cams__cn_119*/
	cam_computation_MasterPoints2 = __start.Float+307; /*robot6axis_cams__cn_120*/
	cam_computation_SlavePoints2 = __start.Float+205; /*robot6axis_cams__cn_121*/
	cam_computation_pointer2 = __start.Int+2; /*robot6axis_cams__cn_122*/
	cam_computation_nbPoints3 = __start.Int+1; /*robot6axis_cams__cn_123*/
	cam_computation_MasterPoints3 = __start.Float+103; /*robot6axis_cams__cn_124*/
	cam_computation_SlavePoints3 = __start.Float+1; /*robot6axis_cams__cn_125*/
	cam_computation_pointer3 = __start.Int+0; /*robot6axis_cams__cn_126*/
	cam_computation_slavePosition = robot6axis_cams_slavePosition6;
	cam_computation_masterPosition = __start.Float+0; /*robot6axis_cams__cn_127*/
	_motion_lib__cam_computation_init();

	robot6axis_ctrled__robot6axis_cams_offset__end.Bool = self.Bool - __start.Bool;
	robot6axis_ctrled__robot6axis_cams_offset__end.Int = self.Int - __start.Int;
	robot6axis_ctrled__robot6axis_cams_offset__end.Float = self.Float - __start.Float;
	robot6axis_ctrled__robot6axis_cams_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int robot6axis_ctrled__robot6axis_cams(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																																																																																																																																																																																																																																														
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Bool;
			self.Int = __start.Int + robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Int;
			self.Float = __start.Float + robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Float;
			self.Char = __start.Char + robot6axis_ctrled__robot6axis_cams_offset_servo_kinetix2.Char;

			/********************* servo_kinetix2 execution *********************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+25; /*robot6axis_cams__cn_49*/
				servo_errorFlag = __start.Int+24; /*robot6axis_cams__cn_50*/
				servo_ActualPositionAx1 = __start.Float+2466; /*robot6axis_cams__cn_51*/
				servo_MoveVelDone1 = __start.Bool+9; /*robot6axis_cams__cn_52*/
				servo_ActualVelocity1 = __start.Float+2465; /*robot6axis_cams__cn_53*/
				servo_MoveAbsDone1 = __start.Bool+8; /*robot6axis_cams__cn_54*/
				servo_HomeCmd = robot6axis_cams_HomeCmd;
				servo_MoveVelCmd = robot6axis_cams_MoveVelCmd;
				servo_MoveAbsCmd = robot6axis_cams_MoveAbsCmd;
				servo_MoveVel1ManualCmd = robot6axis_cams_MoveVel1ManualCmd;
				servo_MoveVel2ManualCmd = robot6axis_cams_MoveVel2ManualCmd;
				servo_MoveAbs1ManualCmd = robot6axis_cams_MoveAbs1ManualCmd;
				servo_MoveAbs2ManualCmd = robot6axis_cams_MoveAbs2ManualCmd;
				servo_StopCmd = robot6axis_cams_StopCmd;
				servo_MovePosition = robot6axis_cams_MovePosition;
				servo_MoveSpeed = robot6axis_cams_MoveSpeed;
				servo_MoveAcceleration = robot6axis_cams_MoveAcceleration;
				servo_MoveDeceleration = robot6axis_cams_MoveDeceleration;
				servo_offsetAxToMa = robot6axis_cams_offsetAxToMa;
				servo_PLC_StatusReady = __start.Bool+7; /*robot6axis_cams__cn_55*/
				servo_PLC_StatusMoved = __start.Bool+6; /*robot6axis_cams__cn_56*/
				servo_PLC_StatusStand = __start.Bool+5; /*robot6axis_cams__cn_57*/
				servo_PLC_ActualPositionAx = __start.Float+2464; /*robot6axis_cams__cn_58*/
				servo_PLC_ActualPositionMa = __start.Float+2463; /*robot6axis_cams__cn_59*/
				servo_PLC_ActualVelocity = __start.Float+2462; /*robot6axis_cams__cn_60*/
				servo_physicalPosInit = __start.Float+2461; /*robot6axis_cams__cn_61*/
				servo_MAX_SPEED = __start.Float+2460; /*robot6axis_cams__cn_62*/
				servo_MAX_ACCEL = __start.Float+2459; /*robot6axis_cams__cn_63*/
				servo_MAX_DECEL = __start.Float+2458; /*robot6axis_cams__cn_64*/
				servo_MODULO_LENGTH = __start.Float+2457; /*robot6axis_cams__cn_65*/
				servo_StatusReady = __start.Bool+4; /*robot6axis_cams__cn_66*/
				servo_StatusMoved = __start.Bool+3; /*robot6axis_cams__cn_67*/
				servo_StatusStand = __start.Bool+2; /*robot6axis_cams__cn_68*/
				servo_ActualPositionAx = robot6axis_cams_ActualPositionAx;
				servo_ActualPositionMa = __start.Float+2456; /*robot6axis_cams__cn_69*/
				servo_ActualVelocity = __start.Float+2455; /*robot6axis_cams__cn_70*/
				servo_MaximumVelocity = __start.Float+2454; /*robot6axis_cams__cn_71*/
				servo_StatusPosIncrease = __start.Bool+1; /*robot6axis_cams__cn_72*/
				servo_StatusPosDecrease = __start.Bool+0; /*robot6axis_cams__cn_73*/
				servo_displayJauge = __start.Float+2453; /*robot6axis_cams__cn_74*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile1 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name1;
				cam_profile_nbPoints = __start.Int+26; /*robot6axis_cams__cn_48*/
				cam_profile_MasterPoints = __start.Float+2467; /*robot6axis_cams__cn_47*/
				cam_profile_SlavePoints = __start.Float+2569; /*robot6axis_cams__cn_46*/
				cam_profile_pointer = __start.Int+27; /*robot6axis_cams__cn_45*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile7 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name1_rej;
				cam_profile_nbPoints = __start.Int+28; /*robot6axis_cams__cn_44*/
				cam_profile_MasterPoints = __start.Float+2671; /*robot6axis_cams__cn_43*/
				cam_profile_SlavePoints = __start.Float+2773; /*robot6axis_cams__cn_42*/
				cam_profile_pointer = __start.Int+29; /*robot6axis_cams__cn_41*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation1 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+26; /*robot6axis_cams__cn_48*/
				cam_computation_MasterPoints0 = __start.Float+2467; /*robot6axis_cams__cn_47*/
				cam_computation_SlavePoints0 = __start.Float+2569; /*robot6axis_cams__cn_46*/
				cam_computation_pointer0 = __start.Int+27; /*robot6axis_cams__cn_45*/
				cam_computation_nbPoints1 = __start.Int+28; /*robot6axis_cams__cn_44*/
				cam_computation_MasterPoints1 = __start.Float+2671; /*robot6axis_cams__cn_43*/
				cam_computation_SlavePoints1 = __start.Float+2773; /*robot6axis_cams__cn_42*/
				cam_computation_pointer1 = __start.Int+29; /*robot6axis_cams__cn_41*/
				cam_computation_nbPoints2 = __start.Int+23; /*robot6axis_cams__cn_75*/
				cam_computation_MasterPoints2 = __start.Float+2351; /*robot6axis_cams__cn_76*/
				cam_computation_SlavePoints2 = __start.Float+2249; /*robot6axis_cams__cn_77*/
				cam_computation_pointer2 = __start.Int+22; /*robot6axis_cams__cn_78*/
				cam_computation_nbPoints3 = __start.Int+21; /*robot6axis_cams__cn_79*/
				cam_computation_MasterPoints3 = __start.Float+2147; /*robot6axis_cams__cn_80*/
				cam_computation_SlavePoints3 = __start.Float+2045; /*robot6axis_cams__cn_81*/
				cam_computation_pointer3 = __start.Int+20; /*robot6axis_cams__cn_82*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition1;
				cam_computation_masterPosition = robot6axis_cams_masterPosition;
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile2 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name2;
				cam_profile_nbPoints = __start.Int+30; /*robot6axis_cams__cn_40*/
				cam_profile_MasterPoints = __start.Float+2875; /*robot6axis_cams__cn_39*/
				cam_profile_SlavePoints = __start.Float+2977; /*robot6axis_cams__cn_38*/
				cam_profile_pointer = __start.Int+31; /*robot6axis_cams__cn_37*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile8 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name2_rej;
				cam_profile_nbPoints = __start.Int+32; /*robot6axis_cams__cn_36*/
				cam_profile_MasterPoints = __start.Float+3079; /*robot6axis_cams__cn_35*/
				cam_profile_SlavePoints = __start.Float+3181; /*robot6axis_cams__cn_34*/
				cam_profile_pointer = __start.Int+33; /*robot6axis_cams__cn_33*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation2 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+30; /*robot6axis_cams__cn_40*/
				cam_computation_MasterPoints0 = __start.Float+2875; /*robot6axis_cams__cn_39*/
				cam_computation_SlavePoints0 = __start.Float+2977; /*robot6axis_cams__cn_38*/
				cam_computation_pointer0 = __start.Int+31; /*robot6axis_cams__cn_37*/
				cam_computation_nbPoints1 = __start.Int+32; /*robot6axis_cams__cn_36*/
				cam_computation_MasterPoints1 = __start.Float+3079; /*robot6axis_cams__cn_35*/
				cam_computation_SlavePoints1 = __start.Float+3181; /*robot6axis_cams__cn_34*/
				cam_computation_pointer1 = __start.Int+33; /*robot6axis_cams__cn_33*/
				cam_computation_nbPoints2 = __start.Int+19; /*robot6axis_cams__cn_83*/
				cam_computation_MasterPoints2 = __start.Float+1943; /*robot6axis_cams__cn_84*/
				cam_computation_SlavePoints2 = __start.Float+1841; /*robot6axis_cams__cn_85*/
				cam_computation_pointer2 = __start.Int+18; /*robot6axis_cams__cn_86*/
				cam_computation_nbPoints3 = __start.Int+17; /*robot6axis_cams__cn_87*/
				cam_computation_MasterPoints3 = __start.Float+1739; /*robot6axis_cams__cn_88*/
				cam_computation_SlavePoints3 = __start.Float+1637; /*robot6axis_cams__cn_89*/
				cam_computation_pointer3 = __start.Int+16; /*robot6axis_cams__cn_90*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition2;
				cam_computation_masterPosition = __start.Float+1636; /*robot6axis_cams__cn_91*/
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile3 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name3;
				cam_profile_nbPoints = __start.Int+34; /*robot6axis_cams__cn_32*/
				cam_profile_MasterPoints = __start.Float+3283; /*robot6axis_cams__cn_31*/
				cam_profile_SlavePoints = __start.Float+3385; /*robot6axis_cams__cn_30*/
				cam_profile_pointer = __start.Int+35; /*robot6axis_cams__cn_29*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile9 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name3_rej;
				cam_profile_nbPoints = __start.Int+36; /*robot6axis_cams__cn_28*/
				cam_profile_MasterPoints = __start.Float+3487; /*robot6axis_cams__cn_27*/
				cam_profile_SlavePoints = __start.Float+3589; /*robot6axis_cams__cn_26*/
				cam_profile_pointer = __start.Int+37; /*robot6axis_cams__cn_25*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation3 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+34; /*robot6axis_cams__cn_32*/
				cam_computation_MasterPoints0 = __start.Float+3283; /*robot6axis_cams__cn_31*/
				cam_computation_SlavePoints0 = __start.Float+3385; /*robot6axis_cams__cn_30*/
				cam_computation_pointer0 = __start.Int+35; /*robot6axis_cams__cn_29*/
				cam_computation_nbPoints1 = __start.Int+36; /*robot6axis_cams__cn_28*/
				cam_computation_MasterPoints1 = __start.Float+3487; /*robot6axis_cams__cn_27*/
				cam_computation_SlavePoints1 = __start.Float+3589; /*robot6axis_cams__cn_26*/
				cam_computation_pointer1 = __start.Int+37; /*robot6axis_cams__cn_25*/
				cam_computation_nbPoints2 = __start.Int+15; /*robot6axis_cams__cn_92*/
				cam_computation_MasterPoints2 = __start.Float+1534; /*robot6axis_cams__cn_93*/
				cam_computation_SlavePoints2 = __start.Float+1432; /*robot6axis_cams__cn_94*/
				cam_computation_pointer2 = __start.Int+14; /*robot6axis_cams__cn_95*/
				cam_computation_nbPoints3 = __start.Int+13; /*robot6axis_cams__cn_96*/
				cam_computation_MasterPoints3 = __start.Float+1330; /*robot6axis_cams__cn_97*/
				cam_computation_SlavePoints3 = __start.Float+1228; /*robot6axis_cams__cn_98*/
				cam_computation_pointer3 = __start.Int+12; /*robot6axis_cams__cn_99*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition3;
				cam_computation_masterPosition = __start.Float+1227; /*robot6axis_cams__cn_100*/
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile4 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name4;
				cam_profile_nbPoints = __start.Int+38; /*robot6axis_cams__cn_24*/
				cam_profile_MasterPoints = __start.Float+3691; /*robot6axis_cams__cn_23*/
				cam_profile_SlavePoints = __start.Float+3793; /*robot6axis_cams__cn_22*/
				cam_profile_pointer = __start.Int+39; /*robot6axis_cams__cn_21*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* cam_profile10 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name4_rej;
				cam_profile_nbPoints = __start.Int+40; /*robot6axis_cams__cn_20*/
				cam_profile_MasterPoints = __start.Float+3895; /*robot6axis_cams__cn_19*/
				cam_profile_SlavePoints = __start.Float+3997; /*robot6axis_cams__cn_18*/
				cam_profile_pointer = __start.Int+41; /*robot6axis_cams__cn_17*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation4 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+38; /*robot6axis_cams__cn_24*/
				cam_computation_MasterPoints0 = __start.Float+3691; /*robot6axis_cams__cn_23*/
				cam_computation_SlavePoints0 = __start.Float+3793; /*robot6axis_cams__cn_22*/
				cam_computation_pointer0 = __start.Int+39; /*robot6axis_cams__cn_21*/
				cam_computation_nbPoints1 = __start.Int+40; /*robot6axis_cams__cn_20*/
				cam_computation_MasterPoints1 = __start.Float+3895; /*robot6axis_cams__cn_19*/
				cam_computation_SlavePoints1 = __start.Float+3997; /*robot6axis_cams__cn_18*/
				cam_computation_pointer1 = __start.Int+41; /*robot6axis_cams__cn_17*/
				cam_computation_nbPoints2 = __start.Int+11; /*robot6axis_cams__cn_101*/
				cam_computation_MasterPoints2 = __start.Float+1125; /*robot6axis_cams__cn_102*/
				cam_computation_SlavePoints2 = __start.Float+1023; /*robot6axis_cams__cn_103*/
				cam_computation_pointer2 = __start.Int+10; /*robot6axis_cams__cn_104*/
				cam_computation_nbPoints3 = __start.Int+9; /*robot6axis_cams__cn_105*/
				cam_computation_MasterPoints3 = __start.Float+921; /*robot6axis_cams__cn_106*/
				cam_computation_SlavePoints3 = __start.Float+819; /*robot6axis_cams__cn_107*/
				cam_computation_pointer3 = __start.Int+8; /*robot6axis_cams__cn_108*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition4;
				cam_computation_masterPosition = __start.Float+818; /*robot6axis_cams__cn_109*/
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile5 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name5;
				cam_profile_nbPoints = __start.Int+42; /*robot6axis_cams__cn_16*/
				cam_profile_MasterPoints = __start.Float+4099; /*robot6axis_cams__cn_15*/
				cam_profile_SlavePoints = __start.Float+4201; /*robot6axis_cams__cn_14*/
				cam_profile_pointer = __start.Int+43; /*robot6axis_cams__cn_13*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* cam_profile11 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name5_rej;
				cam_profile_nbPoints = __start.Int+44; /*robot6axis_cams__cn_12*/
				cam_profile_MasterPoints = __start.Float+4303; /*robot6axis_cams__cn_11*/
				cam_profile_SlavePoints = __start.Float+4405; /*robot6axis_cams__cn_10*/
				cam_profile_pointer = __start.Int+45; /*robot6axis_cams__cn_9*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation5 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+42; /*robot6axis_cams__cn_16*/
				cam_computation_MasterPoints0 = __start.Float+4099; /*robot6axis_cams__cn_15*/
				cam_computation_SlavePoints0 = __start.Float+4201; /*robot6axis_cams__cn_14*/
				cam_computation_pointer0 = __start.Int+43; /*robot6axis_cams__cn_13*/
				cam_computation_nbPoints1 = __start.Int+44; /*robot6axis_cams__cn_12*/
				cam_computation_MasterPoints1 = __start.Float+4303; /*robot6axis_cams__cn_11*/
				cam_computation_SlavePoints1 = __start.Float+4405; /*robot6axis_cams__cn_10*/
				cam_computation_pointer1 = __start.Int+45; /*robot6axis_cams__cn_9*/
				cam_computation_nbPoints2 = __start.Int+7; /*robot6axis_cams__cn_110*/
				cam_computation_MasterPoints2 = __start.Float+716; /*robot6axis_cams__cn_111*/
				cam_computation_SlavePoints2 = __start.Float+614; /*robot6axis_cams__cn_112*/
				cam_computation_pointer2 = __start.Int+6; /*robot6axis_cams__cn_113*/
				cam_computation_nbPoints3 = __start.Int+5; /*robot6axis_cams__cn_114*/
				cam_computation_MasterPoints3 = __start.Float+512; /*robot6axis_cams__cn_115*/
				cam_computation_SlavePoints3 = __start.Float+410; /*robot6axis_cams__cn_116*/
				cam_computation_pointer3 = __start.Int+4; /*robot6axis_cams__cn_117*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition5;
				cam_computation_masterPosition = __start.Float+409; /*robot6axis_cams__cn_118*/
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cam_profile6 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name6;
				cam_profile_nbPoints = __start.Int+46; /*robot6axis_cams__cn_8*/
				cam_profile_MasterPoints = __start.Float+4507; /*robot6axis_cams__cn_7*/
				cam_profile_SlavePoints = __start.Float+4609; /*robot6axis_cams__cn_6*/
				cam_profile_pointer = __start.Int+47; /*robot6axis_cams__cn_5*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* cam_profile12 execution **********************/

			self_num++;
			if (cam_profile__num != self_num) {
				cam_profile__num = self_num;
				cam_profile_name = robot6axis_cams_name6_rej;
				cam_profile_nbPoints = __start.Int+48; /*robot6axis_cams__cn_4*/
				cam_profile_MasterPoints = __start.Float+4711; /*robot6axis_cams__cn_3*/
				cam_profile_SlavePoints = __start.Float+4813; /*robot6axis_cams__cn_2*/
				cam_profile_pointer = __start.Int+49; /*robot6axis_cams__cn_1*/
			}
			__ret = motion_lib__cam_profile();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** cam_computation6 execution ********************/

			self_num++;
			if (cam_computation__num != self_num) {
				cam_computation__num = self_num;
				cam_computation_profileNr = robot6axis_cams_profileNr;
				cam_computation_MasterPositionIn = robot6axis_cams_ActualPositionAx;
				cam_computation_nbPoints0 = __start.Int+46; /*robot6axis_cams__cn_8*/
				cam_computation_MasterPoints0 = __start.Float+4507; /*robot6axis_cams__cn_7*/
				cam_computation_SlavePoints0 = __start.Float+4609; /*robot6axis_cams__cn_6*/
				cam_computation_pointer0 = __start.Int+47; /*robot6axis_cams__cn_5*/
				cam_computation_nbPoints1 = __start.Int+48; /*robot6axis_cams__cn_4*/
				cam_computation_MasterPoints1 = __start.Float+4711; /*robot6axis_cams__cn_3*/
				cam_computation_SlavePoints1 = __start.Float+4813; /*robot6axis_cams__cn_2*/
				cam_computation_pointer1 = __start.Int+49; /*robot6axis_cams__cn_1*/
				cam_computation_nbPoints2 = __start.Int+3; /*robot6axis_cams__cn_119*/
				cam_computation_MasterPoints2 = __start.Float+307; /*robot6axis_cams__cn_120*/
				cam_computation_SlavePoints2 = __start.Float+205; /*robot6axis_cams__cn_121*/
				cam_computation_pointer2 = __start.Int+2; /*robot6axis_cams__cn_122*/
				cam_computation_nbPoints3 = __start.Int+1; /*robot6axis_cams__cn_123*/
				cam_computation_MasterPoints3 = __start.Float+103; /*robot6axis_cams__cn_124*/
				cam_computation_SlavePoints3 = __start.Float+1; /*robot6axis_cams__cn_125*/
				cam_computation_pointer3 = __start.Int+0; /*robot6axis_cams__cn_126*/
				cam_computation_slavePosition = robot6axis_cams_slavePosition6;
				cam_computation_masterPosition = __start.Float+0; /*robot6axis_cams__cn_127*/
			}
			__ret = motion_lib__cam_computation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + robot6axis_ctrled__robot6axis_cams_offset__end.Bool;
	self.Int = __start.Int + robot6axis_ctrled__robot6axis_cams_offset__end.Int;
	self.Float = __start.Float + robot6axis_ctrled__robot6axis_cams_offset__end.Float;
	self.Char = __start.Char + robot6axis_ctrled__robot6axis_cams_offset__end.Char;

	return 0;
}

