/*2023-10-04T11:03:54-01:00*/

/********************************************************************
 * servo_velocity.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__SERVO_VELOCITY_H
#define _MOTION_CONTROL__SERVO_VELOCITY_H


/********************** Variable declarations ***********************/

extern CB_Index servo_velocity__num;
extern CB_Mem_Bool *servo_velocity_MoveVelEnable;
extern CB_Mem_Bool *servo_velocity_MoveVelStart;
extern CB_Mem_Float *servo_velocity_MoveSpeed;
extern CB_Mem_Float *servo_velocity_MoveAcceleration;
extern CB_Mem_Float *servo_velocity_MoveDeceleration;
extern CB_Mem_Float *servo_velocity_MAX_SPEED;
extern CB_Mem_Float *servo_velocity_MAX_ACCEL;
extern CB_Mem_Float *servo_velocity_MAX_DECEL;
extern CB_Mem_Float *servo_velocity_MODULO_LENGTH;
extern CB_Mem_Int *servo_velocity_status;
extern CB_Mem_Int *servo_velocity_errorFlag;
extern CB_Mem_Bool *servo_velocity_MoveVelDone;
extern CB_Mem_Float *servo_velocity_ActualPositionAx;
extern CB_Mem_Float *servo_velocity_ActualVelocity;
extern CB_Mem_Bool *servo_velocity_firstStep;
extern CB_Mem_Bool *servo_velocity_stepDone;
extern CB_Mem_Float *servo_velocity_currentTime;
extern CB_Mem_Float *servo_velocity_MoveSpeed1;
extern CB_Mem_Float *servo_velocity_acceleration;
extern CB_Mem_Float *servo_velocity_deceleration;
extern CB_Mem_Float *servo_velocity_orderSpeed;
extern CB_Mem_Float *servo_velocity_endChangeSpeed;
extern CB_Mem_Float *servo_velocity_accelDecelChangeSpeed;
extern CB_Mem_Float *servo_velocity_ActualVelocity1;
extern CB_Mem_Bool *servo_velocity_speedChanged;

/********************** Function declarations ***********************/

extern int _motion_control__servo_velocity_init(void);
extern int motion_control__servo_velocity(void);

#endif /*_MOTION_CONTROL__SERVO_VELOCITY_H*/
