/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * motors.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "motors.h"


/**************************** Variables *****************************/

CB_Index motors__num = 0;
CB_Mem_Bool *motors_Auto;
CB_Mem_Bool *motors_Manu;
CB_Mem_Bool *motors_run;
CB_Mem_Bool *motors_presConvUp;
CB_Mem_Bool *motors_presConvDw;
CB_Mem_Float *motors_masterPosition;
CB_Mem_Int *motors_mesuredWeight;
CB_Mem_Int *motors_phaseCode;
CB_Mem_Bool *motors_forwardUp;
CB_Mem_Bool *motors_backwardUp;
CB_Mem_Bool *motors_forwardDw;
CB_Mem_Bool *motors_backwardDw;
CB_Mem_Bool *motors_ejectBadProd;
CB_Mem_Bool *motors_weihtOk;
CB_Mem_Bool *motors_upperLimitOk;
CB_Mem_Bool *motors_lowerLimitOk;
CB_Mem_Int *motors_prtSensorConvDw;
CB_Mem_Int *motors_prtSensorConvUp;
CB_Mem_Int *motors_upperLimitWeight;
CB_Mem_Int *motors_lowerLimitWeight;
CB_Mem_Bool *motors_le_int1_OUT;
CB_Mem_Bool *motors_gt_int1_OUT;
CB_Mem_Bool *motors_ton1_Q;
CB_Mem_Int *motors_ton1_CV;
CB_Mem_Int *motors_ton1_t1;
CB_Mem_Int *motors_ton1_tn;
CB_Mem_Bool *motors__13__3_Out;
CB_Mem_Bool *motors_tof1_Q;
CB_Mem_Int *motors_tof1_CV;
CB_Mem_Int *motors_tof1_t1;
CB_Mem_Int *motors_tof1_memo_tof;
CB_Mem_Int *motors_tof1_tn;

/**************************** Variables *****************************/

#define Auto (motors_Auto->CB_current_value)
#define Manu (motors_Manu->CB_current_value)
#define run (motors_run->CB_current_value)
#define presConvUp (motors_presConvUp->CB_current_value)
#define presConvDw (motors_presConvDw->CB_current_value)
#define masterPosition (motors_masterPosition->CB_current_value)
#define mesuredWeight (*((short *)&(motors_mesuredWeight->CB_current_value) + ALIGN_OFFSET_SHORT))
#define phaseCode (*((short *)&(motors_phaseCode->CB_current_value) + ALIGN_OFFSET_SHORT))
#define forwardUp (motors_forwardUp->CB_current_value)
#define backwardUp (motors_backwardUp->CB_current_value)
#define forwardDw (motors_forwardDw->CB_current_value)
#define backwardDw (motors_backwardDw->CB_current_value)
#define ejectBadProd (motors_ejectBadProd->CB_current_value)
#define weihtOk (motors_weihtOk->CB_current_value)
#define upperLimitOk (motors_upperLimitOk->CB_current_value)
#define lowerLimitOk (motors_lowerLimitOk->CB_current_value)
#define prtSensorConvDw(i) (motors_prtSensorConvDw[i+1].CB_current_value)
#define prtSensorConvUp(i) (motors_prtSensorConvUp[i+1].CB_current_value)
#define upperLimitWeight (*((short *)&(motors_upperLimitWeight->CB_current_value) + ALIGN_OFFSET_SHORT))
#define lowerLimitWeight (*((short *)&(motors_lowerLimitWeight->CB_current_value) + ALIGN_OFFSET_SHORT))
#define le_int1_OUT (motors_le_int1_OUT->CB_current_value)
#define gt_int1_OUT (motors_gt_int1_OUT->CB_current_value)
#define ton1_Q (motors_ton1_Q->CB_current_value)
#define ton1_CV(i) (motors_ton1_CV[i+1].CB_current_value)
#define ton1_t1(i) (motors_ton1_t1[i+1].CB_current_value)
#define ton1_tn (motors_ton1_tn->CB_current_value)
#define _13__3_Out (motors__13__3_Out->CB_current_value)
#define tof1_Q (motors_tof1_Q->CB_current_value)
#define tof1_CV(i) (motors_tof1_CV[i+1].CB_current_value)
#define tof1_t1(i) (motors_tof1_t1[i+1].CB_current_value)
#define tof1_memo_tof (*((short *)&(motors_tof1_memo_tof->CB_current_value) + ALIGN_OFFSET_SHORT))
#define tof1_tn (motors_tof1_tn->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _flask_motion_app__motors_init(void)
{
	(self.Int+0+3)->CB_current_value = 5000; /*prtSensorConvDw[2]*/
	(self.Int+4+3)->CB_current_value = 8000; /*prtSensorConvUp[2]*/
	*((short *)&((self.Int+8)->CB_current_value) + ALIGN_OFFSET_SHORT) = 125; /*upperLimitWeight*/
	*((short *)&((self.Int+9)->CB_current_value) + ALIGN_OFFSET_SHORT) = 115; /*lowerLimitWeight*/
	self.Bool+=7;
	self.Int+=29;


	return 0;
}


/************************ Behavior function *************************/

int flask_motion_app__motors(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		motors_upperLimitOk = self.Bool+0;
		motors_lowerLimitOk = self.Bool+1;
		motors_prtSensorConvDw = self.Int+0;
		motors_prtSensorConvUp = self.Int+4;
		motors_upperLimitWeight = self.Int+8;
		motors_lowerLimitWeight = self.Int+9;
		motors_le_int1_OUT = self.Bool+2;
		motors_gt_int1_OUT = self.Bool+3;
		motors_ton1_Q = self.Bool+4;
		motors_ton1_CV = self.Int+10;
		motors_ton1_t1 = self.Int+14;
		motors_ton1_tn = self.Int+18;
		motors__13__3_Out = self.Bool+5;
		motors_tof1_Q = self.Bool+6;
		motors_tof1_CV = self.Int+19;
		motors_tof1_t1 = self.Int+23;
		motors_tof1_memo_tof = self.Int+27;
		motors_tof1_tn = self.Int+28;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _3;
			CB_Mem_Int _12[4] =  { cb_int_header(2) };
			CB_Mem_Int _11[4] =  { cb_int_header(2) };
			le_int1_OUT = le_int_OUT(mesuredWeight, upperLimitWeight);
			upperLimitOk = le_int1_OUT;
			gt_int1_OUT = gt_int_OUT(mesuredWeight, lowerLimitWeight);
			lowerLimitOk = gt_int1_OUT;
			weihtOk = upperLimitOk && lowerLimitOk;
			_3 = (Auto && run) && !presConvDw;
			copy_int_array(_12, motors_prtSensorConvUp, 2);
			ton1_Q = ton_Q(_3, _12, motors_ton1_t1, &ton1_tn);
			copy_int_array(motors_ton1_CV, ton_CV(_3, _12, motors_ton1_t1, &ton1_tn), 2);
			backwardDw = ton1_Q;
			if ((Auto && run) && presConvUp) {
				_13__3_Out = phaseCode != 4;
			}
			else {
				_13__3_Out = 0;
			}
			copy_int_array(_11, motors_prtSensorConvDw, 2);
			tof1_Q = tof_Q(_13__3_Out, _11, motors_tof1_t1, &tof1_memo_tof, &tof1_tn);
			copy_int_array(motors_tof1_CV, tof_CV(_13__3_Out, _11, motors_tof1_t1, &tof1_memo_tof, &tof1_tn), 2);
			forwardUp = tof1_Q;
			ejectBadProd = (((Auto && run) && presConvDw) && !weihtOk) && !backwardDw;
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(motors_forwardUp);
		CB_post_bool(motors_backwardUp);
		CB_post_bool(motors_forwardDw);
		CB_post_bool(motors_backwardDw);
		CB_post_bool(motors_ejectBadProd);
		CB_post_bool(motors_weihtOk);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 7;
	self.Int += 29;

	return 0;
}

