/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * motors.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _FLASK_MOTION_APP__MOTORS_H
#define _FLASK_MOTION_APP__MOTORS_H


/********************** Variable declarations ***********************/

extern CB_Index motors__num;
extern CB_Mem_Bool *motors_Auto;
extern CB_Mem_Bool *motors_Manu;
extern CB_Mem_Bool *motors_run;
extern CB_Mem_Bool *motors_presConvUp;
extern CB_Mem_Bool *motors_presConvDw;
extern CB_Mem_Float *motors_masterPosition;
extern CB_Mem_Int *motors_mesuredWeight;
extern CB_Mem_Int *motors_phaseCode;
extern CB_Mem_Bool *motors_forwardUp;
extern CB_Mem_Bool *motors_backwardUp;
extern CB_Mem_Bool *motors_forwardDw;
extern CB_Mem_Bool *motors_backwardDw;
extern CB_Mem_Bool *motors_ejectBadProd;
extern CB_Mem_Bool *motors_weihtOk;
extern CB_Mem_Bool *motors_upperLimitOk;
extern CB_Mem_Bool *motors_lowerLimitOk;
extern CB_Mem_Int *motors_prtSensorConvDw;
extern CB_Mem_Int *motors_prtSensorConvUp;
extern CB_Mem_Int *motors_upperLimitWeight;
extern CB_Mem_Int *motors_lowerLimitWeight;

/********************** Function declarations ***********************/

extern int _flask_motion_app__motors_init(void);
extern int flask_motion_app__motors(void);

#endif /*_FLASK_MOTION_APP__MOTORS_H*/
