/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * weighingscale.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__WEIGHINGSCALE_H
#define _MOTION_LIB__WEIGHINGSCALE_H


/********************** Variable declarations ***********************/

extern CB_Index weighingscale__num;
extern CB_Mem_Int *weighingscale_Weight;
extern CB_Mem_Int *weighingscale_status_act_prod;
extern CB_Mem_Float *weighingscale_m11;
extern CB_Mem_Float *weighingscale_m12;
extern CB_Mem_Float *weighingscale_m13;
extern CB_Mem_Float *weighingscale_m14;
extern CB_Mem_Float *weighingscale_m21;
extern CB_Mem_Float *weighingscale_m22;
extern CB_Mem_Float *weighingscale_m23;
extern CB_Mem_Float *weighingscale_m24;
extern CB_Mem_Float *weighingscale_m31;
extern CB_Mem_Float *weighingscale_m32;
extern CB_Mem_Float *weighingscale_m33;
extern CB_Mem_Float *weighingscale_m34;
extern CB_Mem_Float *weighingscale_m41;
extern CB_Mem_Float *weighingscale_m42;
extern CB_Mem_Float *weighingscale_m43;
extern CB_Mem_Float *weighingscale_m44;
extern CB_Mem_Int *weighingscale_weight;

/********************** Function declarations ***********************/

extern int _motion_lib__weighingscale_init(void);
extern int motion_lib__weighingscale(void);

/************************** Access macros ***************************/

#define mx_acces_motion_lib__weighingscale__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_lib__weighingscale__m11 Float[0].CB_current_value
#define mx_acces_motion_lib__weighingscale__m12 Float[1].CB_current_value
#define mx_acces_motion_lib__weighingscale__m13 Float[2].CB_current_value
#define mx_acces_motion_lib__weighingscale__m14 Float[3].CB_current_value
#define mx_acces_motion_lib__weighingscale__m21 Float[4].CB_current_value
#define mx_acces_motion_lib__weighingscale__m22 Float[5].CB_current_value
#define mx_acces_motion_lib__weighingscale__m23 Float[6].CB_current_value
#define mx_acces_motion_lib__weighingscale__m24 Float[7].CB_current_value
#define mx_acces_motion_lib__weighingscale__m31 Float[8].CB_current_value
#define mx_acces_motion_lib__weighingscale__m32 Float[9].CB_current_value
#define mx_acces_motion_lib__weighingscale__m33 Float[10].CB_current_value
#define mx_acces_motion_lib__weighingscale__m34 Float[11].CB_current_value
#define mx_acces_motion_lib__weighingscale__m41 Float[12].CB_current_value
#define mx_acces_motion_lib__weighingscale__m42 Float[13].CB_current_value
#define mx_acces_motion_lib__weighingscale__m43 Float[14].CB_current_value
#define mx_acces_motion_lib__weighingscale__m44 Float[15].CB_current_value
#define mx_acces_motion_lib__weighingscale__weight Int[1].CB_current_value

#endif /*_MOTION_LIB__WEIGHINGSCALE_H*/
