/*2023-10-04T11:03:52-01:00*/

/********************************************************************
 * trigger_function.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__TRIGGER_FUNCTION_H
#define _MOTION_LIB__TRIGGER_FUNCTION_H


/********************** Variable declarations ***********************/

extern CB_Index trigger_function__num;
extern CB_Mem_Float *trigger_function_armExtrem;
extern CB_Mem_Int *trigger_function_productId;
extern CB_Mem_Float *trigger_function_velX;
extern CB_Mem_Float *trigger_function_velY;
extern CB_Mem_Float *trigger_function_velZ;
extern CB_Mem_Bool *trigger_function_armInStop;
extern CB_Mem_Float *trigger_function_armExtrem1;
extern CB_Mem_Int *trigger_function_i;
extern CB_Mem_Float *trigger_function_productTimeDetect;
extern CB_Mem_Bool *trigger_function_productDetected;
extern CB_Mem_Int *trigger_function_productId1;
extern CB_Mem_Bool *trigger_function_actionTake;
extern CB_Mem_Bool *trigger_function_activeArea;
extern CB_Mem_Float *trigger_function_ACTIVE_AREA_Z;
extern CB_Mem_Float *trigger_function_TEMPO_DETECTION_PRO;

/********************** Function declarations ***********************/

extern int _motion_lib__trigger_function_init(void);
extern int motion_lib__trigger_function(void);

#endif /*_MOTION_LIB__TRIGGER_FUNCTION_H*/
