/*2023-10-04T11:03:52-01:00*/

/********************************************************************
 * trigger_function.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "trigger_function.h"



/**************************** Variables *****************************/

CB_Index trigger_function__num = 0;
CB_Mem_Float *trigger_function_armExtrem;
CB_Mem_Int *trigger_function_productId;
CB_Mem_Float *trigger_function_velX;
CB_Mem_Float *trigger_function_velY;
CB_Mem_Float *trigger_function_velZ;
CB_Mem_Bool *trigger_function_armInStop;
CB_Mem_Float *trigger_function_armExtrem1;
CB_Mem_Int *trigger_function_i;
CB_Mem_Float *trigger_function_productTimeDetect;
CB_Mem_Bool *trigger_function_productDetected;
CB_Mem_Int *trigger_function_productId1;
CB_Mem_Bool *trigger_function_actionTake;
CB_Mem_Bool *trigger_function_activeArea;
CB_Mem_Float *trigger_function_ACTIVE_AREA_Z;
CB_Mem_Float *trigger_function_TEMPO_DETECTION_PRO;

/**************************** Variables *****************************/

#define armExtrem(i) (trigger_function_armExtrem[i+1].CB_current_value)
#define productId (trigger_function_productId->CB_current_value)
#define velX (trigger_function_velX->CB_current_value)
#define velY (trigger_function_velY->CB_current_value)
#define velZ (trigger_function_velZ->CB_current_value)
#define armInStop (trigger_function_armInStop->CB_current_value)
#define armExtrem1(i) (trigger_function_armExtrem1[i+1].CB_current_value)
#define i (*((short *)&(trigger_function_i->CB_current_value) + ALIGN_OFFSET_SHORT))
#define productTimeDetect (trigger_function_productTimeDetect->CB_current_value)
#define productDetected (trigger_function_productDetected->CB_current_value)
#define productId1 (trigger_function_productId1->CB_current_value)
#define actionTake (trigger_function_actionTake->CB_current_value)
#define activeArea (trigger_function_activeArea->CB_current_value)
#define ACTIVE_AREA_Z (trigger_function_ACTIVE_AREA_Z->CB_current_value)
#define TEMPO_DETECTION_PRO (trigger_function_TEMPO_DETECTION_PRO->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_lib__trigger_function_init(void)
{
	(trigger_function_productId)->CB_current_value = (-1); /*productId*/
	(self.Int+1)->CB_current_value = (-1); /*productId1*/
	(self.Float+6)->CB_current_value = 1100.0; /*ACTIVE_AREA_Z*/
	(self.Float+7)->CB_current_value = 0.2; /*TEMPO_DETECTION_PRO*/
	self.Bool+=3;
	self.Int+=2;
	self.Float+=8;


	return 0;
}


/************************ Behavior function *************************/

int motion_lib__trigger_function(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		trigger_function_armExtrem1 = self.Float+0;
		trigger_function_i = self.Int+0;
		trigger_function_productTimeDetect = self.Float+5;
		trigger_function_productDetected = self.Bool+0;
		trigger_function_productId1 = self.Int+1;
		trigger_function_actionTake = self.Bool+1;
		trigger_function_activeArea = self.Bool+2;
		trigger_function_ACTIVE_AREA_Z = self.Float+6;
		trigger_function_TEMPO_DETECTION_PRO = self.Float+7;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

			if (productId1 == -1 && productId != -1) 
				productTimeDetect = 0;

			if (productId != -1) 
				productTimeDetect += CLOCK_PERIOD / 1000000;

			if (productTimeDetect > TEMPO_DETECTION_PRO) productDetected = 1; else productDetected = 0;

			velX = 1000000 * (armExtrem(1) - armExtrem1(1)) / CLOCK_PERIOD; // mm/s
			velY = 1000000 * (armExtrem(2) - armExtrem1(2)) / CLOCK_PERIOD;
			velZ = 1000000 * (armExtrem(3) - armExtrem1(3)) / CLOCK_PERIOD;

			armInStop = (fabs(velX) < 10 && fabs(velY) < 10 && velZ < -50);



			for (i = 1; i <= 3; i++)
				armExtrem1(i) = armExtrem(i);

			productId1 = productId;
		}

		CB_post_float(trigger_function_velX);
		CB_post_float(trigger_function_velY);
		CB_post_float(trigger_function_velZ);
		CB_post_bool(trigger_function_armInStop);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 3;
	self.Int += 2;
	self.Float += 8;

	return 0;
}

