/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * presence_sensor.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"
#include "cb_products_iec.h"

#include "presence_sensor.h"



/**************************** Variables *****************************/

CB_Index presence_sensor__num = 0;
CB_Mem_Float *presence_sensor_incPositionX;
CB_Mem_Float *presence_sensor_incPositionY;
CB_Mem_Float *presence_sensor_incPositionZ;
CB_Mem_Float *presence_sensor_coordCenterX;
CB_Mem_Float *presence_sensor_coordCenterY;
CB_Mem_Float *presence_sensor_coordCenterZ;
CB_Mem_Float *presence_sensor_incRotationX;
CB_Mem_Float *presence_sensor_incRotationY;
CB_Mem_Float *presence_sensor_incRotationZ;
CB_Mem_Bool *presence_sensor_sensorSupply;
CB_Mem_Bool *presence_sensor_presence;
CB_Mem_Int *presence_sensor_status_act_prod;
CB_Mem_Float *presence_sensor_m11;
CB_Mem_Float *presence_sensor_m12;
CB_Mem_Float *presence_sensor_m13;
CB_Mem_Float *presence_sensor_m14;
CB_Mem_Float *presence_sensor_m21;
CB_Mem_Float *presence_sensor_m22;
CB_Mem_Float *presence_sensor_m23;
CB_Mem_Float *presence_sensor_m24;
CB_Mem_Float *presence_sensor_m31;
CB_Mem_Float *presence_sensor_m32;
CB_Mem_Float *presence_sensor_m33;
CB_Mem_Float *presence_sensor_m34;
CB_Mem_Float *presence_sensor_m41;
CB_Mem_Float *presence_sensor_m42;
CB_Mem_Float *presence_sensor_m43;
CB_Mem_Float *presence_sensor_m44;
CB_Mem_Bool *presence_sensor_detection;
CB_Mem_Bool *presence_sensor_presenceLogic;
CB_Mem_Bool *presence_sensor_d_presence;
CB_Mem_Bool *presence_sensor_v_d_presence;

/**************************** Variables *****************************/

#define incPositionX (presence_sensor_incPositionX->CB_current_value)
#define incPositionY (presence_sensor_incPositionY->CB_current_value)
#define incPositionZ (presence_sensor_incPositionZ->CB_current_value)
#define coordCenterX (presence_sensor_coordCenterX->CB_current_value)
#define coordCenterY (presence_sensor_coordCenterY->CB_current_value)
#define coordCenterZ (presence_sensor_coordCenterZ->CB_current_value)
#define incRotationX (presence_sensor_incRotationX->CB_current_value)
#define incRotationY (presence_sensor_incRotationY->CB_current_value)
#define incRotationZ (presence_sensor_incRotationZ->CB_current_value)
#define sensorSupply (presence_sensor_sensorSupply->CB_current_value)
#define presence (presence_sensor_presence->CB_current_value)
#define status_act_prod (presence_sensor_status_act_prod->CB_current_value)
#define m11 (presence_sensor_m11->CB_current_value)
#define m12 (presence_sensor_m12->CB_current_value)
#define m13 (presence_sensor_m13->CB_current_value)
#define m14 (presence_sensor_m14->CB_current_value)
#define m21 (presence_sensor_m21->CB_current_value)
#define m22 (presence_sensor_m22->CB_current_value)
#define m23 (presence_sensor_m23->CB_current_value)
#define m24 (presence_sensor_m24->CB_current_value)
#define m31 (presence_sensor_m31->CB_current_value)
#define m32 (presence_sensor_m32->CB_current_value)
#define m33 (presence_sensor_m33->CB_current_value)
#define m34 (presence_sensor_m34->CB_current_value)
#define m41 (presence_sensor_m41->CB_current_value)
#define m42 (presence_sensor_m42->CB_current_value)
#define m43 (presence_sensor_m43->CB_current_value)
#define m44 (presence_sensor_m44->CB_current_value)
#define detection (presence_sensor_detection->CB_current_value)
#define presenceLogic (presence_sensor_presenceLogic->CB_current_value)
#define d_presence (presence_sensor_d_presence->CB_current_value)
#define v_d_presence (presence_sensor_v_d_presence->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_lib__presence_sensor_init(void)
{
	(presence_sensor_sensorSupply)->CB_current_value = 1; /*sensorSupply*/
	(self.Float+0)->CB_current_value = 1.0; /*m11*/
	(self.Float+5)->CB_current_value = 1.0; /*m22*/
	(self.Float+10)->CB_current_value = 1.0; /*m33*/
	(self.Float+15)->CB_current_value = 1.0; /*m44*/
	(self.Bool+1)->CB_current_value = 1; /*presenceLogic*/
	(self.Bool+3)->CB_current_value = 1; /*v_d_presence*/
	self.Bool+=4;
	self.Int+=1;
	self.Float+=16;


	return 0;
}


/************************ Behavior function *************************/

int motion_lib__presence_sensor(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		presence_sensor_status_act_prod = self.Int+0;
		presence_sensor_m11 = self.Float+0;
		presence_sensor_m12 = self.Float+1;
		presence_sensor_m13 = self.Float+2;
		presence_sensor_m14 = self.Float+3;
		presence_sensor_m21 = self.Float+4;
		presence_sensor_m22 = self.Float+5;
		presence_sensor_m23 = self.Float+6;
		presence_sensor_m24 = self.Float+7;
		presence_sensor_m31 = self.Float+8;
		presence_sensor_m32 = self.Float+9;
		presence_sensor_m33 = self.Float+10;
		presence_sensor_m34 = self.Float+11;
		presence_sensor_m41 = self.Float+12;
		presence_sensor_m42 = self.Float+13;
		presence_sensor_m43 = self.Float+14;
		presence_sensor_m44 = self.Float+15;
		presence_sensor_detection = self.Bool+0;
		presence_sensor_presenceLogic = self.Bool+1;
		presence_sensor_d_presence = self.Bool+2;
		presence_sensor_v_d_presence = self.Bool+3;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Actor Myself init *************************/

		setMyselfFor(self_num);

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Actors and Products						*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates the behaviour of a presence sensor that 	*/
			/* detects products.								*/
			/* It is an "actor" and can be shifted or rotated.			*/
			/* The product that is in interaction should modify the variable 	*/
			/* "detection".								*/
			/* ----------------------------------------------------------------	*/


			/* Management of the detection	*/
			if (d_presence) presence = v_d_presence;
			else 
				presence = sensorSupply & (detection ^ ! presenceLogic);


			/* Reset informations given by the product	*/
			detection = 0;

			/* Association with a traverser : take account of the traverse speed	*/
			if ((incPositionX != 0.0) || (incPositionY != 0.0) || (incPositionZ != 0.0))
				moveBy(myself, incPositionX, incPositionY, incPositionZ);

			/* Association with a rotary plate ring : take account of the rotation speed	*/
			if ((incRotationX != 0.0) || (incRotationY != 0.0) || (incRotationZ != 0.0))
				rotateBy(myself, incRotationX, incRotationY, incRotationZ, coordCenterX, coordCenterY, coordCenterZ);


		}

		CB_post_bool(presence_sensor_presence);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 4;
	self.Int += 1;
	self.Float += 16;

	return 0;
}

