#ifndef mx_included_product_h
#define mx_included_product_h


/*****************************************************
                             Variables
******************************************************/
extern CB_Index product__num;
extern CB_Mem_Int *product_status_act_prod;
extern CB_Mem_Float *product_m11;
extern CB_Mem_Float *product_m12;
extern CB_Mem_Float *product_m13;
extern CB_Mem_Float *product_m14;
extern CB_Mem_Float *product_m21;
extern CB_Mem_Float *product_m22;
extern CB_Mem_Float *product_m23;
extern CB_Mem_Float *product_m24;
extern CB_Mem_Float *product_m31;
extern CB_Mem_Float *product_m32;
extern CB_Mem_Float *product_m33;
extern CB_Mem_Float *product_m34;
extern CB_Mem_Float *product_m41;
extern CB_Mem_Float *product_m42;
extern CB_Mem_Float *product_m43;
extern CB_Mem_Float *product_m44;
extern CB_Mem_Float *product_movementConv;
extern CB_Mem_Bool *product_contact;
extern CB_Mem_Float *product_centreRotX;
extern CB_Mem_Float *product_centreRotZ;
extern CB_Mem_Float *product_centreRotY;
extern CB_Mem_Int *product_moveDirection;
extern CB_Mem_Int *product_idConv;
extern CB_Mem_Bool *product_moveAuthorization;
extern CB_Mem_Int *product_number;
extern CB_Mem_Int *product_idProdBelow;
extern CB_Mem_Int *product_prodId;
extern CB_Mem_Float *product_oldOtherPx;
extern CB_Mem_Float *product_oldOtherPy;
extern CB_Mem_Float *product_oldOtherPz;
extern CB_Mem_Float *product_oldOtherRx;
extern CB_Mem_Float *product_oldOtherRy;
extern CB_Mem_Float *product_oldOtherRz;
extern CB_Mem_Float *product_gravitySpeed;
extern CB_Mem_Int *product_oldIdConv;
extern CB_Mem_Int *product_display1;
extern CB_Mem_Int *product_display2;
extern CB_Mem_Int *product_display3;
extern CB_Mem_Int *product_display4;
extern CB_Mem_Int *product_display5;
extern CB_Mem_Int *product_display6;
extern CB_Mem_Int *product_display7;
extern CB_Mem_Int *product_display8;
extern CB_Mem_Int *product_display9;
extern CB_Mem_Int *product_display10;
extern CB_Mem_Float *product_oPx;
extern CB_Mem_Float *product_oPy;
extern CB_Mem_Float *product_oPz;
extern CB_Mem_Float *product_oAx;
extern CB_Mem_Float *product_oAy;
extern CB_Mem_Float *product_oAz;
extern CB_Mem_Bool *product_armActive;
extern CB_Mem_Bool *product_memArmActive;
extern CB_Mem_Float *product_refAngZ;
extern CB_Mem_Float *product_refAngY;
extern CB_Mem_Float *product_refAngX;
extern CB_Mem_Float *product_refZ;
extern CB_Mem_Float *product_refY;
extern CB_Mem_Float *product_refX;
extern CB_Mem_Float *product_refSizeOthX;
extern CB_Mem_Float *product_refAngOthZ;
extern CB_Mem_Float *product_refAngOthY;
extern CB_Mem_Float *product_refAngOthX;
extern CB_Mem_Float *product_refOthZ;
extern CB_Mem_Float *product_refOthY;
extern CB_Mem_Float *product_refOthX;
extern CB_Mem_Bool *product_empty1;
extern CB_Mem_Bool *product_empty2;
extern CB_Mem_Bool *product_empty3;
extern CB_Mem_Bool *product_empty4;
extern CB_Mem_Bool *product_empty5;
extern CB_Mem_Bool *product_empty6;
extern CB_Mem_Bool *product_empty7;
extern CB_Mem_Bool *product_empty8;
extern CB_Mem_Int *product_weight;

extern int motion_control__product();

extern int motion_control__product__test_interarctions();

/*****************************************************
                     variables access macros :
******************************************************/
#define mx_acces_motion_control__product__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_control__product__m11 Float[0].CB_current_value
#define mx_acces_motion_control__product__m12 Float[1].CB_current_value
#define mx_acces_motion_control__product__m13 Float[2].CB_current_value
#define mx_acces_motion_control__product__m14 Float[3].CB_current_value
#define mx_acces_motion_control__product__m21 Float[4].CB_current_value
#define mx_acces_motion_control__product__m22 Float[5].CB_current_value
#define mx_acces_motion_control__product__m23 Float[6].CB_current_value
#define mx_acces_motion_control__product__m24 Float[7].CB_current_value
#define mx_acces_motion_control__product__m31 Float[8].CB_current_value
#define mx_acces_motion_control__product__m32 Float[9].CB_current_value
#define mx_acces_motion_control__product__m33 Float[10].CB_current_value
#define mx_acces_motion_control__product__m34 Float[11].CB_current_value
#define mx_acces_motion_control__product__m41 Float[12].CB_current_value
#define mx_acces_motion_control__product__m42 Float[13].CB_current_value
#define mx_acces_motion_control__product__m43 Float[14].CB_current_value
#define mx_acces_motion_control__product__m44 Float[15].CB_current_value
#define mx_acces_motion_control__product__movementConv Float[16].CB_current_value
#define mx_acces_motion_control__product__contact Bool[0].CB_current_value
#define mx_acces_motion_control__product__centreRotX Float[17].CB_current_value
#define mx_acces_motion_control__product__centreRotZ Float[18].CB_current_value
#define mx_acces_motion_control__product__centreRotY Float[19].CB_current_value
#define mx_acces_motion_control__product__moveDirection Int[1].CB_current_value
#define mx_acces_motion_control__product__idConv Int[2].CB_current_value
#define mx_acces_motion_control__product__moveAuthorization Bool[1].CB_current_value
#define mx_acces_motion_control__product__number Int[3].CB_current_value
#define mx_acces_motion_control__product__idProdBelow Int[4].CB_current_value
#define mx_acces_motion_control__product__prodId Int[5].CB_current_value
#define mx_acces_motion_control__product__oldOtherPx Float[20].CB_current_value
#define mx_acces_motion_control__product__oldOtherPy Float[21].CB_current_value
#define mx_acces_motion_control__product__oldOtherPz Float[22].CB_current_value
#define mx_acces_motion_control__product__oldOtherRx Float[23].CB_current_value
#define mx_acces_motion_control__product__oldOtherRy Float[24].CB_current_value
#define mx_acces_motion_control__product__oldOtherRz Float[25].CB_current_value
#define mx_acces_motion_control__product__gravitySpeed Float[26].CB_current_value
#define mx_acces_motion_control__product__oldIdConv Int[6].CB_current_value
#define mx_acces_motion_control__product__display1 Int[7].CB_current_value
#define mx_acces_motion_control__product__display2 Int[8].CB_current_value
#define mx_acces_motion_control__product__display3 Int[9].CB_current_value
#define mx_acces_motion_control__product__display4 Int[10].CB_current_value
#define mx_acces_motion_control__product__display5 Int[11].CB_current_value
#define mx_acces_motion_control__product__display6 Int[12].CB_current_value
#define mx_acces_motion_control__product__display7 Int[13].CB_current_value
#define mx_acces_motion_control__product__display8 Int[14].CB_current_value
#define mx_acces_motion_control__product__display9 Int[15].CB_current_value
#define mx_acces_motion_control__product__display10 Int[16].CB_current_value
#define mx_acces_motion_control__product__oPx Float[27].CB_current_value
#define mx_acces_motion_control__product__oPy Float[28].CB_current_value
#define mx_acces_motion_control__product__oPz Float[29].CB_current_value
#define mx_acces_motion_control__product__oAx Float[30].CB_current_value
#define mx_acces_motion_control__product__oAy Float[31].CB_current_value
#define mx_acces_motion_control__product__oAz Float[32].CB_current_value
#define mx_acces_motion_control__product__armActive Bool[2].CB_current_value
#define mx_acces_motion_control__product__memArmActive Bool[3].CB_current_value
#define mx_acces_motion_control__product__refAngZ Float[33].CB_current_value
#define mx_acces_motion_control__product__refAngY Float[34].CB_current_value
#define mx_acces_motion_control__product__refAngX Float[35].CB_current_value
#define mx_acces_motion_control__product__refZ Float[36].CB_current_value
#define mx_acces_motion_control__product__refY Float[37].CB_current_value
#define mx_acces_motion_control__product__refX Float[38].CB_current_value
#define mx_acces_motion_control__product__refSizeOthX Float[39].CB_current_value
#define mx_acces_motion_control__product__refAngOthZ Float[40].CB_current_value
#define mx_acces_motion_control__product__refAngOthY Float[41].CB_current_value
#define mx_acces_motion_control__product__refAngOthX Float[42].CB_current_value
#define mx_acces_motion_control__product__refOthZ Float[43].CB_current_value
#define mx_acces_motion_control__product__refOthY Float[44].CB_current_value
#define mx_acces_motion_control__product__refOthX Float[45].CB_current_value
#define mx_acces_motion_control__product__empty1 Bool[4].CB_current_value
#define mx_acces_motion_control__product__empty2 Bool[5].CB_current_value
#define mx_acces_motion_control__product__empty3 Bool[6].CB_current_value
#define mx_acces_motion_control__product__empty4 Bool[7].CB_current_value
#define mx_acces_motion_control__product__empty5 Bool[8].CB_current_value
#define mx_acces_motion_control__product__empty6 Bool[9].CB_current_value
#define mx_acces_motion_control__product__empty7 Bool[10].CB_current_value
#define mx_acces_motion_control__product__empty8 Bool[11].CB_current_value
#define mx_acces_motion_control__product__weight Int[17].CB_current_value

#endif
