<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generator: ControlBuild -->

<CB_COMPONENT NAME="product" COMMENTS="This module simulates a generic product &quot;box&quot;." COMMENTS_PATTERN="&lt;CLASS_PATTERN&gt;" PICTURE_PATH="" INSTANCE_NAMIMG_PATTERN="&lt;CLASS_PATTERN&gt;" COMPONENT_CLASS="" SAFE_MODE="False" BREAKPOINT="False" PLMId="" COMPONENT_CLASS_UUID="">
	<MODEL_REQUIREMENTS>
		<FUNCTIONAL_TREE TYPE="prod" />
	</MODEL_REQUIREMENTS>
</CB_COMPONENT>