/*2023-10-04T11:03:53-01:00*/

/********************************************************************
 * robot6axis.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "robot6axis.h"
#include "motion_control/functional/servo/servo.h"
#include "motion_control/functional/robotic_arm/robotic_arm.h"
#include "motion_lib/functional/trigger_function/trigger_function.h"


/**************************** Variables *****************************/

CB_Index robot6axis__num = 0;
CB_Mem_Float *robot6axis_armOrigin;
CB_Mem_Float *robot6axis_structRotVectorFOOT;
CB_Mem_Float *robot6axis_structRotDegFOOT;
CB_Mem_Float *robot6axis_ownRotDegFOOT;
CB_Mem_Float *robot6axis_structRotVectorFOOT2;
CB_Mem_Float *robot6axis_structRotDegFOOT2;
CB_Mem_Float *robot6axis_structRotVectorArm2;
CB_Mem_Float *robot6axis_structRotDegArm2;
CB_Mem_Float *robot6axis_driveRotVector1;
CB_Mem_Float *robot6axis_driveRotVector2;
CB_Mem_Float *robot6axis_driveRotVector3;
CB_Mem_Float *robot6axis_driveRotVector4;
CB_Mem_Float *robot6axis_driveRotVector5;
CB_Mem_Float *robot6axis_driveRotVector6;
CB_Mem_Float *robot6axis_structRotVector1RowA;
CB_Mem_Float *robot6axis_structRotDeg1RowA;
CB_Mem_Float *robot6axis_structRotVector1RowB;
CB_Mem_Float *robot6axis_structRotDeg1RowB;
CB_Mem_Float *robot6axis_structRotVectorMultiRowsA;
CB_Mem_Float *robot6axis_structRotDegMultiRowsA;
CB_Mem_Float *robot6axis_structRotVectorMultiRowsB;
CB_Mem_Float *robot6axis_structRotDegMultiRowsB;
CB_Mem_Bool *robot6axis_HomeCmd;
CB_Mem_Bool *robot6axis_MoveVelCmd;
CB_Mem_Bool *robot6axis_MoveAbsCmd;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd;
CB_Mem_Bool *robot6axis_StopCmd;
CB_Mem_Float *robot6axis_MovePosition;
CB_Mem_Float *robot6axis_MoveSpeed;
CB_Mem_Float *robot6axis_MoveAcceleration;
CB_Mem_Float *robot6axis_MoveDeceleration;
CB_Mem_Float *robot6axis_offsetAxToMa;
CB_Mem_Bool *robot6axis_HomeCmd2;
CB_Mem_Bool *robot6axis_MoveVelCmd2;
CB_Mem_Bool *robot6axis_MoveAbsCmd2;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd2;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd2;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd2;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd2;
CB_Mem_Bool *robot6axis_StopCmd2;
CB_Mem_Float *robot6axis_MovePosition2;
CB_Mem_Float *robot6axis_MoveSpeed2;
CB_Mem_Float *robot6axis_MoveAcceleration2;
CB_Mem_Float *robot6axis_MoveDeceleration2;
CB_Mem_Float *robot6axis_offsetAxToMa2;
CB_Mem_Bool *robot6axis_HomeCmd3;
CB_Mem_Bool *robot6axis_MoveVelCmd3;
CB_Mem_Bool *robot6axis_MoveAbsCmd3;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd3;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd3;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd3;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd3;
CB_Mem_Bool *robot6axis_StopCmd3;
CB_Mem_Float *robot6axis_MovePosition3;
CB_Mem_Float *robot6axis_MoveSpeed3;
CB_Mem_Float *robot6axis_MoveAcceleration3;
CB_Mem_Float *robot6axis_MoveDeceleration3;
CB_Mem_Float *robot6axis_offsetAxToMa3;
CB_Mem_Bool *robot6axis_HomeCmd4;
CB_Mem_Bool *robot6axis_MoveVelCmd4;
CB_Mem_Bool *robot6axis_MoveAbsCmd4;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd4;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd4;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd4;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd4;
CB_Mem_Bool *robot6axis_StopCmd4;
CB_Mem_Float *robot6axis_MovePosition4;
CB_Mem_Float *robot6axis_MoveSpeed4;
CB_Mem_Float *robot6axis_MoveAcceleration4;
CB_Mem_Float *robot6axis_MoveDeceleration4;
CB_Mem_Float *robot6axis_offsetAxToMa4;
CB_Mem_Bool *robot6axis_HomeCmd5;
CB_Mem_Bool *robot6axis_MoveVelCmd5;
CB_Mem_Bool *robot6axis_MoveAbsCmd5;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd5;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd5;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd5;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd5;
CB_Mem_Bool *robot6axis_StopCmd5;
CB_Mem_Float *robot6axis_MovePosition5;
CB_Mem_Float *robot6axis_MoveSpeed5;
CB_Mem_Float *robot6axis_MoveAcceleration5;
CB_Mem_Float *robot6axis_MoveDeceleration5;
CB_Mem_Float *robot6axis_offsetAxToMa5;
CB_Mem_Bool *robot6axis_HomeCmd6;
CB_Mem_Bool *robot6axis_MoveVelCmd6;
CB_Mem_Bool *robot6axis_MoveAbsCmd6;
CB_Mem_Bool *robot6axis_MoveVel1ManualCmd6;
CB_Mem_Bool *robot6axis_MoveVel2ManualCmd6;
CB_Mem_Bool *robot6axis_MoveAbs1ManualCmd6;
CB_Mem_Bool *robot6axis_MoveAbs2ManualCmd6;
CB_Mem_Bool *robot6axis_StopCmd6;
CB_Mem_Float *robot6axis_MovePosition6;
CB_Mem_Float *robot6axis_MoveSpeed6;
CB_Mem_Float *robot6axis_MoveAcceleration6;
CB_Mem_Float *robot6axis_MoveDeceleration6;
CB_Mem_Float *robot6axis_offsetAxToMa6;
CB_Mem_Bool *robot6axis_PLC_StatusReady;
CB_Mem_Bool *robot6axis_PLC_StatusMoved;
CB_Mem_Bool *robot6axis_PLC_StatusStand;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa;
CB_Mem_Float *robot6axis_PLC_ActualVelocity;
CB_Mem_Bool *robot6axis_PLC_StatusReady2;
CB_Mem_Bool *robot6axis_PLC_StatusMoved2;
CB_Mem_Bool *robot6axis_PLC_StatusStand2;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx2;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa2;
CB_Mem_Float *robot6axis_PLC_ActualVelocity2;
CB_Mem_Bool *robot6axis_PLC_StatusReady3;
CB_Mem_Bool *robot6axis_PLC_StatusMoved3;
CB_Mem_Bool *robot6axis_PLC_StatusStand3;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx3;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa3;
CB_Mem_Float *robot6axis_PLC_ActualVelocity3;
CB_Mem_Bool *robot6axis_PLC_StatusReady4;
CB_Mem_Bool *robot6axis_PLC_StatusMoved4;
CB_Mem_Bool *robot6axis_PLC_StatusStand4;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx4;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa4;
CB_Mem_Float *robot6axis_PLC_ActualVelocity4;
CB_Mem_Bool *robot6axis_PLC_StatusReady5;
CB_Mem_Bool *robot6axis_PLC_StatusMoved5;
CB_Mem_Bool *robot6axis_PLC_StatusStand5;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx5;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa5;
CB_Mem_Float *robot6axis_PLC_ActualVelocity5;
CB_Mem_Bool *robot6axis_PLC_StatusReady6;
CB_Mem_Bool *robot6axis_PLC_StatusMoved6;
CB_Mem_Bool *robot6axis_PLC_StatusStand6;
CB_Mem_Float *robot6axis_PLC_ActualPositionAx6;
CB_Mem_Float *robot6axis_PLC_ActualPositionMa6;
CB_Mem_Float *robot6axis_PLC_ActualVelocity6;
CB_Mem_Bool *robot6axis_gripSyringes;
CB_Mem_Float *robot6axis_ActualVelocity1;
CB_Mem_Float *robot6axis_ActualVelocity2;
CB_Mem_Float *robot6axis_ActualVelocity3;
CB_Mem_Float *robot6axis_ActualVelocity4;
CB_Mem_Float *robot6axis_ActualVelocity5;
CB_Mem_Float *robot6axis_ActualVelocity6;
CB_Mem_Float *robot6axis_armExtrem;
CB_Mem_Float *robot6axis_velX;
CB_Mem_Float *robot6axis_velY;
CB_Mem_Float *robot6axis_velZ;
CB_Mem_Bool *robot6axis_armInStop;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset motion_lib__robot6axis_offset_servo_1;
static CB_Offset motion_lib__robot6axis_offset_FOOT;
static CB_Offset motion_lib__robot6axis_offset_FOOT2;
static CB_Offset motion_lib__robot6axis_offset_servo_2;
static CB_Offset motion_lib__robot6axis_offset_arm2;
static CB_Offset motion_lib__robot6axis_offset_servo_3;
static CB_Offset motion_lib__robot6axis_offset_arm3;
static CB_Offset motion_lib__robot6axis_offset_servo_4;
static CB_Offset motion_lib__robot6axis_offset_arm4;
static CB_Offset motion_lib__robot6axis_offset_servo_5;
static CB_Offset motion_lib__robot6axis_offset_arm5;
static CB_Offset motion_lib__robot6axis_offset_servo_6;
static CB_Offset motion_lib__robot6axis_offset_arm6;
static CB_Offset motion_lib__robot6axis_offset_function_trigger;
static CB_Offset motion_lib__robot6axis_offset_arm1RowA;
static CB_Offset motion_lib__robot6axis_offset_arm1RowB;
static CB_Offset motion_lib__robot6axis_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _motion_lib__robot6axis_init(void)
{
	CB_Object __start = self;
	(robot6axis_armOrigin+2)->CB_current_value = 8705.0; /*armOrigin[1]*/
	(robot6axis_armOrigin+3)->CB_current_value = 1630.0; /*armOrigin[2]*/
	(robot6axis_armOrigin+4)->CB_current_value = 540.0; /*armOrigin[3]*/
	(robot6axis_structRotVectorFOOT+3)->CB_current_value = 1.0; /*structRotVectorFOOT[2]*/
	(robot6axis_structRotDegFOOT)->CB_current_value = (-90.01); /*structRotDegFOOT*/
	(robot6axis_ownRotDegFOOT)->CB_current_value = 90.0; /*ownRotDegFOOT*/
	(robot6axis_structRotVectorFOOT2+4)->CB_current_value = 1.0; /*structRotVectorFOOT2[3]*/
	(robot6axis_structRotDegFOOT2)->CB_current_value = 90.0; /*structRotDegFOOT2*/
	(robot6axis_structRotVectorArm2+4)->CB_current_value = 1.0; /*structRotVectorArm2[3]*/
	(robot6axis_structRotDegArm2)->CB_current_value = (-90.0); /*structRotDegArm2*/
	(robot6axis_driveRotVector1+2)->CB_current_value = 1.0; /*driveRotVector1[1]*/
	(robot6axis_driveRotVector2+3)->CB_current_value = 1.0; /*driveRotVector2[2]*/
	(robot6axis_driveRotVector3+3)->CB_current_value = 1.0; /*driveRotVector3[2]*/
	(robot6axis_driveRotVector4+2)->CB_current_value = 1.0; /*driveRotVector4[1]*/
	(robot6axis_driveRotVector5+3)->CB_current_value = 1.0; /*driveRotVector5[2]*/
	(robot6axis_driveRotVector6+2)->CB_current_value = 1.0; /*driveRotVector6[1]*/
	(robot6axis_structRotVector1RowA+3)->CB_current_value = 1.0; /*structRotVector1RowA[2]*/
	(robot6axis_structRotDeg1RowA)->CB_current_value = (-90.0); /*structRotDeg1RowA*/
	(robot6axis_structRotVector1RowB+3)->CB_current_value = 1.0; /*structRotVector1RowB[2]*/
	(robot6axis_structRotDeg1RowB)->CB_current_value = 90.0; /*structRotDeg1RowB*/
	(robot6axis_structRotVectorMultiRowsA+3)->CB_current_value = 1.0; /*structRotVectorMultiRowsA[2]*/
	(robot6axis_structRotDegMultiRowsA)->CB_current_value = 90.0; /*structRotDegMultiRowsA*/
	(robot6axis_structRotVectorMultiRowsB+3)->CB_current_value = 1.0; /*structRotVectorMultiRowsB[2]*/
	(robot6axis_structRotDegMultiRowsB)->CB_current_value = (-90.0); /*structRotDegMultiRowsB*/
	(robot6axis_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(robot6axis_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(robot6axis_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	(robot6axis_MoveSpeed2)->CB_current_value = 100.0; /*MoveSpeed2*/
	(robot6axis_MoveAcceleration2)->CB_current_value = 100.0; /*MoveAcceleration2*/
	(robot6axis_MoveDeceleration2)->CB_current_value = 100.0; /*MoveDeceleration2*/
	(robot6axis_MoveSpeed3)->CB_current_value = 100.0; /*MoveSpeed3*/
	(robot6axis_MoveAcceleration3)->CB_current_value = 100.0; /*MoveAcceleration3*/
	(robot6axis_MoveDeceleration3)->CB_current_value = 100.0; /*MoveDeceleration3*/
	(robot6axis_MoveSpeed4)->CB_current_value = 100.0; /*MoveSpeed4*/
	(robot6axis_MoveAcceleration4)->CB_current_value = 100.0; /*MoveAcceleration4*/
	(robot6axis_MoveDeceleration4)->CB_current_value = 100.0; /*MoveDeceleration4*/
	(robot6axis_MoveSpeed5)->CB_current_value = 100.0; /*MoveSpeed5*/
	(robot6axis_MoveAcceleration5)->CB_current_value = 100.0; /*MoveAcceleration5*/
	(robot6axis_MoveDeceleration5)->CB_current_value = 100.0; /*MoveDeceleration5*/
	(robot6axis_MoveSpeed6)->CB_current_value = 100.0; /*MoveSpeed6*/
	(robot6axis_MoveAcceleration6)->CB_current_value = 100.0; /*MoveAcceleration6*/
	(robot6axis_MoveDeceleration6)->CB_current_value = 100.0; /*MoveDeceleration6*/
	(robot6axis_PLC_StatusReady)->CB_current_value = 1; /*PLC_StatusReady*/
	(robot6axis_PLC_StatusReady2)->CB_current_value = 1; /*PLC_StatusReady2*/
	(robot6axis_PLC_StatusReady3)->CB_current_value = 1; /*PLC_StatusReady3*/
	(robot6axis_PLC_StatusReady4)->CB_current_value = 1; /*PLC_StatusReady4*/
	(robot6axis_PLC_StatusReady5)->CB_current_value = 1; /*PLC_StatusReady5*/
	(robot6axis_PLC_StatusReady6)->CB_current_value = 1; /*PLC_StatusReady6*/
	self.Bool+=50;
	self.Int+=21;
	self.Float+=225;

	/*initialize child servo_1 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_1.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_1.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_1.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_1.Char = self.Char - __start.Char;
	servo_status = __start.Int+19; /*robot6axis__cn_23*/
	servo_errorFlag = __start.Int+18; /*robot6axis__cn_24*/
	servo_ActualPositionAx1 = __start.Float+135; /*robot6axis__cn_25*/
	servo_MoveVelDone1 = __start.Bool+49; /*robot6axis__cn_26*/
	servo_ActualVelocity1 = __start.Float+134; /*robot6axis__cn_27*/
	servo_MoveAbsDone1 = __start.Bool+48; /*robot6axis__cn_28*/
	servo_HomeCmd = robot6axis_HomeCmd;
	servo_MoveVelCmd = robot6axis_MoveVelCmd;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd;
	servo_StopCmd = robot6axis_StopCmd;
	servo_MovePosition = robot6axis_MovePosition;
	servo_MoveSpeed = robot6axis_MoveSpeed;
	servo_MoveAcceleration = robot6axis_MoveAcceleration;
	servo_MoveDeceleration = robot6axis_MoveDeceleration;
	servo_offsetAxToMa = robot6axis_offsetAxToMa;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity;
	servo_physicalPosInit = __start.Float+133; /*robot6axis__cn_29*/
	servo_MAX_SPEED = __start.Float+132; /*robot6axis__cn_30*/
	servo_MAX_ACCEL = __start.Float+131; /*robot6axis__cn_31*/
	servo_MAX_DECEL = __start.Float+130; /*robot6axis__cn_32*/
	servo_MODULO_LENGTH = __start.Float+129; /*robot6axis__cn_33*/
	servo_StatusReady = __start.Bool+47; /*robot6axis__cn_34*/
	servo_StatusMoved = __start.Bool+46; /*robot6axis__cn_35*/
	servo_StatusStand = __start.Bool+45; /*robot6axis__cn_36*/
	servo_ActualPositionAx = __start.Float+136; /*robot6axis__cn_22*/
	servo_ActualPositionMa = __start.Float+128; /*robot6axis__cn_37*/
	servo_ActualVelocity = robot6axis_ActualVelocity1;
	servo_MaximumVelocity = __start.Float+127; /*robot6axis__cn_38*/
	servo_StatusPosIncrease = __start.Bool+44; /*robot6axis__cn_39*/
	servo_StatusPosDecrease = __start.Bool+43; /*robot6axis__cn_40*/
	servo_displayJauge = __start.Float+126; /*robot6axis__cn_41*/
	_motion_control__servo_init();

	/*initialize child FOOT (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_FOOT.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_FOOT.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_FOOT.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_FOOT.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = robot6axis_armOrigin;
	robotic_arm_overallArmQuatInput = __start.Float+120; /*robot6axis__cn_42*/
	robotic_arm_structRotVector = robot6axis_structRotVectorFOOT;
	robotic_arm_structRotDeg = robot6axis_structRotDegFOOT;
	robotic_arm_driveRotVector = robot6axis_driveRotVector1;
	robotic_arm_driveRotDeg = __start.Float+136; /*robot6axis__cn_22*/
	robotic_arm_ownRotDeg = robot6axis_ownRotDegFOOT;
	robotic_arm_driveResizeLength = __start.Float+119; /*robot6axis__cn_43*/
	robotic_arm_functionActive = __start.Bool+42; /*robot6axis__cn_44*/
	robotic_arm_armExtrem = __start.Float+137; /*robot6axis__cn_21*/
	robotic_arm_overallArmRotOutput = __start.Float+142; /*robot6axis__cn_20*/
	robotic_arm_productId = __start.Int+17; /*robot6axis__cn_45*/
	_motion_control__robotic_arm_init();

	/*initialize child FOOT2 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_FOOT2.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_FOOT2.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_FOOT2.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_FOOT2.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+137; /*robot6axis__cn_21*/
	robotic_arm_overallArmQuatInput = __start.Float+142; /*robot6axis__cn_20*/
	robotic_arm_structRotVector = robot6axis_structRotVectorFOOT2;
	robotic_arm_structRotDeg = robot6axis_structRotDegFOOT2;
	robotic_arm_driveRotVector = __start.Float+114; /*robot6axis__cn_46*/
	robotic_arm_driveRotDeg = __start.Float+113; /*robot6axis__cn_47*/
	robotic_arm_ownRotDeg = __start.Float+112; /*robot6axis__cn_48*/
	robotic_arm_driveResizeLength = __start.Float+111; /*robot6axis__cn_49*/
	robotic_arm_functionActive = __start.Bool+41; /*robot6axis__cn_50*/
	robotic_arm_armExtrem = __start.Float+148; /*robot6axis__cn_19*/
	robotic_arm_overallArmRotOutput = __start.Float+153; /*robot6axis__cn_18*/
	robotic_arm_productId = __start.Int+16; /*robot6axis__cn_51*/
	_motion_control__robotic_arm_init();

	/*initialize child servo_2 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_2.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_2.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_2.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_2.Char = self.Char - __start.Char;
	servo_status = __start.Int+15; /*robot6axis__cn_52*/
	servo_errorFlag = __start.Int+14; /*robot6axis__cn_53*/
	servo_ActualPositionAx1 = __start.Float+110; /*robot6axis__cn_54*/
	servo_MoveVelDone1 = __start.Bool+40; /*robot6axis__cn_55*/
	servo_ActualVelocity1 = __start.Float+109; /*robot6axis__cn_56*/
	servo_MoveAbsDone1 = __start.Bool+39; /*robot6axis__cn_57*/
	servo_HomeCmd = robot6axis_HomeCmd2;
	servo_MoveVelCmd = robot6axis_MoveVelCmd2;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd2;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd2;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd2;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd2;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd2;
	servo_StopCmd = robot6axis_StopCmd2;
	servo_MovePosition = robot6axis_MovePosition2;
	servo_MoveSpeed = robot6axis_MoveSpeed2;
	servo_MoveAcceleration = robot6axis_MoveAcceleration2;
	servo_MoveDeceleration = robot6axis_MoveDeceleration2;
	servo_offsetAxToMa = robot6axis_offsetAxToMa2;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady2;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved2;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand2;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx2;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa2;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity2;
	servo_physicalPosInit = __start.Float+108; /*robot6axis__cn_58*/
	servo_MAX_SPEED = __start.Float+107; /*robot6axis__cn_59*/
	servo_MAX_ACCEL = __start.Float+106; /*robot6axis__cn_60*/
	servo_MAX_DECEL = __start.Float+105; /*robot6axis__cn_61*/
	servo_MODULO_LENGTH = __start.Float+104; /*robot6axis__cn_62*/
	servo_StatusReady = __start.Bool+38; /*robot6axis__cn_63*/
	servo_StatusMoved = __start.Bool+37; /*robot6axis__cn_64*/
	servo_StatusStand = __start.Bool+36; /*robot6axis__cn_65*/
	servo_ActualPositionAx = __start.Float+159; /*robot6axis__cn_17*/
	servo_ActualPositionMa = __start.Float+103; /*robot6axis__cn_66*/
	servo_ActualVelocity = robot6axis_ActualVelocity2;
	servo_MaximumVelocity = __start.Float+102; /*robot6axis__cn_67*/
	servo_StatusPosIncrease = __start.Bool+35; /*robot6axis__cn_68*/
	servo_StatusPosDecrease = __start.Bool+34; /*robot6axis__cn_69*/
	servo_displayJauge = __start.Float+101; /*robot6axis__cn_70*/
	_motion_control__servo_init();

	/*initialize child arm2 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm2.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm2.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm2.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm2.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+148; /*robot6axis__cn_19*/
	robotic_arm_overallArmQuatInput = __start.Float+153; /*robot6axis__cn_18*/
	robotic_arm_structRotVector = robot6axis_structRotVectorArm2;
	robotic_arm_structRotDeg = robot6axis_structRotDegArm2;
	robotic_arm_driveRotVector = robot6axis_driveRotVector2;
	robotic_arm_driveRotDeg = __start.Float+159; /*robot6axis__cn_17*/
	robotic_arm_ownRotDeg = __start.Float+100; /*robot6axis__cn_71*/
	robotic_arm_driveResizeLength = __start.Float+99; /*robot6axis__cn_72*/
	robotic_arm_functionActive = __start.Bool+33; /*robot6axis__cn_73*/
	robotic_arm_armExtrem = __start.Float+160; /*robot6axis__cn_16*/
	robotic_arm_overallArmRotOutput = __start.Float+165; /*robot6axis__cn_15*/
	robotic_arm_productId = __start.Int+13; /*robot6axis__cn_74*/
	_motion_control__robotic_arm_init();

	/*initialize child servo_3 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_3.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_3.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_3.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_3.Char = self.Char - __start.Char;
	servo_status = __start.Int+12; /*robot6axis__cn_75*/
	servo_errorFlag = __start.Int+11; /*robot6axis__cn_76*/
	servo_ActualPositionAx1 = __start.Float+98; /*robot6axis__cn_77*/
	servo_MoveVelDone1 = __start.Bool+32; /*robot6axis__cn_78*/
	servo_ActualVelocity1 = __start.Float+97; /*robot6axis__cn_79*/
	servo_MoveAbsDone1 = __start.Bool+31; /*robot6axis__cn_80*/
	servo_HomeCmd = robot6axis_HomeCmd3;
	servo_MoveVelCmd = robot6axis_MoveVelCmd3;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd3;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd3;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd3;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd3;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd3;
	servo_StopCmd = robot6axis_StopCmd3;
	servo_MovePosition = robot6axis_MovePosition3;
	servo_MoveSpeed = robot6axis_MoveSpeed3;
	servo_MoveAcceleration = robot6axis_MoveAcceleration3;
	servo_MoveDeceleration = robot6axis_MoveDeceleration3;
	servo_offsetAxToMa = robot6axis_offsetAxToMa3;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady3;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved3;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand3;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx3;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa3;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity3;
	servo_physicalPosInit = __start.Float+96; /*robot6axis__cn_81*/
	servo_MAX_SPEED = __start.Float+95; /*robot6axis__cn_82*/
	servo_MAX_ACCEL = __start.Float+94; /*robot6axis__cn_83*/
	servo_MAX_DECEL = __start.Float+93; /*robot6axis__cn_84*/
	servo_MODULO_LENGTH = __start.Float+92; /*robot6axis__cn_85*/
	servo_StatusReady = __start.Bool+30; /*robot6axis__cn_86*/
	servo_StatusMoved = __start.Bool+29; /*robot6axis__cn_87*/
	servo_StatusStand = __start.Bool+28; /*robot6axis__cn_88*/
	servo_ActualPositionAx = __start.Float+171; /*robot6axis__cn_14*/
	servo_ActualPositionMa = __start.Float+91; /*robot6axis__cn_89*/
	servo_ActualVelocity = robot6axis_ActualVelocity3;
	servo_MaximumVelocity = __start.Float+90; /*robot6axis__cn_90*/
	servo_StatusPosIncrease = __start.Bool+27; /*robot6axis__cn_91*/
	servo_StatusPosDecrease = __start.Bool+26; /*robot6axis__cn_92*/
	servo_displayJauge = __start.Float+89; /*robot6axis__cn_93*/
	_motion_control__servo_init();

	/*initialize child arm3 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm3.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm3.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm3.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm3.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+160; /*robot6axis__cn_16*/
	robotic_arm_overallArmQuatInput = __start.Float+165; /*robot6axis__cn_15*/
	robotic_arm_structRotVector = __start.Float+84; /*robot6axis__cn_94*/
	robotic_arm_structRotDeg = __start.Float+83; /*robot6axis__cn_95*/
	robotic_arm_driveRotVector = robot6axis_driveRotVector3;
	robotic_arm_driveRotDeg = __start.Float+171; /*robot6axis__cn_14*/
	robotic_arm_ownRotDeg = __start.Float+82; /*robot6axis__cn_96*/
	robotic_arm_driveResizeLength = __start.Float+81; /*robot6axis__cn_97*/
	robotic_arm_functionActive = __start.Bool+25; /*robot6axis__cn_98*/
	robotic_arm_armExtrem = __start.Float+172; /*robot6axis__cn_13*/
	robotic_arm_overallArmRotOutput = __start.Float+177; /*robot6axis__cn_12*/
	robotic_arm_productId = __start.Int+10; /*robot6axis__cn_99*/
	_motion_control__robotic_arm_init();

	/*initialize child servo_4 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_4.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_4.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_4.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_4.Char = self.Char - __start.Char;
	servo_status = __start.Int+9; /*robot6axis__cn_100*/
	servo_errorFlag = __start.Int+8; /*robot6axis__cn_101*/
	servo_ActualPositionAx1 = __start.Float+80; /*robot6axis__cn_102*/
	servo_MoveVelDone1 = __start.Bool+24; /*robot6axis__cn_103*/
	servo_ActualVelocity1 = __start.Float+79; /*robot6axis__cn_104*/
	servo_MoveAbsDone1 = __start.Bool+23; /*robot6axis__cn_105*/
	servo_HomeCmd = robot6axis_HomeCmd4;
	servo_MoveVelCmd = robot6axis_MoveVelCmd4;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd4;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd4;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd4;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd4;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd4;
	servo_StopCmd = robot6axis_StopCmd4;
	servo_MovePosition = robot6axis_MovePosition4;
	servo_MoveSpeed = robot6axis_MoveSpeed4;
	servo_MoveAcceleration = robot6axis_MoveAcceleration4;
	servo_MoveDeceleration = robot6axis_MoveDeceleration4;
	servo_offsetAxToMa = robot6axis_offsetAxToMa4;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady4;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved4;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand4;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx4;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa4;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity4;
	servo_physicalPosInit = __start.Float+78; /*robot6axis__cn_106*/
	servo_MAX_SPEED = __start.Float+77; /*robot6axis__cn_107*/
	servo_MAX_ACCEL = __start.Float+76; /*robot6axis__cn_108*/
	servo_MAX_DECEL = __start.Float+75; /*robot6axis__cn_109*/
	servo_MODULO_LENGTH = __start.Float+74; /*robot6axis__cn_110*/
	servo_StatusReady = __start.Bool+22; /*robot6axis__cn_111*/
	servo_StatusMoved = __start.Bool+21; /*robot6axis__cn_112*/
	servo_StatusStand = __start.Bool+20; /*robot6axis__cn_113*/
	servo_ActualPositionAx = __start.Float+183; /*robot6axis__cn_11*/
	servo_ActualPositionMa = __start.Float+73; /*robot6axis__cn_114*/
	servo_ActualVelocity = robot6axis_ActualVelocity4;
	servo_MaximumVelocity = __start.Float+72; /*robot6axis__cn_115*/
	servo_StatusPosIncrease = __start.Bool+19; /*robot6axis__cn_116*/
	servo_StatusPosDecrease = __start.Bool+18; /*robot6axis__cn_117*/
	servo_displayJauge = __start.Float+71; /*robot6axis__cn_118*/
	_motion_control__servo_init();

	/*initialize child arm4 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm4.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm4.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm4.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm4.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+172; /*robot6axis__cn_13*/
	robotic_arm_overallArmQuatInput = __start.Float+177; /*robot6axis__cn_12*/
	robotic_arm_structRotVector = __start.Float+66; /*robot6axis__cn_119*/
	robotic_arm_structRotDeg = __start.Float+65; /*robot6axis__cn_120*/
	robotic_arm_driveRotVector = robot6axis_driveRotVector4;
	robotic_arm_driveRotDeg = __start.Float+183; /*robot6axis__cn_11*/
	robotic_arm_ownRotDeg = __start.Float+64; /*robot6axis__cn_121*/
	robotic_arm_driveResizeLength = __start.Float+63; /*robot6axis__cn_122*/
	robotic_arm_functionActive = __start.Bool+17; /*robot6axis__cn_123*/
	robotic_arm_armExtrem = __start.Float+184; /*robot6axis__cn_10*/
	robotic_arm_overallArmRotOutput = __start.Float+189; /*robot6axis__cn_9*/
	robotic_arm_productId = __start.Int+7; /*robot6axis__cn_124*/
	_motion_control__robotic_arm_init();

	/*initialize child servo_5 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_5.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_5.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_5.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_5.Char = self.Char - __start.Char;
	servo_status = __start.Int+6; /*robot6axis__cn_125*/
	servo_errorFlag = __start.Int+5; /*robot6axis__cn_126*/
	servo_ActualPositionAx1 = __start.Float+62; /*robot6axis__cn_127*/
	servo_MoveVelDone1 = __start.Bool+16; /*robot6axis__cn_128*/
	servo_ActualVelocity1 = __start.Float+61; /*robot6axis__cn_129*/
	servo_MoveAbsDone1 = __start.Bool+15; /*robot6axis__cn_130*/
	servo_HomeCmd = robot6axis_HomeCmd5;
	servo_MoveVelCmd = robot6axis_MoveVelCmd5;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd5;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd5;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd5;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd5;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd5;
	servo_StopCmd = robot6axis_StopCmd5;
	servo_MovePosition = robot6axis_MovePosition5;
	servo_MoveSpeed = robot6axis_MoveSpeed5;
	servo_MoveAcceleration = robot6axis_MoveAcceleration5;
	servo_MoveDeceleration = robot6axis_MoveDeceleration5;
	servo_offsetAxToMa = robot6axis_offsetAxToMa5;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady5;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved5;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand5;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx5;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa5;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity5;
	servo_physicalPosInit = __start.Float+60; /*robot6axis__cn_131*/
	servo_MAX_SPEED = __start.Float+59; /*robot6axis__cn_132*/
	servo_MAX_ACCEL = __start.Float+58; /*robot6axis__cn_133*/
	servo_MAX_DECEL = __start.Float+57; /*robot6axis__cn_134*/
	servo_MODULO_LENGTH = __start.Float+56; /*robot6axis__cn_135*/
	servo_StatusReady = __start.Bool+14; /*robot6axis__cn_136*/
	servo_StatusMoved = __start.Bool+13; /*robot6axis__cn_137*/
	servo_StatusStand = __start.Bool+12; /*robot6axis__cn_138*/
	servo_ActualPositionAx = __start.Float+195; /*robot6axis__cn_8*/
	servo_ActualPositionMa = __start.Float+55; /*robot6axis__cn_139*/
	servo_ActualVelocity = robot6axis_ActualVelocity5;
	servo_MaximumVelocity = __start.Float+54; /*robot6axis__cn_140*/
	servo_StatusPosIncrease = __start.Bool+11; /*robot6axis__cn_141*/
	servo_StatusPosDecrease = __start.Bool+10; /*robot6axis__cn_142*/
	servo_displayJauge = __start.Float+53; /*robot6axis__cn_143*/
	_motion_control__servo_init();

	/*initialize child arm5 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm5.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm5.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm5.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm5.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+184; /*robot6axis__cn_10*/
	robotic_arm_overallArmQuatInput = __start.Float+189; /*robot6axis__cn_9*/
	robotic_arm_structRotVector = __start.Float+48; /*robot6axis__cn_144*/
	robotic_arm_structRotDeg = __start.Float+47; /*robot6axis__cn_145*/
	robotic_arm_driveRotVector = robot6axis_driveRotVector5;
	robotic_arm_driveRotDeg = __start.Float+195; /*robot6axis__cn_8*/
	robotic_arm_ownRotDeg = __start.Float+46; /*robot6axis__cn_146*/
	robotic_arm_driveResizeLength = __start.Float+45; /*robot6axis__cn_147*/
	robotic_arm_functionActive = __start.Bool+9; /*robot6axis__cn_148*/
	robotic_arm_armExtrem = __start.Float+196; /*robot6axis__cn_7*/
	robotic_arm_overallArmRotOutput = __start.Float+201; /*robot6axis__cn_6*/
	robotic_arm_productId = __start.Int+4; /*robot6axis__cn_149*/
	_motion_control__robotic_arm_init();

	/*initialize child servo_6 (motion_control.servo):*/
	self_num++;
	motion_lib__robot6axis_offset_servo_6.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_servo_6.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_servo_6.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_servo_6.Char = self.Char - __start.Char;
	servo_status = __start.Int+3; /*robot6axis__cn_150*/
	servo_errorFlag = __start.Int+2; /*robot6axis__cn_151*/
	servo_ActualPositionAx1 = __start.Float+44; /*robot6axis__cn_152*/
	servo_MoveVelDone1 = __start.Bool+8; /*robot6axis__cn_153*/
	servo_ActualVelocity1 = __start.Float+43; /*robot6axis__cn_154*/
	servo_MoveAbsDone1 = __start.Bool+7; /*robot6axis__cn_155*/
	servo_HomeCmd = robot6axis_HomeCmd6;
	servo_MoveVelCmd = robot6axis_MoveVelCmd6;
	servo_MoveAbsCmd = robot6axis_MoveAbsCmd6;
	servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd6;
	servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd6;
	servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd6;
	servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd6;
	servo_StopCmd = robot6axis_StopCmd6;
	servo_MovePosition = robot6axis_MovePosition6;
	servo_MoveSpeed = robot6axis_MoveSpeed6;
	servo_MoveAcceleration = robot6axis_MoveAcceleration6;
	servo_MoveDeceleration = robot6axis_MoveDeceleration6;
	servo_offsetAxToMa = robot6axis_offsetAxToMa6;
	servo_PLC_StatusReady = robot6axis_PLC_StatusReady6;
	servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved6;
	servo_PLC_StatusStand = robot6axis_PLC_StatusStand6;
	servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx6;
	servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa6;
	servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity6;
	servo_physicalPosInit = __start.Float+42; /*robot6axis__cn_156*/
	servo_MAX_SPEED = __start.Float+41; /*robot6axis__cn_157*/
	servo_MAX_ACCEL = __start.Float+40; /*robot6axis__cn_158*/
	servo_MAX_DECEL = __start.Float+39; /*robot6axis__cn_159*/
	servo_MODULO_LENGTH = __start.Float+38; /*robot6axis__cn_160*/
	servo_StatusReady = __start.Bool+6; /*robot6axis__cn_161*/
	servo_StatusMoved = __start.Bool+5; /*robot6axis__cn_162*/
	servo_StatusStand = __start.Bool+4; /*robot6axis__cn_163*/
	servo_ActualPositionAx = __start.Float+207; /*robot6axis__cn_5*/
	servo_ActualPositionMa = __start.Float+37; /*robot6axis__cn_164*/
	servo_ActualVelocity = robot6axis_ActualVelocity6;
	servo_MaximumVelocity = __start.Float+36; /*robot6axis__cn_165*/
	servo_StatusPosIncrease = __start.Bool+3; /*robot6axis__cn_166*/
	servo_StatusPosDecrease = __start.Bool+2; /*robot6axis__cn_167*/
	servo_displayJauge = __start.Float+35; /*robot6axis__cn_168*/
	_motion_control__servo_init();

	/*initialize child arm6 (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm6.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm6.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm6.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm6.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+196; /*robot6axis__cn_7*/
	robotic_arm_overallArmQuatInput = __start.Float+201; /*robot6axis__cn_6*/
	robotic_arm_structRotVector = __start.Float+30; /*robot6axis__cn_169*/
	robotic_arm_structRotDeg = __start.Float+29; /*robot6axis__cn_170*/
	robotic_arm_driveRotVector = robot6axis_driveRotVector6;
	robotic_arm_driveRotDeg = __start.Float+207; /*robot6axis__cn_5*/
	robotic_arm_ownRotDeg = __start.Float+28; /*robot6axis__cn_171*/
	robotic_arm_driveResizeLength = __start.Float+27; /*robot6axis__cn_172*/
	robotic_arm_functionActive = __start.Bool+1; /*robot6axis__cn_173*/
	robotic_arm_armExtrem = robot6axis_armExtrem;
	robotic_arm_overallArmRotOutput = __start.Float+208; /*robot6axis__cn_3*/
	robotic_arm_productId = __start.Int+20; /*robot6axis__cn_4*/
	_motion_control__robotic_arm_init();

	/*initialize child function_trigger (motion_lib.trigger_function):*/
	self_num++;
	motion_lib__robot6axis_offset_function_trigger.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_function_trigger.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_function_trigger.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_function_trigger.Char = self.Char - __start.Char;
	trigger_function_armExtrem = robot6axis_armExtrem;
	trigger_function_productId = __start.Int+20; /*robot6axis__cn_4*/
	trigger_function_velX = robot6axis_velX;
	trigger_function_velY = robot6axis_velY;
	trigger_function_velZ = robot6axis_velZ;
	trigger_function_armInStop = robot6axis_armInStop;
	_motion_lib__trigger_function_init();

	/*initialize child arm1RowA (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm1RowA.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm1RowA.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm1RowA.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm1RowA.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = robot6axis_armExtrem;
	robotic_arm_overallArmQuatInput = __start.Float+208; /*robot6axis__cn_3*/
	robotic_arm_structRotVector = robot6axis_structRotVector1RowA;
	robotic_arm_structRotDeg = robot6axis_structRotDeg1RowA;
	robotic_arm_driveRotVector = __start.Float+22; /*robot6axis__cn_174*/
	robotic_arm_driveRotDeg = __start.Float+21; /*robot6axis__cn_175*/
	robotic_arm_ownRotDeg = __start.Float+20; /*robot6axis__cn_176*/
	robotic_arm_driveResizeLength = __start.Float+19; /*robot6axis__cn_177*/
	robotic_arm_functionActive = __start.Bool+0; /*robot6axis__cn_178*/
	robotic_arm_armExtrem = __start.Float+214; /*robot6axis__cn_2*/
	robotic_arm_overallArmRotOutput = __start.Float+219; /*robot6axis__cn_1*/
	robotic_arm_productId = __start.Int+1; /*robot6axis__cn_179*/
	_motion_control__robotic_arm_init();

	/*initialize child arm1RowB (motion_control.robotic_arm):*/
	self_num++;
	motion_lib__robot6axis_offset_arm1RowB.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset_arm1RowB.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset_arm1RowB.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset_arm1RowB.Char = self.Char - __start.Char;
	robotic_arm_armOrigin = __start.Float+214; /*robot6axis__cn_2*/
	robotic_arm_overallArmQuatInput = __start.Float+219; /*robot6axis__cn_1*/
	robotic_arm_structRotVector = robot6axis_structRotVector1RowB;
	robotic_arm_structRotDeg = robot6axis_structRotDeg1RowB;
	robotic_arm_driveRotVector = __start.Float+14; /*robot6axis__cn_180*/
	robotic_arm_driveRotDeg = __start.Float+13; /*robot6axis__cn_181*/
	robotic_arm_ownRotDeg = __start.Float+12; /*robot6axis__cn_182*/
	robotic_arm_driveResizeLength = __start.Float+11; /*robot6axis__cn_183*/
	robotic_arm_functionActive = robot6axis_gripSyringes;
	robotic_arm_armExtrem = __start.Float+6; /*robot6axis__cn_184*/
	robotic_arm_overallArmRotOutput = __start.Float+0; /*robot6axis__cn_185*/
	robotic_arm_productId = __start.Int+0; /*robot6axis__cn_186*/
	_motion_control__robotic_arm_init();

	motion_lib__robot6axis_offset__end.Bool = self.Bool - __start.Bool;
	motion_lib__robot6axis_offset__end.Int = self.Int - __start.Int;
	motion_lib__robot6axis_offset__end.Float = self.Float - __start.Float;
	motion_lib__robot6axis_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int motion_lib__robot6axis(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																																																																																																																																																																																																																																																																																																																																																																				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + motion_lib__robot6axis_offset_servo_1.Bool;
			self.Int = __start.Int + motion_lib__robot6axis_offset_servo_1.Int;
			self.Float = __start.Float + motion_lib__robot6axis_offset_servo_1.Float;
			self.Char = __start.Char + motion_lib__robot6axis_offset_servo_1.Char;

			/************************ servo_1 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+19; /*robot6axis__cn_23*/
				servo_errorFlag = __start.Int+18; /*robot6axis__cn_24*/
				servo_ActualPositionAx1 = __start.Float+135; /*robot6axis__cn_25*/
				servo_MoveVelDone1 = __start.Bool+49; /*robot6axis__cn_26*/
				servo_ActualVelocity1 = __start.Float+134; /*robot6axis__cn_27*/
				servo_MoveAbsDone1 = __start.Bool+48; /*robot6axis__cn_28*/
				servo_HomeCmd = robot6axis_HomeCmd;
				servo_MoveVelCmd = robot6axis_MoveVelCmd;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd;
				servo_StopCmd = robot6axis_StopCmd;
				servo_MovePosition = robot6axis_MovePosition;
				servo_MoveSpeed = robot6axis_MoveSpeed;
				servo_MoveAcceleration = robot6axis_MoveAcceleration;
				servo_MoveDeceleration = robot6axis_MoveDeceleration;
				servo_offsetAxToMa = robot6axis_offsetAxToMa;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity;
				servo_physicalPosInit = __start.Float+133; /*robot6axis__cn_29*/
				servo_MAX_SPEED = __start.Float+132; /*robot6axis__cn_30*/
				servo_MAX_ACCEL = __start.Float+131; /*robot6axis__cn_31*/
				servo_MAX_DECEL = __start.Float+130; /*robot6axis__cn_32*/
				servo_MODULO_LENGTH = __start.Float+129; /*robot6axis__cn_33*/
				servo_StatusReady = __start.Bool+47; /*robot6axis__cn_34*/
				servo_StatusMoved = __start.Bool+46; /*robot6axis__cn_35*/
				servo_StatusStand = __start.Bool+45; /*robot6axis__cn_36*/
				servo_ActualPositionAx = __start.Float+136; /*robot6axis__cn_22*/
				servo_ActualPositionMa = __start.Float+128; /*robot6axis__cn_37*/
				servo_ActualVelocity = robot6axis_ActualVelocity1;
				servo_MaximumVelocity = __start.Float+127; /*robot6axis__cn_38*/
				servo_StatusPosIncrease = __start.Bool+44; /*robot6axis__cn_39*/
				servo_StatusPosDecrease = __start.Bool+43; /*robot6axis__cn_40*/
				servo_displayJauge = __start.Float+126; /*robot6axis__cn_41*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** FOOT execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = robot6axis_armOrigin;
				robotic_arm_overallArmQuatInput = __start.Float+120; /*robot6axis__cn_42*/
				robotic_arm_structRotVector = robot6axis_structRotVectorFOOT;
				robotic_arm_structRotDeg = robot6axis_structRotDegFOOT;
				robotic_arm_driveRotVector = robot6axis_driveRotVector1;
				robotic_arm_driveRotDeg = __start.Float+136; /*robot6axis__cn_22*/
				robotic_arm_ownRotDeg = robot6axis_ownRotDegFOOT;
				robotic_arm_driveResizeLength = __start.Float+119; /*robot6axis__cn_43*/
				robotic_arm_functionActive = __start.Bool+42; /*robot6axis__cn_44*/
				robotic_arm_armExtrem = __start.Float+137; /*robot6axis__cn_21*/
				robotic_arm_overallArmRotOutput = __start.Float+142; /*robot6axis__cn_20*/
				robotic_arm_productId = __start.Int+17; /*robot6axis__cn_45*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* FOOT2 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+137; /*robot6axis__cn_21*/
				robotic_arm_overallArmQuatInput = __start.Float+142; /*robot6axis__cn_20*/
				robotic_arm_structRotVector = robot6axis_structRotVectorFOOT2;
				robotic_arm_structRotDeg = robot6axis_structRotDegFOOT2;
				robotic_arm_driveRotVector = __start.Float+114; /*robot6axis__cn_46*/
				robotic_arm_driveRotDeg = __start.Float+113; /*robot6axis__cn_47*/
				robotic_arm_ownRotDeg = __start.Float+112; /*robot6axis__cn_48*/
				robotic_arm_driveResizeLength = __start.Float+111; /*robot6axis__cn_49*/
				robotic_arm_functionActive = __start.Bool+41; /*robot6axis__cn_50*/
				robotic_arm_armExtrem = __start.Float+148; /*robot6axis__cn_19*/
				robotic_arm_overallArmRotOutput = __start.Float+153; /*robot6axis__cn_18*/
				robotic_arm_productId = __start.Int+16; /*robot6axis__cn_51*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ servo_2 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+15; /*robot6axis__cn_52*/
				servo_errorFlag = __start.Int+14; /*robot6axis__cn_53*/
				servo_ActualPositionAx1 = __start.Float+110; /*robot6axis__cn_54*/
				servo_MoveVelDone1 = __start.Bool+40; /*robot6axis__cn_55*/
				servo_ActualVelocity1 = __start.Float+109; /*robot6axis__cn_56*/
				servo_MoveAbsDone1 = __start.Bool+39; /*robot6axis__cn_57*/
				servo_HomeCmd = robot6axis_HomeCmd2;
				servo_MoveVelCmd = robot6axis_MoveVelCmd2;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd2;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd2;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd2;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd2;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd2;
				servo_StopCmd = robot6axis_StopCmd2;
				servo_MovePosition = robot6axis_MovePosition2;
				servo_MoveSpeed = robot6axis_MoveSpeed2;
				servo_MoveAcceleration = robot6axis_MoveAcceleration2;
				servo_MoveDeceleration = robot6axis_MoveDeceleration2;
				servo_offsetAxToMa = robot6axis_offsetAxToMa2;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady2;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved2;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand2;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx2;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa2;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity2;
				servo_physicalPosInit = __start.Float+108; /*robot6axis__cn_58*/
				servo_MAX_SPEED = __start.Float+107; /*robot6axis__cn_59*/
				servo_MAX_ACCEL = __start.Float+106; /*robot6axis__cn_60*/
				servo_MAX_DECEL = __start.Float+105; /*robot6axis__cn_61*/
				servo_MODULO_LENGTH = __start.Float+104; /*robot6axis__cn_62*/
				servo_StatusReady = __start.Bool+38; /*robot6axis__cn_63*/
				servo_StatusMoved = __start.Bool+37; /*robot6axis__cn_64*/
				servo_StatusStand = __start.Bool+36; /*robot6axis__cn_65*/
				servo_ActualPositionAx = __start.Float+159; /*robot6axis__cn_17*/
				servo_ActualPositionMa = __start.Float+103; /*robot6axis__cn_66*/
				servo_ActualVelocity = robot6axis_ActualVelocity2;
				servo_MaximumVelocity = __start.Float+102; /*robot6axis__cn_67*/
				servo_StatusPosIncrease = __start.Bool+35; /*robot6axis__cn_68*/
				servo_StatusPosDecrease = __start.Bool+34; /*robot6axis__cn_69*/
				servo_displayJauge = __start.Float+101; /*robot6axis__cn_70*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** arm2 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+148; /*robot6axis__cn_19*/
				robotic_arm_overallArmQuatInput = __start.Float+153; /*robot6axis__cn_18*/
				robotic_arm_structRotVector = robot6axis_structRotVectorArm2;
				robotic_arm_structRotDeg = robot6axis_structRotDegArm2;
				robotic_arm_driveRotVector = robot6axis_driveRotVector2;
				robotic_arm_driveRotDeg = __start.Float+159; /*robot6axis__cn_17*/
				robotic_arm_ownRotDeg = __start.Float+100; /*robot6axis__cn_71*/
				robotic_arm_driveResizeLength = __start.Float+99; /*robot6axis__cn_72*/
				robotic_arm_functionActive = __start.Bool+33; /*robot6axis__cn_73*/
				robotic_arm_armExtrem = __start.Float+160; /*robot6axis__cn_16*/
				robotic_arm_overallArmRotOutput = __start.Float+165; /*robot6axis__cn_15*/
				robotic_arm_productId = __start.Int+13; /*robot6axis__cn_74*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ servo_3 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+12; /*robot6axis__cn_75*/
				servo_errorFlag = __start.Int+11; /*robot6axis__cn_76*/
				servo_ActualPositionAx1 = __start.Float+98; /*robot6axis__cn_77*/
				servo_MoveVelDone1 = __start.Bool+32; /*robot6axis__cn_78*/
				servo_ActualVelocity1 = __start.Float+97; /*robot6axis__cn_79*/
				servo_MoveAbsDone1 = __start.Bool+31; /*robot6axis__cn_80*/
				servo_HomeCmd = robot6axis_HomeCmd3;
				servo_MoveVelCmd = robot6axis_MoveVelCmd3;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd3;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd3;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd3;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd3;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd3;
				servo_StopCmd = robot6axis_StopCmd3;
				servo_MovePosition = robot6axis_MovePosition3;
				servo_MoveSpeed = robot6axis_MoveSpeed3;
				servo_MoveAcceleration = robot6axis_MoveAcceleration3;
				servo_MoveDeceleration = robot6axis_MoveDeceleration3;
				servo_offsetAxToMa = robot6axis_offsetAxToMa3;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady3;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved3;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand3;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx3;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa3;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity3;
				servo_physicalPosInit = __start.Float+96; /*robot6axis__cn_81*/
				servo_MAX_SPEED = __start.Float+95; /*robot6axis__cn_82*/
				servo_MAX_ACCEL = __start.Float+94; /*robot6axis__cn_83*/
				servo_MAX_DECEL = __start.Float+93; /*robot6axis__cn_84*/
				servo_MODULO_LENGTH = __start.Float+92; /*robot6axis__cn_85*/
				servo_StatusReady = __start.Bool+30; /*robot6axis__cn_86*/
				servo_StatusMoved = __start.Bool+29; /*robot6axis__cn_87*/
				servo_StatusStand = __start.Bool+28; /*robot6axis__cn_88*/
				servo_ActualPositionAx = __start.Float+171; /*robot6axis__cn_14*/
				servo_ActualPositionMa = __start.Float+91; /*robot6axis__cn_89*/
				servo_ActualVelocity = robot6axis_ActualVelocity3;
				servo_MaximumVelocity = __start.Float+90; /*robot6axis__cn_90*/
				servo_StatusPosIncrease = __start.Bool+27; /*robot6axis__cn_91*/
				servo_StatusPosDecrease = __start.Bool+26; /*robot6axis__cn_92*/
				servo_displayJauge = __start.Float+89; /*robot6axis__cn_93*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** arm3 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+160; /*robot6axis__cn_16*/
				robotic_arm_overallArmQuatInput = __start.Float+165; /*robot6axis__cn_15*/
				robotic_arm_structRotVector = __start.Float+84; /*robot6axis__cn_94*/
				robotic_arm_structRotDeg = __start.Float+83; /*robot6axis__cn_95*/
				robotic_arm_driveRotVector = robot6axis_driveRotVector3;
				robotic_arm_driveRotDeg = __start.Float+171; /*robot6axis__cn_14*/
				robotic_arm_ownRotDeg = __start.Float+82; /*robot6axis__cn_96*/
				robotic_arm_driveResizeLength = __start.Float+81; /*robot6axis__cn_97*/
				robotic_arm_functionActive = __start.Bool+25; /*robot6axis__cn_98*/
				robotic_arm_armExtrem = __start.Float+172; /*robot6axis__cn_13*/
				robotic_arm_overallArmRotOutput = __start.Float+177; /*robot6axis__cn_12*/
				robotic_arm_productId = __start.Int+10; /*robot6axis__cn_99*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ servo_4 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+9; /*robot6axis__cn_100*/
				servo_errorFlag = __start.Int+8; /*robot6axis__cn_101*/
				servo_ActualPositionAx1 = __start.Float+80; /*robot6axis__cn_102*/
				servo_MoveVelDone1 = __start.Bool+24; /*robot6axis__cn_103*/
				servo_ActualVelocity1 = __start.Float+79; /*robot6axis__cn_104*/
				servo_MoveAbsDone1 = __start.Bool+23; /*robot6axis__cn_105*/
				servo_HomeCmd = robot6axis_HomeCmd4;
				servo_MoveVelCmd = robot6axis_MoveVelCmd4;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd4;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd4;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd4;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd4;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd4;
				servo_StopCmd = robot6axis_StopCmd4;
				servo_MovePosition = robot6axis_MovePosition4;
				servo_MoveSpeed = robot6axis_MoveSpeed4;
				servo_MoveAcceleration = robot6axis_MoveAcceleration4;
				servo_MoveDeceleration = robot6axis_MoveDeceleration4;
				servo_offsetAxToMa = robot6axis_offsetAxToMa4;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady4;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved4;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand4;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx4;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa4;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity4;
				servo_physicalPosInit = __start.Float+78; /*robot6axis__cn_106*/
				servo_MAX_SPEED = __start.Float+77; /*robot6axis__cn_107*/
				servo_MAX_ACCEL = __start.Float+76; /*robot6axis__cn_108*/
				servo_MAX_DECEL = __start.Float+75; /*robot6axis__cn_109*/
				servo_MODULO_LENGTH = __start.Float+74; /*robot6axis__cn_110*/
				servo_StatusReady = __start.Bool+22; /*robot6axis__cn_111*/
				servo_StatusMoved = __start.Bool+21; /*robot6axis__cn_112*/
				servo_StatusStand = __start.Bool+20; /*robot6axis__cn_113*/
				servo_ActualPositionAx = __start.Float+183; /*robot6axis__cn_11*/
				servo_ActualPositionMa = __start.Float+73; /*robot6axis__cn_114*/
				servo_ActualVelocity = robot6axis_ActualVelocity4;
				servo_MaximumVelocity = __start.Float+72; /*robot6axis__cn_115*/
				servo_StatusPosIncrease = __start.Bool+19; /*robot6axis__cn_116*/
				servo_StatusPosDecrease = __start.Bool+18; /*robot6axis__cn_117*/
				servo_displayJauge = __start.Float+71; /*robot6axis__cn_118*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** arm4 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+172; /*robot6axis__cn_13*/
				robotic_arm_overallArmQuatInput = __start.Float+177; /*robot6axis__cn_12*/
				robotic_arm_structRotVector = __start.Float+66; /*robot6axis__cn_119*/
				robotic_arm_structRotDeg = __start.Float+65; /*robot6axis__cn_120*/
				robotic_arm_driveRotVector = robot6axis_driveRotVector4;
				robotic_arm_driveRotDeg = __start.Float+183; /*robot6axis__cn_11*/
				robotic_arm_ownRotDeg = __start.Float+64; /*robot6axis__cn_121*/
				robotic_arm_driveResizeLength = __start.Float+63; /*robot6axis__cn_122*/
				robotic_arm_functionActive = __start.Bool+17; /*robot6axis__cn_123*/
				robotic_arm_armExtrem = __start.Float+184; /*robot6axis__cn_10*/
				robotic_arm_overallArmRotOutput = __start.Float+189; /*robot6axis__cn_9*/
				robotic_arm_productId = __start.Int+7; /*robot6axis__cn_124*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ servo_5 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+6; /*robot6axis__cn_125*/
				servo_errorFlag = __start.Int+5; /*robot6axis__cn_126*/
				servo_ActualPositionAx1 = __start.Float+62; /*robot6axis__cn_127*/
				servo_MoveVelDone1 = __start.Bool+16; /*robot6axis__cn_128*/
				servo_ActualVelocity1 = __start.Float+61; /*robot6axis__cn_129*/
				servo_MoveAbsDone1 = __start.Bool+15; /*robot6axis__cn_130*/
				servo_HomeCmd = robot6axis_HomeCmd5;
				servo_MoveVelCmd = robot6axis_MoveVelCmd5;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd5;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd5;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd5;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd5;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd5;
				servo_StopCmd = robot6axis_StopCmd5;
				servo_MovePosition = robot6axis_MovePosition5;
				servo_MoveSpeed = robot6axis_MoveSpeed5;
				servo_MoveAcceleration = robot6axis_MoveAcceleration5;
				servo_MoveDeceleration = robot6axis_MoveDeceleration5;
				servo_offsetAxToMa = robot6axis_offsetAxToMa5;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady5;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved5;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand5;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx5;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa5;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity5;
				servo_physicalPosInit = __start.Float+60; /*robot6axis__cn_131*/
				servo_MAX_SPEED = __start.Float+59; /*robot6axis__cn_132*/
				servo_MAX_ACCEL = __start.Float+58; /*robot6axis__cn_133*/
				servo_MAX_DECEL = __start.Float+57; /*robot6axis__cn_134*/
				servo_MODULO_LENGTH = __start.Float+56; /*robot6axis__cn_135*/
				servo_StatusReady = __start.Bool+14; /*robot6axis__cn_136*/
				servo_StatusMoved = __start.Bool+13; /*robot6axis__cn_137*/
				servo_StatusStand = __start.Bool+12; /*robot6axis__cn_138*/
				servo_ActualPositionAx = __start.Float+195; /*robot6axis__cn_8*/
				servo_ActualPositionMa = __start.Float+55; /*robot6axis__cn_139*/
				servo_ActualVelocity = robot6axis_ActualVelocity5;
				servo_MaximumVelocity = __start.Float+54; /*robot6axis__cn_140*/
				servo_StatusPosIncrease = __start.Bool+11; /*robot6axis__cn_141*/
				servo_StatusPosDecrease = __start.Bool+10; /*robot6axis__cn_142*/
				servo_displayJauge = __start.Float+53; /*robot6axis__cn_143*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** arm5 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+184; /*robot6axis__cn_10*/
				robotic_arm_overallArmQuatInput = __start.Float+189; /*robot6axis__cn_9*/
				robotic_arm_structRotVector = __start.Float+48; /*robot6axis__cn_144*/
				robotic_arm_structRotDeg = __start.Float+47; /*robot6axis__cn_145*/
				robotic_arm_driveRotVector = robot6axis_driveRotVector5;
				robotic_arm_driveRotDeg = __start.Float+195; /*robot6axis__cn_8*/
				robotic_arm_ownRotDeg = __start.Float+46; /*robot6axis__cn_146*/
				robotic_arm_driveResizeLength = __start.Float+45; /*robot6axis__cn_147*/
				robotic_arm_functionActive = __start.Bool+9; /*robot6axis__cn_148*/
				robotic_arm_armExtrem = __start.Float+196; /*robot6axis__cn_7*/
				robotic_arm_overallArmRotOutput = __start.Float+201; /*robot6axis__cn_6*/
				robotic_arm_productId = __start.Int+4; /*robot6axis__cn_149*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ servo_6 execution *************************/

			self_num++;
			if (servo__num != self_num) {
				servo__num = self_num;
				servo_status = __start.Int+3; /*robot6axis__cn_150*/
				servo_errorFlag = __start.Int+2; /*robot6axis__cn_151*/
				servo_ActualPositionAx1 = __start.Float+44; /*robot6axis__cn_152*/
				servo_MoveVelDone1 = __start.Bool+8; /*robot6axis__cn_153*/
				servo_ActualVelocity1 = __start.Float+43; /*robot6axis__cn_154*/
				servo_MoveAbsDone1 = __start.Bool+7; /*robot6axis__cn_155*/
				servo_HomeCmd = robot6axis_HomeCmd6;
				servo_MoveVelCmd = robot6axis_MoveVelCmd6;
				servo_MoveAbsCmd = robot6axis_MoveAbsCmd6;
				servo_MoveVel1ManualCmd = robot6axis_MoveVel1ManualCmd6;
				servo_MoveVel2ManualCmd = robot6axis_MoveVel2ManualCmd6;
				servo_MoveAbs1ManualCmd = robot6axis_MoveAbs1ManualCmd6;
				servo_MoveAbs2ManualCmd = robot6axis_MoveAbs2ManualCmd6;
				servo_StopCmd = robot6axis_StopCmd6;
				servo_MovePosition = robot6axis_MovePosition6;
				servo_MoveSpeed = robot6axis_MoveSpeed6;
				servo_MoveAcceleration = robot6axis_MoveAcceleration6;
				servo_MoveDeceleration = robot6axis_MoveDeceleration6;
				servo_offsetAxToMa = robot6axis_offsetAxToMa6;
				servo_PLC_StatusReady = robot6axis_PLC_StatusReady6;
				servo_PLC_StatusMoved = robot6axis_PLC_StatusMoved6;
				servo_PLC_StatusStand = robot6axis_PLC_StatusStand6;
				servo_PLC_ActualPositionAx = robot6axis_PLC_ActualPositionAx6;
				servo_PLC_ActualPositionMa = robot6axis_PLC_ActualPositionMa6;
				servo_PLC_ActualVelocity = robot6axis_PLC_ActualVelocity6;
				servo_physicalPosInit = __start.Float+42; /*robot6axis__cn_156*/
				servo_MAX_SPEED = __start.Float+41; /*robot6axis__cn_157*/
				servo_MAX_ACCEL = __start.Float+40; /*robot6axis__cn_158*/
				servo_MAX_DECEL = __start.Float+39; /*robot6axis__cn_159*/
				servo_MODULO_LENGTH = __start.Float+38; /*robot6axis__cn_160*/
				servo_StatusReady = __start.Bool+6; /*robot6axis__cn_161*/
				servo_StatusMoved = __start.Bool+5; /*robot6axis__cn_162*/
				servo_StatusStand = __start.Bool+4; /*robot6axis__cn_163*/
				servo_ActualPositionAx = __start.Float+207; /*robot6axis__cn_5*/
				servo_ActualPositionMa = __start.Float+37; /*robot6axis__cn_164*/
				servo_ActualVelocity = robot6axis_ActualVelocity6;
				servo_MaximumVelocity = __start.Float+36; /*robot6axis__cn_165*/
				servo_StatusPosIncrease = __start.Bool+3; /*robot6axis__cn_166*/
				servo_StatusPosDecrease = __start.Bool+2; /*robot6axis__cn_167*/
				servo_displayJauge = __start.Float+35; /*robot6axis__cn_168*/
			}
			__ret = motion_control__servo();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** arm6 execution **************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+196; /*robot6axis__cn_7*/
				robotic_arm_overallArmQuatInput = __start.Float+201; /*robot6axis__cn_6*/
				robotic_arm_structRotVector = __start.Float+30; /*robot6axis__cn_169*/
				robotic_arm_structRotDeg = __start.Float+29; /*robot6axis__cn_170*/
				robotic_arm_driveRotVector = robot6axis_driveRotVector6;
				robotic_arm_driveRotDeg = __start.Float+207; /*robot6axis__cn_5*/
				robotic_arm_ownRotDeg = __start.Float+28; /*robot6axis__cn_171*/
				robotic_arm_driveResizeLength = __start.Float+27; /*robot6axis__cn_172*/
				robotic_arm_functionActive = __start.Bool+1; /*robot6axis__cn_173*/
				robotic_arm_armExtrem = robot6axis_armExtrem;
				robotic_arm_overallArmRotOutput = __start.Float+208; /*robot6axis__cn_3*/
				robotic_arm_productId = __start.Int+20; /*robot6axis__cn_4*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** function_trigger execution ********************/

			self_num++;
			if (trigger_function__num != self_num) {
				trigger_function__num = self_num;
				trigger_function_armExtrem = robot6axis_armExtrem;
				trigger_function_productId = __start.Int+20; /*robot6axis__cn_4*/
				trigger_function_velX = robot6axis_velX;
				trigger_function_velY = robot6axis_velY;
				trigger_function_velZ = robot6axis_velZ;
				trigger_function_armInStop = robot6axis_armInStop;
			}
			__ret = motion_lib__trigger_function();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ arm1RowA execution ************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = robot6axis_armExtrem;
				robotic_arm_overallArmQuatInput = __start.Float+208; /*robot6axis__cn_3*/
				robotic_arm_structRotVector = robot6axis_structRotVector1RowA;
				robotic_arm_structRotDeg = robot6axis_structRotDeg1RowA;
				robotic_arm_driveRotVector = __start.Float+22; /*robot6axis__cn_174*/
				robotic_arm_driveRotDeg = __start.Float+21; /*robot6axis__cn_175*/
				robotic_arm_ownRotDeg = __start.Float+20; /*robot6axis__cn_176*/
				robotic_arm_driveResizeLength = __start.Float+19; /*robot6axis__cn_177*/
				robotic_arm_functionActive = __start.Bool+0; /*robot6axis__cn_178*/
				robotic_arm_armExtrem = __start.Float+214; /*robot6axis__cn_2*/
				robotic_arm_overallArmRotOutput = __start.Float+219; /*robot6axis__cn_1*/
				robotic_arm_productId = __start.Int+1; /*robot6axis__cn_179*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ arm1RowB execution ************************/

			self_num++;
			if (robotic_arm__num != self_num) {
				robotic_arm__num = self_num;
				robotic_arm_armOrigin = __start.Float+214; /*robot6axis__cn_2*/
				robotic_arm_overallArmQuatInput = __start.Float+219; /*robot6axis__cn_1*/
				robotic_arm_structRotVector = robot6axis_structRotVector1RowB;
				robotic_arm_structRotDeg = robot6axis_structRotDeg1RowB;
				robotic_arm_driveRotVector = __start.Float+14; /*robot6axis__cn_180*/
				robotic_arm_driveRotDeg = __start.Float+13; /*robot6axis__cn_181*/
				robotic_arm_ownRotDeg = __start.Float+12; /*robot6axis__cn_182*/
				robotic_arm_driveResizeLength = __start.Float+11; /*robot6axis__cn_183*/
				robotic_arm_functionActive = robot6axis_gripSyringes;
				robotic_arm_armExtrem = __start.Float+6; /*robot6axis__cn_184*/
				robotic_arm_overallArmRotOutput = __start.Float+0; /*robot6axis__cn_185*/
				robotic_arm_productId = __start.Int+0; /*robot6axis__cn_186*/
			}
			__ret = motion_control__robotic_arm();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + motion_lib__robot6axis_offset__end.Bool;
	self.Int = __start.Int + motion_lib__robot6axis_offset__end.Int;
	self.Float = __start.Float + motion_lib__robot6axis_offset__end.Float;
	self.Char = __start.Char + motion_lib__robot6axis_offset__end.Char;

	return 0;
}

