/*2023-10-04T11:03:56-01:00*/

/********************************************************************
 * robotic_arm.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__ROBOTIC_ARM_H
#define _MOTION_CONTROL__ROBOTIC_ARM_H


/********************** Variable declarations ***********************/

extern CB_Index robotic_arm__num;
extern CB_Mem_Float *robotic_arm_armOrigin;
extern CB_Mem_Float *robotic_arm_overallArmQuatInput;
extern CB_Mem_Float *robotic_arm_structRotVector;
extern CB_Mem_Float *robotic_arm_structRotDeg;
extern CB_Mem_Float *robotic_arm_driveRotVector;
extern CB_Mem_Float *robotic_arm_driveRotDeg;
extern CB_Mem_Float *robotic_arm_ownRotDeg;
extern CB_Mem_Float *robotic_arm_driveResizeLength;
extern CB_Mem_Bool *robotic_arm_functionActive;
extern CB_Mem_Float *robotic_arm_armExtrem;
extern CB_Mem_Float *robotic_arm_overallArmRotOutput;
extern CB_Mem_Int *robotic_arm_productId;
extern CB_Mem_Int *robotic_arm_status_act_prod;
extern CB_Mem_Float *robotic_arm_m11;
extern CB_Mem_Float *robotic_arm_m12;
extern CB_Mem_Float *robotic_arm_m13;
extern CB_Mem_Float *robotic_arm_m14;
extern CB_Mem_Float *robotic_arm_m21;
extern CB_Mem_Float *robotic_arm_m22;
extern CB_Mem_Float *robotic_arm_m23;
extern CB_Mem_Float *robotic_arm_m24;
extern CB_Mem_Float *robotic_arm_m31;
extern CB_Mem_Float *robotic_arm_m32;
extern CB_Mem_Float *robotic_arm_m33;
extern CB_Mem_Float *robotic_arm_m34;
extern CB_Mem_Float *robotic_arm_m41;
extern CB_Mem_Float *robotic_arm_m42;
extern CB_Mem_Float *robotic_arm_m43;
extern CB_Mem_Float *robotic_arm_m44;
extern CB_Mem_Float *robotic_arm_armLengthCalc;
extern CB_Mem_Bool *robotic_arm_functionActiveLocale;
extern CB_Mem_Int *robotic_arm_product_id;
extern CB_Mem_Int *robotic_arm_arm_id;
extern CB_Mem_Float *robotic_arm_timeToGripParam;
extern CB_Mem_Float *robotic_arm_armLength;
extern CB_Mem_Float *robotic_arm_armWidth;
extern CB_Mem_Float *robotic_arm_armHeight;
extern CB_Mem_Int *robotic_arm_armType;

/********************** Function declarations ***********************/

extern int _motion_control__robotic_arm_init(void);
extern int motion_control__robotic_arm(void);

/************************** Access macros ***************************/

#define mx_acces_motion_control__robotic_arm__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_control__robotic_arm__m11 Float[0].CB_current_value
#define mx_acces_motion_control__robotic_arm__m12 Float[1].CB_current_value
#define mx_acces_motion_control__robotic_arm__m13 Float[2].CB_current_value
#define mx_acces_motion_control__robotic_arm__m14 Float[3].CB_current_value
#define mx_acces_motion_control__robotic_arm__m21 Float[4].CB_current_value
#define mx_acces_motion_control__robotic_arm__m22 Float[5].CB_current_value
#define mx_acces_motion_control__robotic_arm__m23 Float[6].CB_current_value
#define mx_acces_motion_control__robotic_arm__m24 Float[7].CB_current_value
#define mx_acces_motion_control__robotic_arm__m31 Float[8].CB_current_value
#define mx_acces_motion_control__robotic_arm__m32 Float[9].CB_current_value
#define mx_acces_motion_control__robotic_arm__m33 Float[10].CB_current_value
#define mx_acces_motion_control__robotic_arm__m34 Float[11].CB_current_value
#define mx_acces_motion_control__robotic_arm__m41 Float[12].CB_current_value
#define mx_acces_motion_control__robotic_arm__m42 Float[13].CB_current_value
#define mx_acces_motion_control__robotic_arm__m43 Float[14].CB_current_value
#define mx_acces_motion_control__robotic_arm__m44 Float[15].CB_current_value
#define mx_acces_motion_control__robotic_arm__armLengthCalc Float[16].CB_current_value
#define mx_acces_motion_control__robotic_arm__functionActiveLocale Bool[0].CB_current_value
#define mx_acces_motion_control__robotic_arm__product_id Int[1].CB_current_value
#define mx_acces_motion_control__robotic_arm__arm_id Int[2].CB_current_value
#define mx_acces_motion_control__robotic_arm__timeToGripParam Float[17].CB_current_value
#define mx_acces_motion_control__robotic_arm__armLength Float[18].CB_current_value
#define mx_acces_motion_control__robotic_arm__armWidth Float[19].CB_current_value
#define mx_acces_motion_control__robotic_arm__armHeight Float[20].CB_current_value
#define mx_acces_motion_control__robotic_arm__armType Int[3].CB_current_value

#endif /*_MOTION_CONTROL__ROBOTIC_ARM_H*/
