/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * modemanagement.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "modemanagement.h"


/**************************** Variables *****************************/

CB_Index modemanagement__num = 0;
CB_Mem_Bool *modemanagement_bpStart;
CB_Mem_Bool *modemanagement_bpAuto;
CB_Mem_Bool *modemanagement_bpManu;
CB_Mem_Bool *modemanagement_bpEmergencyStop;
CB_Mem_Bool *modemanagement_bpStop;
CB_Mem_Bool *modemanagement_Auto;
CB_Mem_Bool *modemanagement_Manu;
CB_Mem_Bool *modemanagement_run;
CB_Mem_Bool *modemanagement_rs1_Q1;
CB_Mem_Int *modemanagement_rs1_i_rs;

/**************************** Variables *****************************/

#define bpStart (modemanagement_bpStart->CB_current_value)
#define bpAuto (modemanagement_bpAuto->CB_current_value)
#define bpManu (modemanagement_bpManu->CB_current_value)
#define bpEmergencyStop (modemanagement_bpEmergencyStop->CB_current_value)
#define bpStop (modemanagement_bpStop->CB_current_value)
#define Auto (modemanagement_Auto->CB_current_value)
#define Manu (modemanagement_Manu->CB_current_value)
#define run (modemanagement_run->CB_current_value)
#define rs1_Q1 (modemanagement_rs1_Q1->CB_current_value)
#define rs1_i_rs (*((short *)&(modemanagement_rs1_i_rs->CB_current_value) + ALIGN_OFFSET_SHORT))


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _flask_motion_app__modemanagement_init(void)
{
	self.Bool+=1;
	self.Int+=1;


	return 0;
}


/************************ Behavior function *************************/

int flask_motion_app__modemanagement(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		modemanagement_rs1_Q1 = self.Bool+0;
		modemanagement_rs1_i_rs = self.Int+0;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			Auto = bpAuto && (!bpManu && !bpEmergencyStop);
			Manu = bpManu && (!bpAuto && !bpEmergencyStop);
			rs1_Q1 = rs_Q1(bpStart && (Auto && !bpStop), bpStop || !Auto, &rs1_i_rs);
			run = rs1_Q1;
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(modemanagement_Auto);
		CB_post_bool(modemanagement_Manu);
		CB_post_bool(modemanagement_run);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 1;
	self.Int += 1;

	return 0;
}

