/*2024-04-22T17:52:18-01:00*/

/********************************************************************
 * modemanagement.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _FLASK_MOTION_APP__MODEMANAGEMENT_H
#define _FLASK_MOTION_APP__MODEMANAGEMENT_H


/********************** Variable declarations ***********************/

extern CB_Index modemanagement__num;
extern CB_Mem_Bool *modemanagement_bpStart;
extern CB_Mem_Bool *modemanagement_bpAuto;
extern CB_Mem_Bool *modemanagement_bpManu;
extern CB_Mem_Bool *modemanagement_bpEmergencyStop;
extern CB_Mem_Bool *modemanagement_bpStop;
extern CB_Mem_Bool *modemanagement_Auto;
extern CB_Mem_Bool *modemanagement_Manu;
extern CB_Mem_Bool *modemanagement_run;

/********************** Function declarations ***********************/

extern int _flask_motion_app__modemanagement_init(void);
extern int flask_motion_app__modemanagement(void);

#endif /*_FLASK_MOTION_APP__MODEMANAGEMENT_H*/
