/*2023-10-04T11:03:57-01:00*/

/********************************************************************
 * product_creator.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"
#include "cb_products_iec.h"

#include "product_creator.h"

#include "motion_control/functional/product/product.h"


/**************************** Variables *****************************/

CB_Index product_creator__num = 0;
CB_Mem_Int *product_creator_status_act_prod;
CB_Mem_Float *product_creator_m11;
CB_Mem_Float *product_creator_m12;
CB_Mem_Float *product_creator_m13;
CB_Mem_Float *product_creator_m14;
CB_Mem_Float *product_creator_m21;
CB_Mem_Float *product_creator_m22;
CB_Mem_Float *product_creator_m23;
CB_Mem_Float *product_creator_m24;
CB_Mem_Float *product_creator_m31;
CB_Mem_Float *product_creator_m32;
CB_Mem_Float *product_creator_m33;
CB_Mem_Float *product_creator_m34;
CB_Mem_Float *product_creator_m41;
CB_Mem_Float *product_creator_m42;
CB_Mem_Float *product_creator_m43;
CB_Mem_Float *product_creator_m44;
CB_Mem_Bool *product_creator_pbCreation;
CB_Mem_Bool *product_creator_productPresence;
CB_Mem_Int *product_creator_idProd;
CB_Mem_Int *product_creator_cntProd;
CB_Mem_Float *product_creator_waitingTime;
CB_Mem_Int *product_creator_oldIdProd;
CB_Mem_Bool *product_creator_empty1;
CB_Mem_Bool *product_creator_empty2;
CB_Mem_Bool *product_creator_empty3;
CB_Mem_Bool *product_creator_empty4;
CB_Mem_Bool *product_creator_empty5;
CB_Mem_Bool *product_creator_empty6;
CB_Mem_Bool *product_creator_empty7;
CB_Mem_Bool *product_creator_empty8;
CB_Mem_Float *product_creator_gravitySpeed;
CB_Mem_Int *product_creator_nbProdToCreate;
CB_Mem_Bool *product_creator_pulsedMode;
CB_Mem_Float *product_creator_pulseTime;
CB_Mem_Bool *product_creator_alignProductsToZ;
CB_Mem_Bool *product_creator_alignProductsToY;
CB_Mem_Bool *product_creator_alignProductsToX;

/**************************** Variables *****************************/

#define status_act_prod (product_creator_status_act_prod->CB_current_value)
#define m11 (product_creator_m11->CB_current_value)
#define m12 (product_creator_m12->CB_current_value)
#define m13 (product_creator_m13->CB_current_value)
#define m14 (product_creator_m14->CB_current_value)
#define m21 (product_creator_m21->CB_current_value)
#define m22 (product_creator_m22->CB_current_value)
#define m23 (product_creator_m23->CB_current_value)
#define m24 (product_creator_m24->CB_current_value)
#define m31 (product_creator_m31->CB_current_value)
#define m32 (product_creator_m32->CB_current_value)
#define m33 (product_creator_m33->CB_current_value)
#define m34 (product_creator_m34->CB_current_value)
#define m41 (product_creator_m41->CB_current_value)
#define m42 (product_creator_m42->CB_current_value)
#define m43 (product_creator_m43->CB_current_value)
#define m44 (product_creator_m44->CB_current_value)
#define pbCreation (product_creator_pbCreation->CB_current_value)
#define productPresence (product_creator_productPresence->CB_current_value)
#define idProd (product_creator_idProd->CB_current_value)
#define cntProd (product_creator_cntProd->CB_current_value)
#define waitingTime (product_creator_waitingTime->CB_current_value)
#define oldIdProd (product_creator_oldIdProd->CB_current_value)
#define empty1 (product_creator_empty1->CB_current_value)
#define empty2 (product_creator_empty2->CB_current_value)
#define empty3 (product_creator_empty3->CB_current_value)
#define empty4 (product_creator_empty4->CB_current_value)
#define empty5 (product_creator_empty5->CB_current_value)
#define empty6 (product_creator_empty6->CB_current_value)
#define empty7 (product_creator_empty7->CB_current_value)
#define empty8 (product_creator_empty8->CB_current_value)
#define gravitySpeed (product_creator_gravitySpeed->CB_current_value)
#define nbProdToCreate (*((short *)&(product_creator_nbProdToCreate->CB_current_value) + ALIGN_OFFSET_SHORT))
#define pulsedMode (product_creator_pulsedMode->CB_current_value)
#define pulseTime (product_creator_pulseTime->CB_current_value)
#define alignProductsToZ (product_creator_alignProductsToZ->CB_current_value)
#define alignProductsToY (product_creator_alignProductsToY->CB_current_value)
#define alignProductsToX (product_creator_alignProductsToX->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_control__product_creator_init(void)
{
	(self.Float+0)->CB_current_value = 1.0; /*m11*/
	(self.Float+5)->CB_current_value = 1.0; /*m22*/
	(self.Float+10)->CB_current_value = 1.0; /*m33*/
	(self.Float+15)->CB_current_value = 1.0; /*m44*/
	(self.Float+16)->CB_current_value = 10.0; /*waitingTime*/
	(self.Float+17)->CB_current_value = 0.1; /*gravitySpeed*/
	*((short *)&((self.Int+4)->CB_current_value) + ALIGN_OFFSET_SHORT) = 1; /*nbProdToCreate*/
	(self.Bool+10)->CB_current_value = 1; /*pulsedMode*/
	(self.Float+18)->CB_current_value = 10.0; /*pulseTime*/
	(self.Bool+11)->CB_current_value = 1; /*alignProductsToZ*/
	self.Bool+=14;
	self.Int+=5;
	self.Float+=19;


	return 0;
}


/************************ Behavior function *************************/

int motion_control__product_creator(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		product_creator_status_act_prod = self.Int+0;
		product_creator_m11 = self.Float+0;
		product_creator_m12 = self.Float+1;
		product_creator_m13 = self.Float+2;
		product_creator_m14 = self.Float+3;
		product_creator_m21 = self.Float+4;
		product_creator_m22 = self.Float+5;
		product_creator_m23 = self.Float+6;
		product_creator_m24 = self.Float+7;
		product_creator_m31 = self.Float+8;
		product_creator_m32 = self.Float+9;
		product_creator_m33 = self.Float+10;
		product_creator_m34 = self.Float+11;
		product_creator_m41 = self.Float+12;
		product_creator_m42 = self.Float+13;
		product_creator_m43 = self.Float+14;
		product_creator_m44 = self.Float+15;
		product_creator_pbCreation = self.Bool+0;
		product_creator_productPresence = self.Bool+1;
		product_creator_idProd = self.Int+1;
		product_creator_cntProd = self.Int+2;
		product_creator_waitingTime = self.Float+16;
		product_creator_oldIdProd = self.Int+3;
		product_creator_empty1 = self.Bool+2;
		product_creator_empty2 = self.Bool+3;
		product_creator_empty3 = self.Bool+4;
		product_creator_empty4 = self.Bool+5;
		product_creator_empty5 = self.Bool+6;
		product_creator_empty6 = self.Bool+7;
		product_creator_empty7 = self.Bool+8;
		product_creator_empty8 = self.Bool+9;
		product_creator_gravitySpeed = self.Float+17;
		product_creator_nbProdToCreate = self.Int+4;
		product_creator_pulsedMode = self.Bool+10;
		product_creator_pulseTime = self.Float+18;
		product_creator_alignProductsToZ = self.Bool+11;
		product_creator_alignProductsToY = self.Bool+12;
		product_creator_alignProductsToX = self.Bool+13;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Actor Myself init *************************/

		setMyselfFor(self_num);

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Actors and Products						*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2021							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates the creation of products.			*/
			/* The creation can be :							*/
			/* - pulsed									*/
			/* - automatic and cyclic							*/
			/* ----------------------------------------------------------------	*/


			int i;
			 
			if (!  pulsedMode) {
				waitingTime += CLOCK_PERIOD / 1000000.0;
				if (productPresence) waitingTime = 0.0;
			}

			/* ----------------------------------------------------------------	*/
			/* Request for creation of a product at the same location that the	*/
			/* creation module.								*/
			/* To avoid inopportune stacking, the creation of a new product is	*/
			/* forbidden when there is already one in the creation area.		*/
			/* ----------------------------------------------------------------	*/

			if ((pbCreation ||  ((waitingTime>= pulseTime) && ! pulsedMode)) && ! productPresence) {
				waitingTime = 0.0;
				for (i=0;i<nbProdToCreate;i++) {
					if (alignProductsToX) {
						idProd=prodNew(motion_control__product, getPositionX(myself), getPositionY(myself), getPositionZ(myself), getSizeX(myself)/2.0, getSizeY(myself), getSizeZ(myself));
						if (idProd >= 0)
							rotateTo(idProd, getAngleX(myself), getAngleY(myself), getAngleZ(myself), getPositionX(idProd), getPositionY(idProd),getPositionZ(idProd));
						if (i>0) moveRelativeAnotherXBy(idProd, oldIdProd , (getSizeX(myself)*i));

						oldIdProd = idProd;
					}

					if (alignProductsToY) {
						idProd=prodNew(motion_control__product, getPositionX(myself), getPositionY(myself), getPositionZ(myself), getSizeX(myself)/2.0, getSizeY(myself), getSizeZ(myself));
						if (idProd >= 0)
							rotateTo(idProd, getAngleX(myself), getAngleY(myself), getAngleZ(myself), getPositionX(idProd), getPositionY(idProd),getPositionZ(idProd));
						if (i>0) moveRelativeAnotherYBy(idProd, oldIdProd , (getSizeY(myself)*i));
						oldIdProd = idProd;
					}
					if (alignProductsToZ) {
						idProd=prodNew(motion_control__product, getPositionX(myself), getPositionY(myself), getPositionZ(myself)+(getSizeZ(myself)*i), getSizeX(myself)/2.0, getSizeY(myself), getSizeZ(myself));
						if (idProd >= 0)
							rotateTo(idProd, getAngleX(myself), getAngleY(myself), getAngleZ(myself), getPositionX(idProd), getPositionY(idProd),getPositionZ(idProd));
					}
					
					if (idProd >= 0) {
						cntProd++;
						var(idProd, motion_control__product__gravitySpeed ) = gravitySpeed;
						var(idProd, motion_control__product__number ) = cntProd;
						var(idProd, motion_control__product__empty1 ) = empty1 ;
						var(idProd, motion_control__product__empty2 ) = empty2 ;
						var(idProd, motion_control__product__empty3 ) = empty3 ;
						var(idProd, motion_control__product__empty4 ) = empty4 ;
						var(idProd, motion_control__product__empty5 ) = empty5 ;
						var(idProd, motion_control__product__empty6 ) = empty6 ;
						var(idProd, motion_control__product__empty7 ) = empty7 ;
						var(idProd, motion_control__product__empty8 ) = empty8 ;
					}
				}
			}


			/* ----------------------------------------------------------------	*/
			/* Reset information on product presence					*/
			/* ----------------------------------------------------------------	*/
			productPresence=0;

			/* ----------------------------------------------------------------	*/
			/* Reset of the manual request for creation				*/
			/* ----------------------------------------------------------------	*/
			pbCreation=0;
		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 14;
	self.Int += 5;
	self.Float += 19;

	return 0;
}

