/*2023-10-04T11:03:57-01:00*/

/********************************************************************
 * product_creator.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__PRODUCT_CREATOR_H
#define _MOTION_CONTROL__PRODUCT_CREATOR_H


/********************** Variable declarations ***********************/

extern CB_Index product_creator__num;
extern CB_Mem_Int *product_creator_status_act_prod;
extern CB_Mem_Float *product_creator_m11;
extern CB_Mem_Float *product_creator_m12;
extern CB_Mem_Float *product_creator_m13;
extern CB_Mem_Float *product_creator_m14;
extern CB_Mem_Float *product_creator_m21;
extern CB_Mem_Float *product_creator_m22;
extern CB_Mem_Float *product_creator_m23;
extern CB_Mem_Float *product_creator_m24;
extern CB_Mem_Float *product_creator_m31;
extern CB_Mem_Float *product_creator_m32;
extern CB_Mem_Float *product_creator_m33;
extern CB_Mem_Float *product_creator_m34;
extern CB_Mem_Float *product_creator_m41;
extern CB_Mem_Float *product_creator_m42;
extern CB_Mem_Float *product_creator_m43;
extern CB_Mem_Float *product_creator_m44;
extern CB_Mem_Bool *product_creator_pbCreation;
extern CB_Mem_Bool *product_creator_productPresence;
extern CB_Mem_Int *product_creator_idProd;
extern CB_Mem_Int *product_creator_cntProd;
extern CB_Mem_Float *product_creator_waitingTime;
extern CB_Mem_Int *product_creator_oldIdProd;
extern CB_Mem_Bool *product_creator_empty1;
extern CB_Mem_Bool *product_creator_empty2;
extern CB_Mem_Bool *product_creator_empty3;
extern CB_Mem_Bool *product_creator_empty4;
extern CB_Mem_Bool *product_creator_empty5;
extern CB_Mem_Bool *product_creator_empty6;
extern CB_Mem_Bool *product_creator_empty7;
extern CB_Mem_Bool *product_creator_empty8;
extern CB_Mem_Float *product_creator_gravitySpeed;
extern CB_Mem_Int *product_creator_nbProdToCreate;
extern CB_Mem_Bool *product_creator_pulsedMode;
extern CB_Mem_Float *product_creator_pulseTime;
extern CB_Mem_Bool *product_creator_alignProductsToZ;
extern CB_Mem_Bool *product_creator_alignProductsToY;
extern CB_Mem_Bool *product_creator_alignProductsToX;

/********************** Function declarations ***********************/

extern int _motion_control__product_creator_init(void);
extern int motion_control__product_creator(void);

/************************** Access macros ***************************/

#define mx_acces_motion_control__product_creator__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_control__product_creator__m11 Float[0].CB_current_value
#define mx_acces_motion_control__product_creator__m12 Float[1].CB_current_value
#define mx_acces_motion_control__product_creator__m13 Float[2].CB_current_value
#define mx_acces_motion_control__product_creator__m14 Float[3].CB_current_value
#define mx_acces_motion_control__product_creator__m21 Float[4].CB_current_value
#define mx_acces_motion_control__product_creator__m22 Float[5].CB_current_value
#define mx_acces_motion_control__product_creator__m23 Float[6].CB_current_value
#define mx_acces_motion_control__product_creator__m24 Float[7].CB_current_value
#define mx_acces_motion_control__product_creator__m31 Float[8].CB_current_value
#define mx_acces_motion_control__product_creator__m32 Float[9].CB_current_value
#define mx_acces_motion_control__product_creator__m33 Float[10].CB_current_value
#define mx_acces_motion_control__product_creator__m34 Float[11].CB_current_value
#define mx_acces_motion_control__product_creator__m41 Float[12].CB_current_value
#define mx_acces_motion_control__product_creator__m42 Float[13].CB_current_value
#define mx_acces_motion_control__product_creator__m43 Float[14].CB_current_value
#define mx_acces_motion_control__product_creator__m44 Float[15].CB_current_value
#define mx_acces_motion_control__product_creator__pbCreation Bool[0].CB_current_value
#define mx_acces_motion_control__product_creator__productPresence Bool[1].CB_current_value
#define mx_acces_motion_control__product_creator__idProd Int[1].CB_current_value
#define mx_acces_motion_control__product_creator__cntProd Int[2].CB_current_value
#define mx_acces_motion_control__product_creator__waitingTime Float[16].CB_current_value
#define mx_acces_motion_control__product_creator__oldIdProd Int[3].CB_current_value
#define mx_acces_motion_control__product_creator__empty1 Bool[2].CB_current_value
#define mx_acces_motion_control__product_creator__empty2 Bool[3].CB_current_value
#define mx_acces_motion_control__product_creator__empty3 Bool[4].CB_current_value
#define mx_acces_motion_control__product_creator__empty4 Bool[5].CB_current_value
#define mx_acces_motion_control__product_creator__empty5 Bool[6].CB_current_value
#define mx_acces_motion_control__product_creator__empty6 Bool[7].CB_current_value
#define mx_acces_motion_control__product_creator__empty7 Bool[8].CB_current_value
#define mx_acces_motion_control__product_creator__empty8 Bool[9].CB_current_value
#define mx_acces_motion_control__product_creator__gravitySpeed Float[17].CB_current_value
#define mx_acces_motion_control__product_creator__nbProdToCreate Int[4].CB_current_value
#define mx_acces_motion_control__product_creator__pulsedMode Bool[10].CB_current_value
#define mx_acces_motion_control__product_creator__pulseTime Float[18].CB_current_value
#define mx_acces_motion_control__product_creator__alignProductsToZ Bool[11].CB_current_value
#define mx_acces_motion_control__product_creator__alignProductsToY Bool[12].CB_current_value
#define mx_acces_motion_control__product_creator__alignProductsToX Bool[13].CB_current_value

#endif /*_MOTION_CONTROL__PRODUCT_CREATOR_H*/
