/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * robotctrl.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "robotctrl.h"


/**************************** Variables *****************************/

CB_Index robotctrl__num = 0;
CB_Mem_Bool *robotctrl_forwardUp;
CB_Mem_Bool *robotctrl_backwardUp;
CB_Mem_Bool *robotctrl_forwardDw;
CB_Mem_Bool *robotctrl_backwardDw;
CB_Mem_Bool *robotctrl_presConvUp;
CB_Mem_Bool *robotctrl_presConvDw;
CB_Mem_Float *robotctrl_masterPosition;
CB_Mem_Bool *robotctrl_Auto;
CB_Mem_Bool *robotctrl_Manu;
CB_Mem_Bool *robotctrl_run;
CB_Mem_Bool *robotctrl_weightOk;
CB_Mem_Int *robotctrl_phaseCode;
CB_Mem_Bool *robotctrl_HomeCmd;
CB_Mem_Bool *robotctrl_MoveVelCmd;
CB_Mem_Bool *robotctrl_MoveAbsCmd;
CB_Mem_Bool *robotctrl_MoveVel1ManualCmd;
CB_Mem_Bool *robotctrl_MoveVel2ManualCmd;
CB_Mem_Bool *robotctrl_MoveAbs1ManualCmd;
CB_Mem_Bool *robotctrl_MoveAbs2ManualCmd;
CB_Mem_Bool *robotctrl_StopCmd;
CB_Mem_Float *robotctrl_MovePosition;
CB_Mem_Float *robotctrl_MoveSpeed;
CB_Mem_Float *robotctrl_MoveAcceleration;
CB_Mem_Float *robotctrl_MoveDeceleration;
CB_Mem_Float *robotctrl_offsetAxToMa;
CB_Mem_Bool *robotctrl_gripSyringes;
CB_Mem_Float *robotctrl_endPhase1;
CB_Mem_Float *robotctrl_endPhase2;
CB_Mem_Float *robotctrl_endPhase3;
CB_Mem_Float *robotctrl_endPhase4;
CB_Mem_Float *robotctrl_speedPhase1;
CB_Mem_Float *robotctrl_speedPhase2;
CB_Mem_Float *robotctrl_speedPhase3;
CB_Mem_Float *robotctrl_speedPhase4;
CB_Mem_Float *robotctrl_globalSpeedFactor;

/**************************** Variables *****************************/

#define forwardUp (robotctrl_forwardUp->CB_current_value)
#define backwardUp (robotctrl_backwardUp->CB_current_value)
#define forwardDw (robotctrl_forwardDw->CB_current_value)
#define backwardDw (robotctrl_backwardDw->CB_current_value)
#define presConvUp (robotctrl_presConvUp->CB_current_value)
#define presConvDw (robotctrl_presConvDw->CB_current_value)
#define masterPosition (robotctrl_masterPosition->CB_current_value)
#define Auto (robotctrl_Auto->CB_current_value)
#define Manu (robotctrl_Manu->CB_current_value)
#define run (robotctrl_run->CB_current_value)
#define weightOk (robotctrl_weightOk->CB_current_value)
#define phaseCode (*((short *)&(robotctrl_phaseCode->CB_current_value) + ALIGN_OFFSET_SHORT))
#define HomeCmd (robotctrl_HomeCmd->CB_current_value)
#define MoveVelCmd (robotctrl_MoveVelCmd->CB_current_value)
#define MoveAbsCmd (robotctrl_MoveAbsCmd->CB_current_value)
#define MoveVel1ManualCmd (robotctrl_MoveVel1ManualCmd->CB_current_value)
#define MoveVel2ManualCmd (robotctrl_MoveVel2ManualCmd->CB_current_value)
#define MoveAbs1ManualCmd (robotctrl_MoveAbs1ManualCmd->CB_current_value)
#define MoveAbs2ManualCmd (robotctrl_MoveAbs2ManualCmd->CB_current_value)
#define StopCmd (robotctrl_StopCmd->CB_current_value)
#define MovePosition (robotctrl_MovePosition->CB_current_value)
#define MoveSpeed (robotctrl_MoveSpeed->CB_current_value)
#define MoveAcceleration (robotctrl_MoveAcceleration->CB_current_value)
#define MoveDeceleration (robotctrl_MoveDeceleration->CB_current_value)
#define offsetAxToMa (robotctrl_offsetAxToMa->CB_current_value)
#define gripSyringes (robotctrl_gripSyringes->CB_current_value)
#define endPhase1 (robotctrl_endPhase1->CB_current_value)
#define endPhase2 (robotctrl_endPhase2->CB_current_value)
#define endPhase3 (robotctrl_endPhase3->CB_current_value)
#define endPhase4 (robotctrl_endPhase4->CB_current_value)
#define speedPhase1 (robotctrl_speedPhase1->CB_current_value)
#define speedPhase2 (robotctrl_speedPhase2->CB_current_value)
#define speedPhase3 (robotctrl_speedPhase3->CB_current_value)
#define speedPhase4 (robotctrl_speedPhase4->CB_current_value)
#define globalSpeedFactor (robotctrl_globalSpeedFactor->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _flask_motion_app__robotctrl_init(void)
{
	(robotctrl_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(robotctrl_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(robotctrl_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	(self.Float+0)->CB_current_value = 50.0; /*endPhase1*/
	(self.Float+1)->CB_current_value = 60.0; /*endPhase2*/
	(self.Float+2)->CB_current_value = 150.0; /*endPhase3*/
	(self.Float+3)->CB_current_value = 200.0; /*endPhase4*/
	(self.Float+4)->CB_current_value = 80.0; /*speedPhase1*/
	(self.Float+5)->CB_current_value = 85.0; /*speedPhase2*/
	(self.Float+6)->CB_current_value = 100.0; /*speedPhase3*/
	(self.Float+7)->CB_current_value = 100.0; /*speedPhase4*/
	(self.Float+8)->CB_current_value = 100.0; /*globalSpeedFactor*/
	self.Float+=9;


	return 0;
}


/************************ Behavior function *************************/

int flask_motion_app__robotctrl(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		robotctrl_endPhase1 = self.Float+0;
		robotctrl_endPhase2 = self.Float+1;
		robotctrl_endPhase3 = self.Float+2;
		robotctrl_endPhase4 = self.Float+3;
		robotctrl_speedPhase1 = self.Float+4;
		robotctrl_speedPhase2 = self.Float+5;
		robotctrl_speedPhase3 = self.Float+6;
		robotctrl_speedPhase4 = self.Float+7;
		robotctrl_globalSpeedFactor = self.Float+8;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if ((masterPosition >= 0.0) && (masterPosition < endPhase1)) {
				phaseCode = 1;
			}
			if ((masterPosition >= endPhase1) && (masterPosition < endPhase2)) {
				phaseCode = 2;
			}
			if ((masterPosition >= endPhase2) && (masterPosition < endPhase3)) {
				phaseCode = 3;
			}
			if ((masterPosition >= endPhase3) && (masterPosition < endPhase4)) {
				phaseCode = 4;
			}
			if ((masterPosition >= endPhase4) && (masterPosition < 360.0)) {
				phaseCode = 5;
			}
			if ((phaseCode == 2) && (!presConvDw || !weightOk)) {
				phaseCode = 0;
			}
			if ((phaseCode == 3) && presConvUp) {
				phaseCode = 0;
			}
			if (!run) {
				phaseCode = 0;
			}
			switch (phaseCode) {
			case 0:
				MoveVelCmd = 0;
				break;
			case 1:
				MoveVelCmd = 1;
				MoveSpeed = speedPhase1 * globalSpeedFactor / 100.0;
				gripSyringes = 0;
				break;
			case 2:
				MoveVelCmd = 1;
				MoveSpeed = speedPhase2 * globalSpeedFactor / 100.0;
				gripSyringes = 1;
				break;
			case 3:
				MoveVelCmd = 1;
				MoveSpeed = speedPhase3 * globalSpeedFactor / 100.0;
				gripSyringes = 1;
				break;
			case 4:
				MoveVelCmd = 1;
				MoveSpeed = speedPhase4 * globalSpeedFactor / 100.0;
				gripSyringes = 1;
				break;
			case 5:
				MoveVelCmd = 1;
				MoveSpeed = speedPhase4 * globalSpeedFactor / 100.0;
				gripSyringes = 0;
				break;
			default:
				MoveVelCmd = 0;
				break;
			}
		}

		CB_post_int(robotctrl_phaseCode);
		CB_post_bool(robotctrl_HomeCmd);
		CB_post_bool(robotctrl_MoveVelCmd);
		CB_post_bool(robotctrl_MoveAbsCmd);
		CB_post_bool(robotctrl_MoveVel1ManualCmd);
		CB_post_bool(robotctrl_MoveVel2ManualCmd);
		CB_post_bool(robotctrl_MoveAbs1ManualCmd);
		CB_post_bool(robotctrl_MoveAbs2ManualCmd);
		CB_post_bool(robotctrl_StopCmd);
		CB_post_float(robotctrl_MovePosition);
		CB_post_float(robotctrl_MoveSpeed);
		CB_post_float(robotctrl_MoveAcceleration);
		CB_post_float(robotctrl_MoveDeceleration);
		CB_post_float(robotctrl_offsetAxToMa);
		CB_post_bool(robotctrl_gripSyringes);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Float += 9;

	return 0;
}

