/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * robotctrl.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _FLASK_MOTION_APP__ROBOTCTRL_H
#define _FLASK_MOTION_APP__ROBOTCTRL_H


/********************** Variable declarations ***********************/

extern CB_Index robotctrl__num;
extern CB_Mem_Bool *robotctrl_forwardUp;
extern CB_Mem_Bool *robotctrl_backwardUp;
extern CB_Mem_Bool *robotctrl_forwardDw;
extern CB_Mem_Bool *robotctrl_backwardDw;
extern CB_Mem_Bool *robotctrl_presConvUp;
extern CB_Mem_Bool *robotctrl_presConvDw;
extern CB_Mem_Float *robotctrl_masterPosition;
extern CB_Mem_Bool *robotctrl_Auto;
extern CB_Mem_Bool *robotctrl_Manu;
extern CB_Mem_Bool *robotctrl_run;
extern CB_Mem_Bool *robotctrl_weightOk;
extern CB_Mem_Int *robotctrl_phaseCode;
extern CB_Mem_Bool *robotctrl_HomeCmd;
extern CB_Mem_Bool *robotctrl_MoveVelCmd;
extern CB_Mem_Bool *robotctrl_MoveAbsCmd;
extern CB_Mem_Bool *robotctrl_MoveVel1ManualCmd;
extern CB_Mem_Bool *robotctrl_MoveVel2ManualCmd;
extern CB_Mem_Bool *robotctrl_MoveAbs1ManualCmd;
extern CB_Mem_Bool *robotctrl_MoveAbs2ManualCmd;
extern CB_Mem_Bool *robotctrl_StopCmd;
extern CB_Mem_Float *robotctrl_MovePosition;
extern CB_Mem_Float *robotctrl_MoveSpeed;
extern CB_Mem_Float *robotctrl_MoveAcceleration;
extern CB_Mem_Float *robotctrl_MoveDeceleration;
extern CB_Mem_Float *robotctrl_offsetAxToMa;
extern CB_Mem_Bool *robotctrl_gripSyringes;
extern CB_Mem_Float *robotctrl_endPhase1;
extern CB_Mem_Float *robotctrl_endPhase2;
extern CB_Mem_Float *robotctrl_endPhase3;
extern CB_Mem_Float *robotctrl_endPhase4;
extern CB_Mem_Float *robotctrl_speedPhase1;
extern CB_Mem_Float *robotctrl_speedPhase2;
extern CB_Mem_Float *robotctrl_speedPhase3;
extern CB_Mem_Float *robotctrl_speedPhase4;
extern CB_Mem_Float *robotctrl_globalSpeedFactor;

/********************** Function declarations ***********************/

extern int _flask_motion_app__robotctrl_init(void);
extern int flask_motion_app__robotctrl(void);

#endif /*_FLASK_MOTION_APP__ROBOTCTRL_H*/
