/*2023-10-04T11:03:52-01:00*/

/********************************************************************
 * single_acting_jack.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__SINGLE_ACTING_JACK_H
#define _MOTION_LIB__SINGLE_ACTING_JACK_H


/********************** Variable declarations ***********************/

extern CB_Index single_acting_jack__num;
extern CB_Mem_Bool *single_acting_jack_energy;
extern CB_Mem_Bool *single_acting_jack_cmdSupply;
extern CB_Mem_Bool *single_acting_jack_sensorSupply;
extern CB_Mem_Bool *single_acting_jack_valveWork;
extern CB_Mem_Bool *single_acting_jack_outletSensor;
extern CB_Mem_Bool *single_acting_jack_inletSensor;
extern CB_Mem_Float *single_acting_jack_rodPosition;
extern CB_Mem_Float *single_acting_jack_rodPercent;
extern CB_Mem_Float *single_acting_jack_incrementValue;
extern CB_Mem_Int *single_acting_jack_slidePosition;
extern CB_Mem_Bool *single_acting_jack_pipeWork;
extern CB_Mem_Bool *single_acting_jack_pipeRest;
extern CB_Mem_Float *single_acting_jack_increment;
extern CB_Mem_Bool *single_acting_jack_outletSensorLogic;
extern CB_Mem_Bool *single_acting_jack_inletSensorLogic;
extern CB_Mem_Float *single_acting_jack_rodLength;
extern CB_Mem_Float *single_acting_jack_time2extend;
extern CB_Mem_Bool *single_acting_jack_d_locking;
extern CB_Mem_Float *single_acting_jack_v_d_locking;
extern CB_Mem_Bool *single_acting_jack_d_inletSensor;
extern CB_Mem_Bool *single_acting_jack_v_d_inletSensor;
extern CB_Mem_Bool *single_acting_jack_d_outletSensor;
extern CB_Mem_Bool *single_acting_jack_v_d_outletSensor;

/********************** Function declarations ***********************/

extern int _motion_lib__single_acting_jack_init(void);
extern int motion_lib__single_acting_jack(void);

#endif /*_MOTION_LIB__SINGLE_ACTING_JACK_H*/
