/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * pusher.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__PUSHER_H
#define _MOTION_LIB__PUSHER_H


/********************** Variable declarations ***********************/

extern CB_Index pusher__num;
extern CB_Mem_Float *pusher_moveX;
extern CB_Mem_Float *pusher_moveY;
extern CB_Mem_Float *pusher_moveZ;
extern CB_Mem_Int *pusher_status_act_prod;
extern CB_Mem_Float *pusher_m11;
extern CB_Mem_Float *pusher_m12;
extern CB_Mem_Float *pusher_m13;
extern CB_Mem_Float *pusher_m14;
extern CB_Mem_Float *pusher_m21;
extern CB_Mem_Float *pusher_m22;
extern CB_Mem_Float *pusher_m23;
extern CB_Mem_Float *pusher_m24;
extern CB_Mem_Float *pusher_m31;
extern CB_Mem_Float *pusher_m32;
extern CB_Mem_Float *pusher_m33;
extern CB_Mem_Float *pusher_m34;
extern CB_Mem_Float *pusher_m41;
extern CB_Mem_Float *pusher_m42;
extern CB_Mem_Float *pusher_m43;
extern CB_Mem_Float *pusher_m44;
extern CB_Mem_Float *pusher_moveX1;
extern CB_Mem_Float *pusher_moveY1;
extern CB_Mem_Float *pusher_moveZ1;
extern CB_Mem_Float *pusher_oriX;
extern CB_Mem_Float *pusher_oriY;
extern CB_Mem_Float *pusher_oriZ;

/********************** Function declarations ***********************/

extern int _motion_lib__pusher_init(void);
extern int motion_lib__pusher(void);

/************************** Access macros ***************************/

#define mx_acces_motion_lib__pusher__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_lib__pusher__m11 Float[0].CB_current_value
#define mx_acces_motion_lib__pusher__m12 Float[1].CB_current_value
#define mx_acces_motion_lib__pusher__m13 Float[2].CB_current_value
#define mx_acces_motion_lib__pusher__m14 Float[3].CB_current_value
#define mx_acces_motion_lib__pusher__m21 Float[4].CB_current_value
#define mx_acces_motion_lib__pusher__m22 Float[5].CB_current_value
#define mx_acces_motion_lib__pusher__m23 Float[6].CB_current_value
#define mx_acces_motion_lib__pusher__m24 Float[7].CB_current_value
#define mx_acces_motion_lib__pusher__m31 Float[8].CB_current_value
#define mx_acces_motion_lib__pusher__m32 Float[9].CB_current_value
#define mx_acces_motion_lib__pusher__m33 Float[10].CB_current_value
#define mx_acces_motion_lib__pusher__m34 Float[11].CB_current_value
#define mx_acces_motion_lib__pusher__m41 Float[12].CB_current_value
#define mx_acces_motion_lib__pusher__m42 Float[13].CB_current_value
#define mx_acces_motion_lib__pusher__m43 Float[14].CB_current_value
#define mx_acces_motion_lib__pusher__m44 Float[15].CB_current_value
#define mx_acces_motion_lib__pusher__moveX1 Float[16].CB_current_value
#define mx_acces_motion_lib__pusher__moveY1 Float[17].CB_current_value
#define mx_acces_motion_lib__pusher__moveZ1 Float[18].CB_current_value
#define mx_acces_motion_lib__pusher__oriX Float[19].CB_current_value
#define mx_acces_motion_lib__pusher__oriY Float[20].CB_current_value
#define mx_acces_motion_lib__pusher__oriZ Float[21].CB_current_value

#endif /*_MOTION_LIB__PUSHER_H*/
