/*2023-10-04T11:03:55-01:00*/

/********************************************************************
 * servo_mode.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__SERVO_MODE_H
#define _MOTION_CONTROL__SERVO_MODE_H


/********************** Variable declarations ***********************/

extern CB_Index servo_mode__num;
extern CB_Mem_Bool *servo_mode_PLC_StatusReady;
extern CB_Mem_Bool *servo_mode_PLC_StatusMoved;
extern CB_Mem_Bool *servo_mode_PLC_StatusStand;
extern CB_Mem_Float *servo_mode_PLC_ActualPositionAx;
extern CB_Mem_Float *servo_mode_PLC_ActualPositionMa;
extern CB_Mem_Float *servo_mode_PLC_ActualVelocity;
extern CB_Mem_Bool *servo_mode_StatusReady;
extern CB_Mem_Bool *servo_mode_StatusMoved;
extern CB_Mem_Bool *servo_mode_StatusStand;
extern CB_Mem_Float *servo_mode_ActualPositionMa;
extern CB_Mem_Float *servo_mode_ActualVelocity;
extern CB_Mem_Float *servo_mode_MaximumVelocity;
extern CB_Mem_Float *servo_mode_physicalPosInit;
extern CB_Mem_Float *servo_mode_ActualPositionAx;
extern CB_Mem_Bool *servo_mode_StatusReady_o;
extern CB_Mem_Bool *servo_mode_StatusMoved_o;
extern CB_Mem_Bool *servo_mode_StatusStand_o;
extern CB_Mem_Float *servo_mode_ActualPositionAx_o;
extern CB_Mem_Float *servo_mode_ActualPositionMa_o;
extern CB_Mem_Float *servo_mode_ActualVelocity_o;
extern CB_Mem_Float *servo_mode_MaximumVelocity_o;
extern CB_Mem_Bool *servo_mode_StatusPosIncrease_o;
extern CB_Mem_Bool *servo_mode_StatusPosDecrease_o;
extern CB_Mem_Float *servo_mode_displayJauge_o;
extern CB_Mem_Bool *servo_mode_PLCMode;
extern CB_Mem_Bool *servo_mode_PLCMode1;
extern CB_Mem_Bool *servo_mode_initDone;
extern CB_Mem_Float *servo_mode_displayPosMin;
extern CB_Mem_Float *servo_mode_displayPosMax;
extern CB_Mem_Float *servo_mode_PLC_ActualPositionAx1;
extern CB_Mem_Float *servo_mode_PLC_ActualVelocity1;
extern CB_Mem_Float *servo_mode_ActualPositionAx1;
extern CB_Mem_Float *servo_mode_ActualVelocity1;
extern CB_Mem_Float *servo_mode_offsetAxToMa;
extern CB_Mem_Float *servo_mode_offsetAxToMa1;
extern CB_Mem_Float *servo_mode_ActualPositionMa_o1;

/********************** Function declarations ***********************/

extern int _motion_control__servo_mode_init(void);
extern int motion_control__servo_mode(void);

#endif /*_MOTION_CONTROL__SERVO_MODE_H*/
