/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * servo.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "servo.h"
#include "motion_control/functional/servo_mode/servo_mode.h"
#include "motion_control/functional/servo_control/servo_control.h"
#include "motion_control/functional/servo_velocity/servo_velocity.h"
#include "motion_control/functional/servo_position/servo_position.h"


/**************************** Variables *****************************/

CB_Index servo__num = 0;
CB_Mem_Int *servo_status;
CB_Mem_Int *servo_errorFlag;
CB_Mem_Float *servo_ActualPositionAx1;
CB_Mem_Bool *servo_MoveVelDone1;
CB_Mem_Float *servo_ActualVelocity1;
CB_Mem_Bool *servo_MoveAbsDone1;
CB_Mem_Bool *servo_HomeCmd;
CB_Mem_Bool *servo_MoveVelCmd;
CB_Mem_Bool *servo_MoveAbsCmd;
CB_Mem_Bool *servo_MoveVel1ManualCmd;
CB_Mem_Bool *servo_MoveVel2ManualCmd;
CB_Mem_Bool *servo_MoveAbs1ManualCmd;
CB_Mem_Bool *servo_MoveAbs2ManualCmd;
CB_Mem_Bool *servo_StopCmd;
CB_Mem_Float *servo_MovePosition;
CB_Mem_Float *servo_MoveSpeed;
CB_Mem_Float *servo_MoveAcceleration;
CB_Mem_Float *servo_MoveDeceleration;
CB_Mem_Float *servo_offsetAxToMa;
CB_Mem_Bool *servo_PLC_StatusReady;
CB_Mem_Bool *servo_PLC_StatusMoved;
CB_Mem_Bool *servo_PLC_StatusStand;
CB_Mem_Float *servo_PLC_ActualPositionAx;
CB_Mem_Float *servo_PLC_ActualPositionMa;
CB_Mem_Float *servo_PLC_ActualVelocity;
CB_Mem_Float *servo_physicalPosInit;
CB_Mem_Float *servo_MAX_SPEED;
CB_Mem_Float *servo_MAX_ACCEL;
CB_Mem_Float *servo_MAX_DECEL;
CB_Mem_Float *servo_MODULO_LENGTH;
CB_Mem_Bool *servo_StatusReady;
CB_Mem_Bool *servo_StatusMoved;
CB_Mem_Bool *servo_StatusStand;
CB_Mem_Float *servo_ActualPositionAx;
CB_Mem_Float *servo_ActualPositionMa;
CB_Mem_Float *servo_ActualVelocity;
CB_Mem_Float *servo_MaximumVelocity;
CB_Mem_Bool *servo_StatusPosIncrease;
CB_Mem_Bool *servo_StatusPosDecrease;
CB_Mem_Float *servo_displayJauge;

/**************************** Variables *****************************/

#define MAX_SPEED (servo_MAX_SPEED->CB_current_value)
#define MAX_ACCEL (servo_MAX_ACCEL->CB_current_value)
#define MAX_DECEL (servo_MAX_DECEL->CB_current_value)


/************************ Components offsets ************************/

static CB_Offset motion_control__servo_offset_servo_mode;
static CB_Offset motion_control__servo_offset_servo_control;
static CB_Offset motion_control__servo_offset_servo_velocity;
static CB_Offset motion_control__servo_offset_servo_position;
static CB_Offset motion_control__servo_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _motion_control__servo_init(void)
{
	CB_Object __start = self;
	(servo_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(servo_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(servo_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	(servo_PLC_StatusReady)->CB_current_value = 1; /*PLC_StatusReady*/
	(servo_MAX_SPEED)->CB_current_value = 30.0; /*MAX_SPEED*/
	(servo_MAX_ACCEL)->CB_current_value = 1500.0; /*MAX_ACCEL*/
	(servo_MAX_DECEL)->CB_current_value = 1500.0; /*MAX_DECEL*/
	(servo_StatusReady)->CB_current_value = 1; /*StatusReady*/
	self.Bool+=7;
	self.Int+=1;
	self.Float+=5;

	/*initialize child servo_mode (motion_control.servo_mode):*/
	self_num++;
	motion_control__servo_offset_servo_mode.Bool = self.Bool - __start.Bool;
	motion_control__servo_offset_servo_mode.Int = self.Int - __start.Int;
	motion_control__servo_offset_servo_mode.Float = self.Float - __start.Float;
	motion_control__servo_offset_servo_mode.Char = self.Char - __start.Char;
	servo_mode_PLC_StatusReady = servo_PLC_StatusReady;
	servo_mode_PLC_StatusMoved = servo_PLC_StatusMoved;
	servo_mode_PLC_StatusStand = servo_PLC_StatusStand;
	servo_mode_PLC_ActualPositionAx = servo_PLC_ActualPositionAx;
	servo_mode_PLC_ActualPositionMa = servo_PLC_ActualPositionMa;
	servo_mode_PLC_ActualVelocity = servo_PLC_ActualVelocity;
	servo_mode_StatusReady = __start.Bool+0; /*servo__cn_12*/
	servo_mode_StatusMoved = __start.Bool+1; /*servo__cn_11*/
	servo_mode_StatusStand = __start.Bool+2; /*servo__cn_10*/
	servo_mode_ActualPositionMa = __start.Float+0; /*servo__cn_9*/
	servo_mode_ActualVelocity = __start.Float+1; /*servo__cn_8*/
	servo_mode_MaximumVelocity = __start.Float+2; /*servo__cn_7*/
	servo_mode_physicalPosInit = servo_physicalPosInit;
	servo_mode_ActualPositionAx = servo_ActualPositionAx1;
	servo_mode_StatusReady_o = servo_StatusReady;
	servo_mode_StatusMoved_o = servo_StatusMoved;
	servo_mode_StatusStand_o = servo_StatusStand;
	servo_mode_ActualPositionAx_o = servo_ActualPositionAx;
	servo_mode_ActualPositionMa_o = servo_ActualPositionMa;
	servo_mode_ActualVelocity_o = servo_ActualVelocity;
	servo_mode_MaximumVelocity_o = servo_MaximumVelocity;
	servo_mode_StatusPosIncrease_o = servo_StatusPosIncrease;
	servo_mode_StatusPosDecrease_o = servo_StatusPosDecrease;
	servo_mode_displayJauge_o = servo_displayJauge;
	_motion_control__servo_mode_init();

	/*initialize child servo_control (motion_control.servo_control):*/
	self_num++;
	motion_control__servo_offset_servo_control.Bool = self.Bool - __start.Bool;
	motion_control__servo_offset_servo_control.Int = self.Int - __start.Int;
	motion_control__servo_offset_servo_control.Float = self.Float - __start.Float;
	motion_control__servo_offset_servo_control.Char = self.Char - __start.Char;
	servo_control_HomeCmd = servo_HomeCmd;
	servo_control_MoveVelCmd = servo_MoveVelCmd;
	servo_control_MoveAbsCmd = servo_MoveAbsCmd;
	servo_control_MoveVel1ManualCmd = servo_MoveVel1ManualCmd;
	servo_control_MoveVel2ManualCmd = servo_MoveVel2ManualCmd;
	servo_control_MoveAbs1ManualCmd = servo_MoveAbs1ManualCmd;
	servo_control_MoveAbs2ManualCmd = servo_MoveAbs2ManualCmd;
	servo_control_StopCmd = servo_StopCmd;
	servo_control_MovePosition = servo_MovePosition;
	servo_control_MoveSpeed = servo_MoveSpeed;
	servo_control_MoveAcceleration = servo_MoveAcceleration;
	servo_control_MoveDeceleration = servo_MoveDeceleration;
	servo_control_offsetAxToMa = servo_offsetAxToMa;
	servo_control_physicalPosInit = servo_physicalPosInit;
	servo_control_MAX_SPEED = servo_MAX_SPEED;
	servo_control_status = servo_status;
	servo_control_errorFlag = servo_errorFlag;
	servo_control_IOActualPositionAx = servo_ActualPositionAx1;
	servo_control_IOVelDone = servo_MoveVelDone1;
	servo_control_IOAbsDone = servo_MoveAbsDone1;
	servo_control_IOActualVelocity = servo_ActualVelocity1;
	servo_control_OperationMode = __start.Int+0; /*servo__cn_13*/
	servo_control_StatusReady = __start.Bool+0; /*servo__cn_12*/
	servo_control_StatusMove = __start.Bool+1; /*servo__cn_11*/
	servo_control_StatusStand = __start.Bool+2; /*servo__cn_10*/
	servo_control_ActualPositionMa = __start.Float+0; /*servo__cn_9*/
	servo_control_ActualVelocity = __start.Float+1; /*servo__cn_8*/
	servo_control_MaximumVelocity = __start.Float+2; /*servo__cn_7*/
	servo_control_VelEnabled = __start.Bool+3; /*servo__cn_6*/
	servo_control_VelCmd = __start.Bool+4; /*servo__cn_5*/
	servo_control_PosEnabled = __start.Bool+5; /*servo__cn_3*/
	servo_control_PosCmd = __start.Bool+6; /*servo__cn_2*/
	servo_control_Position = __start.Float+4; /*servo__cn_1*/
	servo_control_Speed = __start.Float+3; /*servo__cn_4*/
	_motion_control__servo_control_init();

	/*initialize child servo_velocity (motion_control.servo_velocity):*/
	self_num++;
	motion_control__servo_offset_servo_velocity.Bool = self.Bool - __start.Bool;
	motion_control__servo_offset_servo_velocity.Int = self.Int - __start.Int;
	motion_control__servo_offset_servo_velocity.Float = self.Float - __start.Float;
	motion_control__servo_offset_servo_velocity.Char = self.Char - __start.Char;
	servo_velocity_MoveVelEnable = __start.Bool+3; /*servo__cn_6*/
	servo_velocity_MoveVelStart = __start.Bool+4; /*servo__cn_5*/
	servo_velocity_MoveSpeed = __start.Float+3; /*servo__cn_4*/
	servo_velocity_MoveAcceleration = servo_MoveAcceleration;
	servo_velocity_MoveDeceleration = servo_MoveDeceleration;
	servo_velocity_MAX_SPEED = servo_MAX_SPEED;
	servo_velocity_MAX_ACCEL = servo_MAX_ACCEL;
	servo_velocity_MAX_DECEL = servo_MAX_DECEL;
	servo_velocity_MODULO_LENGTH = servo_MODULO_LENGTH;
	servo_velocity_status = servo_status;
	servo_velocity_errorFlag = servo_errorFlag;
	servo_velocity_MoveVelDone = servo_MoveVelDone1;
	servo_velocity_ActualPositionAx = servo_ActualPositionAx1;
	servo_velocity_ActualVelocity = servo_ActualVelocity1;
	_motion_control__servo_velocity_init();

	/*initialize child servo_position (motion_control.servo_position):*/
	self_num++;
	motion_control__servo_offset_servo_position.Bool = self.Bool - __start.Bool;
	motion_control__servo_offset_servo_position.Int = self.Int - __start.Int;
	motion_control__servo_offset_servo_position.Float = self.Float - __start.Float;
	motion_control__servo_offset_servo_position.Char = self.Char - __start.Char;
	servo_position_MoveAbsEnable = __start.Bool+5; /*servo__cn_3*/
	servo_position_MoveAbsStart = __start.Bool+6; /*servo__cn_2*/
	servo_position_MovePosition = __start.Float+4; /*servo__cn_1*/
	servo_position_MoveSpeed = __start.Float+3; /*servo__cn_4*/
	servo_position_MoveAcceleration = servo_MoveAcceleration;
	servo_position_MoveDeceleration = servo_MoveDeceleration;
	servo_position_MAX_SPEED = servo_MAX_SPEED;
	servo_position_MAX_ACCEL = servo_MAX_ACCEL;
	servo_position_MAX_DECEL = servo_MAX_DECEL;
	servo_position_MODULO_LENGTH = servo_MODULO_LENGTH;
	servo_position_status = servo_status;
	servo_position_errorFlag = servo_errorFlag;
	servo_position_MoveAbsDone = servo_MoveAbsDone1;
	servo_position_ActualPositionAx = servo_ActualPositionAx1;
	servo_position_ActualVelocity = servo_ActualVelocity1;
	_motion_control__servo_position_init();

	motion_control__servo_offset__end.Bool = self.Bool - __start.Bool;
	motion_control__servo_offset__end.Int = self.Int - __start.Int;
	motion_control__servo_offset__end.Float = self.Float - __start.Float;
	motion_control__servo_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int motion_control__servo(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																										
		/********************* Pre-conditions execution *********************/

		if (allowpreconditions->CB_current_value) {
			if (!((0.0 <= MAX_SPEED) && (MAX_SPEED <= 3.4e+38))) {
				raise_debug_break(servo_MAX_SPEED - mem.Float, INPRE, OUTOFRANGESFLOAT, 0);
				return servo__num; /*assertion failure*/
			}
			if (!((0.0 <= MAX_ACCEL) && (MAX_ACCEL <= 3.4e+38))) {
				raise_debug_break(servo_MAX_ACCEL - mem.Float, INPRE, OUTOFRANGESFLOAT, 0);
				return servo__num; /*assertion failure*/
			}
			if (!((0.0 <= MAX_DECEL) && (MAX_DECEL <= 3.4e+38))) {
				raise_debug_break(servo_MAX_DECEL - mem.Float, INPRE, OUTOFRANGESFLOAT, 0);
				return servo__num; /*assertion failure*/
			}
		}

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + motion_control__servo_offset_servo_mode.Bool;
			self.Int = __start.Int + motion_control__servo_offset_servo_mode.Int;
			self.Float = __start.Float + motion_control__servo_offset_servo_mode.Float;
			self.Char = __start.Char + motion_control__servo_offset_servo_mode.Char;

			/*********************** servo_mode execution ***********************/

			self_num++;
			if (servo_mode__num != self_num) {
				servo_mode__num = self_num;
				servo_mode_PLC_StatusReady = servo_PLC_StatusReady;
				servo_mode_PLC_StatusMoved = servo_PLC_StatusMoved;
				servo_mode_PLC_StatusStand = servo_PLC_StatusStand;
				servo_mode_PLC_ActualPositionAx = servo_PLC_ActualPositionAx;
				servo_mode_PLC_ActualPositionMa = servo_PLC_ActualPositionMa;
				servo_mode_PLC_ActualVelocity = servo_PLC_ActualVelocity;
				servo_mode_StatusReady = __start.Bool+0; /*servo__cn_12*/
				servo_mode_StatusMoved = __start.Bool+1; /*servo__cn_11*/
				servo_mode_StatusStand = __start.Bool+2; /*servo__cn_10*/
				servo_mode_ActualPositionMa = __start.Float+0; /*servo__cn_9*/
				servo_mode_ActualVelocity = __start.Float+1; /*servo__cn_8*/
				servo_mode_MaximumVelocity = __start.Float+2; /*servo__cn_7*/
				servo_mode_physicalPosInit = servo_physicalPosInit;
				servo_mode_ActualPositionAx = servo_ActualPositionAx1;
				servo_mode_StatusReady_o = servo_StatusReady;
				servo_mode_StatusMoved_o = servo_StatusMoved;
				servo_mode_StatusStand_o = servo_StatusStand;
				servo_mode_ActualPositionAx_o = servo_ActualPositionAx;
				servo_mode_ActualPositionMa_o = servo_ActualPositionMa;
				servo_mode_ActualVelocity_o = servo_ActualVelocity;
				servo_mode_MaximumVelocity_o = servo_MaximumVelocity;
				servo_mode_StatusPosIncrease_o = servo_StatusPosIncrease;
				servo_mode_StatusPosDecrease_o = servo_StatusPosDecrease;
				servo_mode_displayJauge_o = servo_displayJauge;
			}
			__ret = motion_control__servo_mode();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* servo_control execution **********************/

			self_num++;
			if (servo_control__num != self_num) {
				servo_control__num = self_num;
				servo_control_HomeCmd = servo_HomeCmd;
				servo_control_MoveVelCmd = servo_MoveVelCmd;
				servo_control_MoveAbsCmd = servo_MoveAbsCmd;
				servo_control_MoveVel1ManualCmd = servo_MoveVel1ManualCmd;
				servo_control_MoveVel2ManualCmd = servo_MoveVel2ManualCmd;
				servo_control_MoveAbs1ManualCmd = servo_MoveAbs1ManualCmd;
				servo_control_MoveAbs2ManualCmd = servo_MoveAbs2ManualCmd;
				servo_control_StopCmd = servo_StopCmd;
				servo_control_MovePosition = servo_MovePosition;
				servo_control_MoveSpeed = servo_MoveSpeed;
				servo_control_MoveAcceleration = servo_MoveAcceleration;
				servo_control_MoveDeceleration = servo_MoveDeceleration;
				servo_control_offsetAxToMa = servo_offsetAxToMa;
				servo_control_physicalPosInit = servo_physicalPosInit;
				servo_control_MAX_SPEED = servo_MAX_SPEED;
				servo_control_status = servo_status;
				servo_control_errorFlag = servo_errorFlag;
				servo_control_IOActualPositionAx = servo_ActualPositionAx1;
				servo_control_IOVelDone = servo_MoveVelDone1;
				servo_control_IOAbsDone = servo_MoveAbsDone1;
				servo_control_IOActualVelocity = servo_ActualVelocity1;
				servo_control_OperationMode = __start.Int+0; /*servo__cn_13*/
				servo_control_StatusReady = __start.Bool+0; /*servo__cn_12*/
				servo_control_StatusMove = __start.Bool+1; /*servo__cn_11*/
				servo_control_StatusStand = __start.Bool+2; /*servo__cn_10*/
				servo_control_ActualPositionMa = __start.Float+0; /*servo__cn_9*/
				servo_control_ActualVelocity = __start.Float+1; /*servo__cn_8*/
				servo_control_MaximumVelocity = __start.Float+2; /*servo__cn_7*/
				servo_control_VelEnabled = __start.Bool+3; /*servo__cn_6*/
				servo_control_VelCmd = __start.Bool+4; /*servo__cn_5*/
				servo_control_PosEnabled = __start.Bool+5; /*servo__cn_3*/
				servo_control_PosCmd = __start.Bool+6; /*servo__cn_2*/
				servo_control_Position = __start.Float+4; /*servo__cn_1*/
				servo_control_Speed = __start.Float+3; /*servo__cn_4*/
			}
			__ret = motion_control__servo_control();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* servo_velocity execution *********************/

			self_num++;
			if (servo_velocity__num != self_num) {
				servo_velocity__num = self_num;
				servo_velocity_MoveVelEnable = __start.Bool+3; /*servo__cn_6*/
				servo_velocity_MoveVelStart = __start.Bool+4; /*servo__cn_5*/
				servo_velocity_MoveSpeed = __start.Float+3; /*servo__cn_4*/
				servo_velocity_MoveAcceleration = servo_MoveAcceleration;
				servo_velocity_MoveDeceleration = servo_MoveDeceleration;
				servo_velocity_MAX_SPEED = servo_MAX_SPEED;
				servo_velocity_MAX_ACCEL = servo_MAX_ACCEL;
				servo_velocity_MAX_DECEL = servo_MAX_DECEL;
				servo_velocity_MODULO_LENGTH = servo_MODULO_LENGTH;
				servo_velocity_status = servo_status;
				servo_velocity_errorFlag = servo_errorFlag;
				servo_velocity_MoveVelDone = servo_MoveVelDone1;
				servo_velocity_ActualPositionAx = servo_ActualPositionAx1;
				servo_velocity_ActualVelocity = servo_ActualVelocity1;
			}
			__ret = motion_control__servo_velocity();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* servo_position execution *********************/

			self_num++;
			if (servo_position__num != self_num) {
				servo_position__num = self_num;
				servo_position_MoveAbsEnable = __start.Bool+5; /*servo__cn_3*/
				servo_position_MoveAbsStart = __start.Bool+6; /*servo__cn_2*/
				servo_position_MovePosition = __start.Float+4; /*servo__cn_1*/
				servo_position_MoveSpeed = __start.Float+3; /*servo__cn_4*/
				servo_position_MoveAcceleration = servo_MoveAcceleration;
				servo_position_MoveDeceleration = servo_MoveDeceleration;
				servo_position_MAX_SPEED = servo_MAX_SPEED;
				servo_position_MAX_ACCEL = servo_MAX_ACCEL;
				servo_position_MAX_DECEL = servo_MAX_DECEL;
				servo_position_MODULO_LENGTH = servo_MODULO_LENGTH;
				servo_position_status = servo_status;
				servo_position_errorFlag = servo_errorFlag;
				servo_position_MoveAbsDone = servo_MoveAbsDone1;
				servo_position_ActualPositionAx = servo_ActualPositionAx1;
				servo_position_ActualVelocity = servo_ActualVelocity1;
			}
			__ret = motion_control__servo_position();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + motion_control__servo_offset__end.Bool;
	self.Int = __start.Int + motion_control__servo_offset__end.Int;
	self.Float = __start.Float + motion_control__servo_offset__end.Float;
	self.Char = __start.Char + motion_control__servo_offset__end.Char;

	return 0;
}

