/*2023-10-04T11:03:58-01:00*/

/********************************************************************
 * servo.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_CONTROL__SERVO_H
#define _MOTION_CONTROL__SERVO_H


/********************** Variable declarations ***********************/

extern CB_Index servo__num;
extern CB_Mem_Int *servo_status;
extern CB_Mem_Int *servo_errorFlag;
extern CB_Mem_Float *servo_ActualPositionAx1;
extern CB_Mem_Bool *servo_MoveVelDone1;
extern CB_Mem_Float *servo_ActualVelocity1;
extern CB_Mem_Bool *servo_MoveAbsDone1;
extern CB_Mem_Bool *servo_HomeCmd;
extern CB_Mem_Bool *servo_MoveVelCmd;
extern CB_Mem_Bool *servo_MoveAbsCmd;
extern CB_Mem_Bool *servo_MoveVel1ManualCmd;
extern CB_Mem_Bool *servo_MoveVel2ManualCmd;
extern CB_Mem_Bool *servo_MoveAbs1ManualCmd;
extern CB_Mem_Bool *servo_MoveAbs2ManualCmd;
extern CB_Mem_Bool *servo_StopCmd;
extern CB_Mem_Float *servo_MovePosition;
extern CB_Mem_Float *servo_MoveSpeed;
extern CB_Mem_Float *servo_MoveAcceleration;
extern CB_Mem_Float *servo_MoveDeceleration;
extern CB_Mem_Float *servo_offsetAxToMa;
extern CB_Mem_Bool *servo_PLC_StatusReady;
extern CB_Mem_Bool *servo_PLC_StatusMoved;
extern CB_Mem_Bool *servo_PLC_StatusStand;
extern CB_Mem_Float *servo_PLC_ActualPositionAx;
extern CB_Mem_Float *servo_PLC_ActualPositionMa;
extern CB_Mem_Float *servo_PLC_ActualVelocity;
extern CB_Mem_Float *servo_physicalPosInit;
extern CB_Mem_Float *servo_MAX_SPEED;
extern CB_Mem_Float *servo_MAX_ACCEL;
extern CB_Mem_Float *servo_MAX_DECEL;
extern CB_Mem_Float *servo_MODULO_LENGTH;
extern CB_Mem_Bool *servo_StatusReady;
extern CB_Mem_Bool *servo_StatusMoved;
extern CB_Mem_Bool *servo_StatusStand;
extern CB_Mem_Float *servo_ActualPositionAx;
extern CB_Mem_Float *servo_ActualPositionMa;
extern CB_Mem_Float *servo_ActualVelocity;
extern CB_Mem_Float *servo_MaximumVelocity;
extern CB_Mem_Bool *servo_StatusPosIncrease;
extern CB_Mem_Bool *servo_StatusPosDecrease;
extern CB_Mem_Float *servo_displayJauge;

/********************** Function declarations ***********************/

extern int _motion_control__servo_init(void);
extern int motion_control__servo(void);

#endif /*_MOTION_CONTROL__SERVO_H*/
