/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * qrreader.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MOTION_LIB__QRREADER_H
#define _MOTION_LIB__QRREADER_H


/********************** Variable declarations ***********************/

extern CB_Index qrreader__num;
extern CB_Mem_Int *qrreader_idRead;
extern CB_Mem_Int *qrreader_status_act_prod;
extern CB_Mem_Float *qrreader_m11;
extern CB_Mem_Float *qrreader_m12;
extern CB_Mem_Float *qrreader_m13;
extern CB_Mem_Float *qrreader_m14;
extern CB_Mem_Float *qrreader_m21;
extern CB_Mem_Float *qrreader_m22;
extern CB_Mem_Float *qrreader_m23;
extern CB_Mem_Float *qrreader_m24;
extern CB_Mem_Float *qrreader_m31;
extern CB_Mem_Float *qrreader_m32;
extern CB_Mem_Float *qrreader_m33;
extern CB_Mem_Float *qrreader_m34;
extern CB_Mem_Float *qrreader_m41;
extern CB_Mem_Float *qrreader_m42;
extern CB_Mem_Float *qrreader_m43;
extern CB_Mem_Float *qrreader_m44;
extern CB_Mem_Int *qrreader_number;

/********************** Function declarations ***********************/

extern int _motion_lib__qrreader_init(void);
extern int motion_lib__qrreader(void);

/************************** Access macros ***************************/

#define mx_acces_motion_lib__qrreader__status_act_prod Int[0].CB_current_value
#define mx_acces_motion_lib__qrreader__m11 Float[0].CB_current_value
#define mx_acces_motion_lib__qrreader__m12 Float[1].CB_current_value
#define mx_acces_motion_lib__qrreader__m13 Float[2].CB_current_value
#define mx_acces_motion_lib__qrreader__m14 Float[3].CB_current_value
#define mx_acces_motion_lib__qrreader__m21 Float[4].CB_current_value
#define mx_acces_motion_lib__qrreader__m22 Float[5].CB_current_value
#define mx_acces_motion_lib__qrreader__m23 Float[6].CB_current_value
#define mx_acces_motion_lib__qrreader__m24 Float[7].CB_current_value
#define mx_acces_motion_lib__qrreader__m31 Float[8].CB_current_value
#define mx_acces_motion_lib__qrreader__m32 Float[9].CB_current_value
#define mx_acces_motion_lib__qrreader__m33 Float[10].CB_current_value
#define mx_acces_motion_lib__qrreader__m34 Float[11].CB_current_value
#define mx_acces_motion_lib__qrreader__m41 Float[12].CB_current_value
#define mx_acces_motion_lib__qrreader__m42 Float[13].CB_current_value
#define mx_acces_motion_lib__qrreader__m43 Float[14].CB_current_value
#define mx_acces_motion_lib__qrreader__m44 Float[15].CB_current_value
#define mx_acces_motion_lib__qrreader__number Int[1].CB_current_value

#endif /*_MOTION_LIB__QRREADER_H*/
