/*2023-10-04T11:03:51-01:00*/

/********************************************************************
 * qrreader.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"
#include "cb_products_iec.h"

#include "qrreader.h"


/**************************** Variables *****************************/

CB_Index qrreader__num = 0;
CB_Mem_Int *qrreader_idRead;
CB_Mem_Int *qrreader_status_act_prod;
CB_Mem_Float *qrreader_m11;
CB_Mem_Float *qrreader_m12;
CB_Mem_Float *qrreader_m13;
CB_Mem_Float *qrreader_m14;
CB_Mem_Float *qrreader_m21;
CB_Mem_Float *qrreader_m22;
CB_Mem_Float *qrreader_m23;
CB_Mem_Float *qrreader_m24;
CB_Mem_Float *qrreader_m31;
CB_Mem_Float *qrreader_m32;
CB_Mem_Float *qrreader_m33;
CB_Mem_Float *qrreader_m34;
CB_Mem_Float *qrreader_m41;
CB_Mem_Float *qrreader_m42;
CB_Mem_Float *qrreader_m43;
CB_Mem_Float *qrreader_m44;
CB_Mem_Int *qrreader_number;

/**************************** Variables *****************************/

#define idRead (*((short *)&(qrreader_idRead->CB_current_value) + ALIGN_OFFSET_SHORT))
#define status_act_prod (qrreader_status_act_prod->CB_current_value)
#define m11 (qrreader_m11->CB_current_value)
#define m12 (qrreader_m12->CB_current_value)
#define m13 (qrreader_m13->CB_current_value)
#define m14 (qrreader_m14->CB_current_value)
#define m21 (qrreader_m21->CB_current_value)
#define m22 (qrreader_m22->CB_current_value)
#define m23 (qrreader_m23->CB_current_value)
#define m24 (qrreader_m24->CB_current_value)
#define m31 (qrreader_m31->CB_current_value)
#define m32 (qrreader_m32->CB_current_value)
#define m33 (qrreader_m33->CB_current_value)
#define m34 (qrreader_m34->CB_current_value)
#define m41 (qrreader_m41->CB_current_value)
#define m42 (qrreader_m42->CB_current_value)
#define m43 (qrreader_m43->CB_current_value)
#define m44 (qrreader_m44->CB_current_value)
#define number (*((short *)&(qrreader_number->CB_current_value) + ALIGN_OFFSET_SHORT))


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _motion_lib__qrreader_init(void)
{
	(self.Float+0)->CB_current_value = 1.0; /*m11*/
	(self.Float+5)->CB_current_value = 1.0; /*m22*/
	(self.Float+10)->CB_current_value = 1.0; /*m33*/
	(self.Float+15)->CB_current_value = 1.0; /*m44*/
	self.Int+=2;
	self.Float+=16;


	return 0;
}


/************************ Behavior function *************************/

int motion_lib__qrreader(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		qrreader_status_act_prod = self.Int+0;
		qrreader_m11 = self.Float+0;
		qrreader_m12 = self.Float+1;
		qrreader_m13 = self.Float+2;
		qrreader_m14 = self.Float+3;
		qrreader_m21 = self.Float+4;
		qrreader_m22 = self.Float+5;
		qrreader_m23 = self.Float+6;
		qrreader_m24 = self.Float+7;
		qrreader_m31 = self.Float+8;
		qrreader_m32 = self.Float+9;
		qrreader_m33 = self.Float+10;
		qrreader_m34 = self.Float+11;
		qrreader_m41 = self.Float+12;
		qrreader_m42 = self.Float+13;
		qrreader_m43 = self.Float+14;
		qrreader_m44 = self.Float+15;
		qrreader_number = self.Int+1;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Actor Myself init *************************/

		setMyselfFor(self_num);

		/************************ Behavior execution ************************/

		{
			idRead = number;
			number = 0;
		}

		CB_post_int(qrreader_idRead);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Int += 2;
	self.Float += 16;

	return 0;
}

