/*2023-10-04T11:03:59-01:00*/

/********************************************************************
 * plc.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "plc.h"
#include "flask_motion_app/functional/modemanagement/modemanagement.h"
#include "flask_motion_app/functional/motors/motors.h"
#include "flask_motion_app/functional/robotctrl/robotctrl.h"


/**************************** Variables *****************************/

CB_Index plc__num = 0;
CB_Mem_Bool *plc_presConvUp;
CB_Mem_Bool *plc_presConvDw;
CB_Mem_Float *plc_masterPosition;
CB_Mem_Int *plc_idRead;
CB_Mem_Int *plc_mesuredWeight;
CB_Mem_Bool *plc_bpStart;
CB_Mem_Bool *plc_bpAuto;
CB_Mem_Bool *plc_bpManu;
CB_Mem_Bool *plc_bpEmergencyStop;
CB_Mem_Bool *plc_bpStop;
CB_Mem_Bool *plc_HomeCmd;
CB_Mem_Bool *plc_MoveVelCmd;
CB_Mem_Bool *plc_MoveAbsCmd;
CB_Mem_Bool *plc_MoveVel1ManualCmd;
CB_Mem_Bool *plc_MoveVel2ManualCmd;
CB_Mem_Bool *plc_MoveAbs1ManualCmd;
CB_Mem_Bool *plc_MoveAbs2ManualCmd;
CB_Mem_Bool *plc_StopCmd;
CB_Mem_Float *plc_MovePosition;
CB_Mem_Float *plc_MoveSpeed;
CB_Mem_Float *plc_MoveAcceleration;
CB_Mem_Float *plc_MoveDeceleration;
CB_Mem_Float *plc_offsetAxToMa;
CB_Mem_Bool *plc_gripSyringes;
CB_Mem_Bool *plc_Auto;
CB_Mem_Bool *plc_Manu;
CB_Mem_Bool *plc_run;
CB_Mem_Bool *plc_forwardUp;
CB_Mem_Bool *plc_backwardUp;
CB_Mem_Bool *plc_forwardDw;
CB_Mem_Bool *plc_backwardDw;
CB_Mem_Bool *plc_ejectBadProd;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset flask_motion_app__plc_offset_modemanagement;
static CB_Offset flask_motion_app__plc_offset_motors;
static CB_Offset flask_motion_app__plc_offset_robotctrl;
static CB_Offset flask_motion_app__plc_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _flask_motion_app__plc_init(void)
{
	CB_Object __start = self;
	(plc_MoveSpeed)->CB_current_value = 100.0; /*MoveSpeed*/
	(plc_MoveAcceleration)->CB_current_value = 100.0; /*MoveAcceleration*/
	(plc_MoveDeceleration)->CB_current_value = 100.0; /*MoveDeceleration*/
	self.Bool+=1;
	self.Int+=1;

	/*initialize child modemanagement (flask_motion_app.modemanagement):*/
	self_num++;
	flask_motion_app__plc_offset_modemanagement.Bool = self.Bool - __start.Bool;
	flask_motion_app__plc_offset_modemanagement.Int = self.Int - __start.Int;
	flask_motion_app__plc_offset_modemanagement.Float = self.Float - __start.Float;
	flask_motion_app__plc_offset_modemanagement.Char = self.Char - __start.Char;
	modemanagement_bpStart = plc_bpStart;
	modemanagement_bpAuto = plc_bpAuto;
	modemanagement_bpManu = plc_bpManu;
	modemanagement_bpEmergencyStop = plc_bpEmergencyStop;
	modemanagement_bpStop = plc_bpStop;
	modemanagement_Auto = plc_Auto;
	modemanagement_Manu = plc_Manu;
	modemanagement_run = plc_run;
	_flask_motion_app__modemanagement_init();

	/*initialize child motors (flask_motion_app.motors):*/
	self_num++;
	flask_motion_app__plc_offset_motors.Bool = self.Bool - __start.Bool;
	flask_motion_app__plc_offset_motors.Int = self.Int - __start.Int;
	flask_motion_app__plc_offset_motors.Float = self.Float - __start.Float;
	flask_motion_app__plc_offset_motors.Char = self.Char - __start.Char;
	motors_Auto = plc_Auto;
	motors_Manu = plc_Manu;
	motors_run = plc_run;
	motors_presConvUp = plc_presConvUp;
	motors_presConvDw = plc_presConvDw;
	motors_masterPosition = plc_masterPosition;
	motors_mesuredWeight = plc_mesuredWeight;
	motors_phaseCode = __start.Int+0; /*plc__cn_2*/
	motors_forwardUp = plc_forwardUp;
	motors_backwardUp = plc_backwardUp;
	motors_forwardDw = plc_forwardDw;
	motors_backwardDw = plc_backwardDw;
	motors_ejectBadProd = plc_ejectBadProd;
	motors_weihtOk = __start.Bool+0; /*plc__cn_1*/
	_flask_motion_app__motors_init();

	/*initialize child robotctrl (flask_motion_app.robotctrl):*/
	self_num++;
	flask_motion_app__plc_offset_robotctrl.Bool = self.Bool - __start.Bool;
	flask_motion_app__plc_offset_robotctrl.Int = self.Int - __start.Int;
	flask_motion_app__plc_offset_robotctrl.Float = self.Float - __start.Float;
	flask_motion_app__plc_offset_robotctrl.Char = self.Char - __start.Char;
	robotctrl_forwardUp = plc_forwardUp;
	robotctrl_backwardUp = plc_backwardUp;
	robotctrl_forwardDw = plc_forwardDw;
	robotctrl_backwardDw = plc_backwardDw;
	robotctrl_presConvUp = plc_presConvUp;
	robotctrl_presConvDw = plc_presConvDw;
	robotctrl_masterPosition = plc_masterPosition;
	robotctrl_Auto = plc_Auto;
	robotctrl_Manu = plc_Manu;
	robotctrl_run = plc_run;
	robotctrl_weightOk = __start.Bool+0; /*plc__cn_1*/
	robotctrl_phaseCode = __start.Int+0; /*plc__cn_2*/
	robotctrl_HomeCmd = plc_HomeCmd;
	robotctrl_MoveVelCmd = plc_MoveVelCmd;
	robotctrl_MoveAbsCmd = plc_MoveAbsCmd;
	robotctrl_MoveVel1ManualCmd = plc_MoveVel1ManualCmd;
	robotctrl_MoveVel2ManualCmd = plc_MoveVel2ManualCmd;
	robotctrl_MoveAbs1ManualCmd = plc_MoveAbs1ManualCmd;
	robotctrl_MoveAbs2ManualCmd = plc_MoveAbs2ManualCmd;
	robotctrl_StopCmd = plc_StopCmd;
	robotctrl_MovePosition = plc_MovePosition;
	robotctrl_MoveSpeed = plc_MoveSpeed;
	robotctrl_MoveAcceleration = plc_MoveAcceleration;
	robotctrl_MoveDeceleration = plc_MoveDeceleration;
	robotctrl_offsetAxToMa = plc_offsetAxToMa;
	robotctrl_gripSyringes = plc_gripSyringes;
	_flask_motion_app__robotctrl_init();

	flask_motion_app__plc_offset__end.Bool = self.Bool - __start.Bool;
	flask_motion_app__plc_offset__end.Int = self.Int - __start.Int;
	flask_motion_app__plc_offset__end.Float = self.Float - __start.Float;
	flask_motion_app__plc_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int flask_motion_app__plc(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + flask_motion_app__plc_offset_modemanagement.Bool;
			self.Int = __start.Int + flask_motion_app__plc_offset_modemanagement.Int;
			self.Float = __start.Float + flask_motion_app__plc_offset_modemanagement.Float;
			self.Char = __start.Char + flask_motion_app__plc_offset_modemanagement.Char;

			/********************* modemanagement execution *********************/

			self_num++;
			if (modemanagement__num != self_num) {
				modemanagement__num = self_num;
				modemanagement_bpStart = plc_bpStart;
				modemanagement_bpAuto = plc_bpAuto;
				modemanagement_bpManu = plc_bpManu;
				modemanagement_bpEmergencyStop = plc_bpEmergencyStop;
				modemanagement_bpStop = plc_bpStop;
				modemanagement_Auto = plc_Auto;
				modemanagement_Manu = plc_Manu;
				modemanagement_run = plc_run;
			}
			__ret = flask_motion_app__modemanagement();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* motors execution *************************/

			self_num++;
			if (motors__num != self_num) {
				motors__num = self_num;
				motors_Auto = plc_Auto;
				motors_Manu = plc_Manu;
				motors_run = plc_run;
				motors_presConvUp = plc_presConvUp;
				motors_presConvDw = plc_presConvDw;
				motors_masterPosition = plc_masterPosition;
				motors_mesuredWeight = plc_mesuredWeight;
				motors_phaseCode = __start.Int+0; /*plc__cn_2*/
				motors_forwardUp = plc_forwardUp;
				motors_backwardUp = plc_backwardUp;
				motors_forwardDw = plc_forwardDw;
				motors_backwardDw = plc_backwardDw;
				motors_ejectBadProd = plc_ejectBadProd;
				motors_weihtOk = __start.Bool+0; /*plc__cn_1*/
			}
			__ret = flask_motion_app__motors();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** robotctrl execution ************************/

			self_num++;
			if (robotctrl__num != self_num) {
				robotctrl__num = self_num;
				robotctrl_forwardUp = plc_forwardUp;
				robotctrl_backwardUp = plc_backwardUp;
				robotctrl_forwardDw = plc_forwardDw;
				robotctrl_backwardDw = plc_backwardDw;
				robotctrl_presConvUp = plc_presConvUp;
				robotctrl_presConvDw = plc_presConvDw;
				robotctrl_masterPosition = plc_masterPosition;
				robotctrl_Auto = plc_Auto;
				robotctrl_Manu = plc_Manu;
				robotctrl_run = plc_run;
				robotctrl_weightOk = __start.Bool+0; /*plc__cn_1*/
				robotctrl_phaseCode = __start.Int+0; /*plc__cn_2*/
				robotctrl_HomeCmd = plc_HomeCmd;
				robotctrl_MoveVelCmd = plc_MoveVelCmd;
				robotctrl_MoveAbsCmd = plc_MoveAbsCmd;
				robotctrl_MoveVel1ManualCmd = plc_MoveVel1ManualCmd;
				robotctrl_MoveVel2ManualCmd = plc_MoveVel2ManualCmd;
				robotctrl_MoveAbs1ManualCmd = plc_MoveAbs1ManualCmd;
				robotctrl_MoveAbs2ManualCmd = plc_MoveAbs2ManualCmd;
				robotctrl_StopCmd = plc_StopCmd;
				robotctrl_MovePosition = plc_MovePosition;
				robotctrl_MoveSpeed = plc_MoveSpeed;
				robotctrl_MoveAcceleration = plc_MoveAcceleration;
				robotctrl_MoveDeceleration = plc_MoveDeceleration;
				robotctrl_offsetAxToMa = plc_offsetAxToMa;
				robotctrl_gripSyringes = plc_gripSyringes;
			}
			__ret = flask_motion_app__robotctrl();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + flask_motion_app__plc_offset__end.Bool;
	self.Int = __start.Int + flask_motion_app__plc_offset__end.Int;
	self.Float = __start.Float + flask_motion_app__plc_offset__end.Float;
	self.Char = __start.Char + flask_motion_app__plc_offset__end.Char;

	return 0;
}

