/*2023-10-04T11:03:59-01:00*/

/********************************************************************
 * plc.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _FLASK_MOTION_APP__PLC_H
#define _FLASK_MOTION_APP__PLC_H


/********************** Variable declarations ***********************/

extern CB_Index plc__num;
extern CB_Mem_Bool *plc_presConvUp;
extern CB_Mem_Bool *plc_presConvDw;
extern CB_Mem_Float *plc_masterPosition;
extern CB_Mem_Int *plc_idRead;
extern CB_Mem_Int *plc_mesuredWeight;
extern CB_Mem_Bool *plc_bpStart;
extern CB_Mem_Bool *plc_bpAuto;
extern CB_Mem_Bool *plc_bpManu;
extern CB_Mem_Bool *plc_bpEmergencyStop;
extern CB_Mem_Bool *plc_bpStop;
extern CB_Mem_Bool *plc_HomeCmd;
extern CB_Mem_Bool *plc_MoveVelCmd;
extern CB_Mem_Bool *plc_MoveAbsCmd;
extern CB_Mem_Bool *plc_MoveVel1ManualCmd;
extern CB_Mem_Bool *plc_MoveVel2ManualCmd;
extern CB_Mem_Bool *plc_MoveAbs1ManualCmd;
extern CB_Mem_Bool *plc_MoveAbs2ManualCmd;
extern CB_Mem_Bool *plc_StopCmd;
extern CB_Mem_Float *plc_MovePosition;
extern CB_Mem_Float *plc_MoveSpeed;
extern CB_Mem_Float *plc_MoveAcceleration;
extern CB_Mem_Float *plc_MoveDeceleration;
extern CB_Mem_Float *plc_offsetAxToMa;
extern CB_Mem_Bool *plc_gripSyringes;
extern CB_Mem_Bool *plc_Auto;
extern CB_Mem_Bool *plc_Manu;
extern CB_Mem_Bool *plc_run;
extern CB_Mem_Bool *plc_forwardUp;
extern CB_Mem_Bool *plc_backwardUp;
extern CB_Mem_Bool *plc_forwardDw;
extern CB_Mem_Bool *plc_backwardDw;
extern CB_Mem_Bool *plc_ejectBadProd;

/********************** Function declarations ***********************/

extern int _flask_motion_app__plc_init(void);
extern int flask_motion_app__plc(void);

#endif /*_FLASK_MOTION_APP__PLC_H*/
